import { DualDatePipe } from '../../../shared/dual-date.pipe';
import { ChangeDetectionStrategy, Component, computed, effect, inject, input, signal } from '@angular/core';
import { JsonPipe } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { TableModule } from 'primeng/table';
import { I18nService } from '../../../core/i18n.service';
import { ToastService } from '../../../shared/toast.service';
interface SourceRow {key:string;kind:string;sourceRef:string;parentRef?:string|null}
interface Target {id:string;name?:string;title?:string;useCaseRef?:string;riskRef?:string;actionRef?:string;round?:number;useCase?:{useCaseRef:string};risk?:{riskRef:string}}
interface Member {rowKey:string;kind:string;sourceRef:string;targetRef:string;targetId:string;equal:boolean;gaps:string[];checks:Array<{field:string;source:unknown;target:unknown;equal:boolean}>}
interface Capture {id:string;round:number;digest:string;createdAt:string;bindings:Array<{rowKey:string;targetId:string}>;report:{sourceCount:number;linkedCount:number;equalCount:number;gapCount:number;targetZeroDiff:boolean;pilotReady:boolean;missingPilotRefs:string[];members:Member[]};review:{outcome:string;justification:string}|null}
interface Archive {rows:Capture[];total:number;page:number;pageSize:number;latestRound:number}
@Component({selector:'app-ai-native-pilot',standalone:true,imports:[DualDatePipe,JsonPipe,FormsModule,TableModule],template:`
<section class="ds-card decision-card"><h2>{{ t('aiCycle.pilotTitle') }}</h2><p>{{ t('aiCycle.pilotHelp') }}</p>
@if(archive();as a){@if(canPropose()){<div class="review-fields"><label>{{ t('aiCycle.sourceRow') }}<select class="ds-input" [ngModel]="rowKey()" (ngModelChange)="choose($event)"><option value="">—</option>@for(r of nativeRows();track r.key){<option [value]="r.key">{{ r.sourceRef }} · {{ t('aiMigration.kind.'+r.kind) }}</option>}</select></label><label>{{ t('aiLibrary.search') }}<input class="ds-input" [ngModel]="search()" (ngModelChange)="search.set($event)" (keydown.enter)="loadTargets()"/><button type="button" class="ds-btn ds-btn--ghost" [disabled]="working()||!rowKey()" (click)="loadTargets()">{{ t('aiLibrary.search') }}</button></label><label>{{ t('aiCycle.nativeTarget') }}<select class="ds-input" [ngModel]="targetId()" (ngModelChange)="targetId.set($event)"><option value="">—</option>@for(target of targets();track target.id){<option [value]="target.id">{{ targetLabel(target) }}</option>}</select><span>{{ targets().length }} / {{ targetTotal() }}</span></label></div><div class="review-actions"><button type="button" class="ds-btn ds-btn--ghost" [disabled]="working()||!rowKey()||!targetId()" (click)="bind()">{{ t('aiCycle.bind') }}</button>@if(selectedRow()?.kind==='usecase'||selectedRow()?.kind==='risk'){<button type="button" class="ds-btn ds-btn--ghost" [disabled]="working()||!reason().trim()||!evidence().trim()" (click)="draft()">{{ t('aiCycle.nativeDraft') }}</button>}<button type="button" class="ds-btn ds-btn--ghost" [disabled]="working()||!rowKey()" (click)="remove()">{{ t('aiCycle.removeBinding') }}</button></div><p>{{ t('aiCycle.draftHelp') }}</p><p-table [value]="bindings()" [paginator]="bindings().length>10" [rows]="10"><ng-template #header><tr><th>{{ t('aiCycle.sourceRow') }}</th><th>{{ t('aiCycle.nativeTarget') }}</th></tr></ng-template><ng-template #body let-b><tr><td>{{ sourceLabel(b.rowKey) }}</td><td>{{ b.label||b.targetId }}</td></tr></ng-template></p-table>}
@if(canPropose()||canReview()){<div class="review-fields"><label>{{ t('aiMigration.justification') }}<textarea class="ds-input" [ngModel]="reason()" (ngModelChange)="reason.set($event)"></textarea></label><label>{{ t('aiMigration.evidence') }}<input class="ds-input" [ngModel]="evidence()" (ngModelChange)="evidence.set($event)"/></label></div>}
@if(canPropose()){<button type="button" class="ds-btn ds-btn--primary" [disabled]="working()||!reason().trim()||!evidence().trim()" (click)="capture()">{{ t('aiCycle.capture') }}</button>}
<p-table [value]="a.rows" [stripedRows]="true"><ng-template #header><tr><th>{{ t('aiCycle.round') }}</th><th>{{ t('aiCycle.targetEquality') }}</th><th>{{ t('aiMigration.review') }}</th></tr></ng-template><ng-template #body let-v><tr><td>{{ v.round }} · {{ v.createdAt | dgopDualDate:'medium':i18n.lang() }}<button type="button" class="ds-btn ds-btn--ghost" (click)="detail.set(v)">{{ t('aiControls.reconciliation') }}</button><button type="button" class="ds-btn ds-btn--ghost" [disabled]="working()" (click)="download(v,'json')">JSON</button><button type="button" class="ds-btn ds-btn--ghost" [disabled]="working()" (click)="download(v,'csv')">CSV</button></td><td>{{ v.report.equalCount }} / {{ v.report.sourceCount }}<p>{{ t('aiCycle.gaps') }}: {{ v.report.gapCount }}</p></td><td>{{ t('aiCorrection.'+(v.review?.outcome??'pending')) }}@if(v.review){<p>{{ v.review.justification }}</p>}@if(canReview()&&!v.review&&v.round===a.latestRound){<button type="button" class="ds-btn ds-btn--primary" [disabled]="working()||!v.report.pilotReady||!reason().trim()||!evidence().trim()" (click)="review(v,'approve')">{{ t('aiCycle.signOff') }}</button><button type="button" class="ds-btn ds-btn--ghost" [disabled]="working()||!reason().trim()||!evidence().trim()" (click)="review(v,'return')">{{ t('aiCorrection.return') }}</button>}</td></tr></ng-template></p-table>@if(a.total>a.pageSize){<div class="review-actions"><button type="button" class="ds-btn ds-btn--ghost" [disabled]="a.page===1||working()" (click)="load(a.page-1)">{{ t('aiReviews.previous') }}</button><span>{{ a.page }}</span><button type="button" class="ds-btn ds-btn--ghost" [disabled]="a.page*a.pageSize>=a.total||working()" (click)="load(a.page+1)">{{ t('aiReviews.next') }}</button></div>}
@if(detail();as d){<h3>{{ t('aiCycle.targetEquality') }} · {{ d.report.equalCount }} / {{ d.report.sourceCount }}</h3><p>{{ t('aiCycle.missingPilot') }}: {{ d.report.missingPilotRefs.join(', ')||'—' }}</p><p-table [value]="d.report.members" [paginator]="true" [rows]="10" [stripedRows]="true"><ng-template #header><tr><th>{{ t('aiCycle.sourceRow') }}</th><th>{{ t('aiCycle.nativeTarget') }}</th><th>{{ t('aiCycle.gaps') }}</th></tr></ng-template><ng-template #body let-r><tr><td>{{ r.sourceRef }}</td><td>{{ r.targetRef||'—' }}</td><td>@for(g of r.gaps;track g){<p>{{ g }}</p>}<details><summary>{{ t('aiControls.reconciliation') }}</summary><pre>{{ r.checks | json }}</pre></details></td></tr></ng-template></p-table>}
}@else if(error()){<button type="button" class="ds-btn ds-btn--ghost" (click)="load()">{{ t('crud.retry') }}</button>}@else{<p role="status">{{ t('crud.loading') }}</p>}</section>`,styleUrls:['../ai-review/ai-review.scss','../ai-reviews/ai-reviews.scss','./ai-migration.scss'],changeDetection:ChangeDetectionStrategy.OnPush})
export class AiNativePilot {
 readonly snapshotId=input.required<string>();readonly digest=input.required<string>();readonly rows=input.required<SourceRow[]>();readonly canPropose=input(false);readonly canReview=input(false);private readonly http=inject(HttpClient);protected readonly i18n=inject(I18nService);private readonly toast=inject(ToastService);protected readonly archive=signal<Archive|null>(null);protected readonly detail=signal<Capture|null>(null);protected readonly rowKey=signal('');protected readonly targetId=signal('');protected readonly targets=signal<Target[]>([]);protected readonly targetTotal=signal(0);protected readonly bindings=signal<Array<{rowKey:string;targetId:string;label?:string}>>([]);protected readonly reason=signal('');protected readonly evidence=signal('');protected readonly search=signal('');protected readonly working=signal(false);protected readonly error=signal(false);protected readonly nativeRows=computed(()=>this.rows().filter(r=>['usecase','risk','classification','assessment','action'].includes(r.kind)));protected readonly selectedRow=computed(()=>this.rows().find(r=>r.key===this.rowKey()));private sequence=0;private targetsSequence=0;private key='';private body='';
 constructor(){effect(()=>{this.snapshotId();++this.targetsSequence;this.bindings.set([]);this.detail.set(null);this.rowKey.set('');this.targets.set([]);this.targetId.set('');this.reason.set('');this.evidence.set('');this.key='';this.body='';void this.load();});}protected t(k:string){return this.i18n.t(k);}protected sourceLabel(key:string){return this.rows().find(r=>r.key===key)?.sourceRef??key;}protected targetLabel(v:Target){return [v.useCaseRef||v.riskRef||v.actionRef||v.risk?.riskRef||v.useCase?.useCaseRef||this.t('aiCycle.draft'),v.name||v.title,v.round?'#'+v.round:''].filter(Boolean).join(' · ');}
 protected choose(key:string){this.rowKey.set(key);this.targetId.set('');this.search.set(this.sourceLabel(key));void this.loadTargets();}protected async loadTargets(kind=this.selectedRow()?.kind){if(!kind)return;const seq=++this.targetsSequence;this.targets.set([]);this.targetTotal.set(0);try{const data=await firstValueFrom(this.http.get<{rows:Target[];total:number}>('/api/ai/migration-pilot/snapshots/'+this.snapshotId()+'/targets?kind='+kind+'&search='+encodeURIComponent(this.search())));if(seq===this.targetsSequence){this.targets.set(data.rows);this.targetTotal.set(data.total);}}catch(e){if(seq===this.targetsSequence)this.toast.errorFrom(e,this.t('aiControls.error'));}}
 protected bind(){const target=this.targets().find(t=>t.id===this.targetId());if(!target)return;this.bindings.update(b=>[...b.filter(x=>x.rowKey!==this.rowKey()),{rowKey:this.rowKey(),targetId:target.id,label:this.targetLabel(target)}]);}protected remove(){this.bindings.update(b=>b.filter(x=>x.rowKey!==this.rowKey()));}private ids(){return [...new Set(this.evidence().split(/[\s,;]+/u).filter(Boolean))];}
 protected async load(page=1){const seq=++this.sequence;this.error.set(false);try{const a=await firstValueFrom(this.http.get<Archive>('/api/ai/migration-pilot/snapshots/'+this.snapshotId()+'/captures?page='+page));if(seq===this.sequence){this.archive.set(a);if(!this.bindings().length&&page===1)this.bindings.set(a.rows[0]?.bindings??[]);}}catch(e){if(seq===this.sequence){this.error.set(true);this.toast.errorFrom(e,this.t('aiControls.error'));}}}
 protected async capture(){const a=this.archive();if(!a)return;await this.request('/api/ai/migration-pilot/snapshots/'+this.snapshotId()+'/captures',{expectedRound:a.latestRound,expectedDigest:this.digest(),bindings:this.bindings().map(({rowKey,targetId})=>({rowKey,targetId})),justification:this.reason(),evidenceIds:this.ids()},true);}
 protected async draft(){const r=this.selectedRow();if(!r)return;let useCaseId:string|undefined;if(r.kind==='risk'){const parent=this.rows().find(row=>row.kind==='usecase'&&row.sourceRef===r.parentRef);useCaseId=parent?this.bindings().find(b=>b.rowKey===parent.key)?.targetId:undefined;if(!useCaseId){this.toast.error(this.t('aiCycle.bindParent'));return;}}await this.request('/api/ai/migration-pilot/snapshots/'+this.snapshotId()+'/native-drafts',{rowKey:r.key,expectedDigest:this.digest(),...(useCaseId?{useCaseId}:{}),justification:this.reason(),evidenceIds:this.ids()},true);}
 protected async review(v:Capture,outcome:string){await this.request('/api/ai/migration-pilot/captures/'+v.id+'/review',{outcome,expectedDigest:v.digest,justification:this.reason(),evidenceIds:this.ids()},false);}
 private async request(url:string,body:Record<string,unknown>,replay:boolean){if(this.working())return;const id=this.snapshotId(),serialized=JSON.stringify({id,url,body});if(replay&&(serialized!==this.body||!this.key)){this.body=serialized;this.key=crypto.randomUUID();}this.working.set(true);try{const result=await firstValueFrom(this.http.post<Capture&{targetUseCaseId?:string;targetRiskId?:string}>(url,{...body,...(replay?{requestKey:this.key}:{})}));if(id===this.snapshotId()){if(result.targetUseCaseId||result.targetRiskId)this.bindings.update(b=>[...b.filter(x=>x.rowKey!==body['rowKey']),{rowKey:String(body['rowKey']),targetId:result.targetUseCaseId||result.targetRiskId!,label:this.t('aiCycle.draft')}]);this.key='';this.body='';this.toast.success(this.t('aiControls.saved'));await this.load();}}catch(e){this.toast.errorFrom(e,this.t('aiControls.error'));}finally{this.working.set(false);}}
 protected async download(v:Capture,format:string){if(this.working())return;this.working.set(true);try{const b=await firstValueFrom(this.http.get('/api/ai/migration-pilot/captures/'+v.id+'/export?format='+format,{responseType:'blob'})),url=URL.createObjectURL(b),link=document.createElement('a');link.href=url;link.download='dgop-ai-native-pilot.'+format;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){this.toast.errorFrom(e,this.t('aiControls.error'));}finally{this.working.set(false);}}
}
