import { AiEvidencePanel } from '../../../shared/ai-evidence-panel';
import { DualDatePipe } from '../../../shared/dual-date.pipe';
import { AiNativePilot } from './ai-native-pilot';
import { ChangeDetectionStrategy, Component, computed, inject, Input, OnChanges, signal } from '@angular/core';
import { JsonPipe } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { TableModule } from 'primeng/table';
import { I18nService } from '../../../core/i18n.service';
import { ToastService } from '../../../shared/toast.service';
interface SourceReconciliation {requestedCount:number;targetProposalCount:number;publishedCount:number;selectedLibraryZeroDiff:boolean;members:Array<{rowKey:string;sourceRef:string;targetRef:string;published:boolean;sourceUnchanged:boolean;projectionUnchanged:boolean;contentEqual:boolean;identifierEqual:boolean;targetIntegrity:boolean}>}
interface Binding {rowKey:string;field:string;value:string}
interface Rule {column:string;kind:string;listCode?:string}
interface Version {id:string;round:number;digest:string;proposedBy:string;justification:string;entries:Binding[];review:{outcome:string;justification:string}|null;snapshot:{id:string;digest:string}|null}
interface Control {id:string;entryId:string;sourceRowKey:string;round:number;digest:string;entry:{controlCode:string};content:Record<string,string>;dimensionPins:Array<{code:string}>;publication:unknown}
interface Context {canPropose:boolean;canReview:boolean;latestRound:number;rules:Record<string,Record<string,Rule>>;rows:Array<{key:string;kind:string;sourceRef:string}>;references:Array<{listCode:string;versionId:string;values:Array<{code:string;labelEn:string;labelAr:string}>}>;people:Array<{id:string;labels:string[]}>;units:Array<{id:string;labels:string[]}>;dimensions:Array<{code:string;labelEn:string;labelAr:string}>;controls:Control[];selectableControls:Control[];versions:Version[]}
@Component({selector:'app-ai-source-corrections',standalone:true,imports:[AiEvidencePanel,AiNativePilot,DualDatePipe,JsonPipe,FormsModule,TableModule],templateUrl:'./ai-source-corrections.html',styleUrls:['../ai-review/ai-review.scss','../ai-reviews/ai-reviews.scss','./ai-migration.scss'],changeDetection:ChangeDetectionStrategy.OnPush})
export class AiSourceCorrections implements OnChanges {
 @Input({required:true}) previewId='';private readonly http=inject(HttpClient);protected readonly i18n=inject(I18nService);private readonly toast=inject(ToastService);
 protected readonly context=signal<Context|null>(null);protected readonly state=signal<'loading'|'ok'|'error'>('loading');protected readonly working=signal(false);protected readonly tab=signal('bindings');
 protected readonly rowKey=signal('');protected readonly field=signal('');protected readonly value=signal('');protected readonly entries=signal<Binding[]>([]);protected readonly justification=signal('');protected readonly evidence=signal('');
 protected readonly controlRow=signal('');protected readonly controlCode=signal('');protected readonly controlRound=signal(0);protected readonly titleEn=signal('');protected readonly titleAr=signal('');protected readonly dimensionCodes=signal<string[]>([]);
 protected readonly snapshot=signal<{id:string;digest:string;createdAt:string;report:{rows:Array<{key:string;kind:string;sourceRef:string;status:string;sample:boolean;prepared:Record<string,unknown>}>;reconciliation:{preparedCount:number;quarantinedCount:number;targetCollisionCount:number};correction:{changes:Array<Record<string,unknown>>;collisions:Array<{kind:string;reference:string;targetId:string}>}}}|null>(null);
 protected readonly fields=computed(()=>Object.keys(this.context()?.rules[this.context()?.rows.find(r=>r.key===this.rowKey())?.kind??'']??{}));
 protected readonly rule=computed(()=>this.context()?.rules[this.context()?.rows.find(r=>r.key===this.rowKey())?.kind??'']?.[this.field()]);
 protected readonly options=computed(()=>{const rule=this.rule(),c=this.context();if(!rule||!c)return [];if(rule.kind==='reference'){const versions=c.references.filter(v=>v.listCode===rule.listCode);return versions.length===1?versions[0].values.map(v=>({value:v.code,label:this.label(v)})):[];}if(rule.kind==='person'||rule.kind==='unit')return (rule.kind==='person'?c.people:c.units).map(p=>({value:p.id,label:p.labels[this.i18n.lang()==='ar'?0:1]??p.labels[0]}));if(rule.kind==='control')return c.selectableControls.filter(v=>v.sourceRowKey===this.rowKey()).map(v=>({value:v.id,label:v.entry.controlCode+' · '+v.content[this.i18n.lang()==='ar'?'titleAr':'titleEn']}));return [];});
 protected readonly controlRows=computed(()=>this.context()?.rows.filter(r=>r.kind==='control')??[]);
 protected readonly sourceSelection=signal<string[]>([]);protected readonly imports=signal<{rows:Array<{id:string;createdAt:string;items:Array<{libraryVersionId:string;sourceRef:string;version:{publication:unknown}}>}>;total:number;page:number;pageSize:number}>({rows:[],total:0,page:1,pageSize:20});protected readonly reconciliation=signal<SourceReconciliation|null>(null);protected readonly eligibleLibrary=computed(()=>this.snapshot()?.report.rows.filter(r=>r.kind==='library'&&r.status==='prepared'&&!r.sample)??[]);
 private sourceSequence=0;private sourceKey='';private sourceBody='';private sequence=0;private snapshotSequence=0;private requestKey='';private requestBody='';
 ngOnChanges(){++this.sourceSequence;this.sourceSelection.set([]);this.imports.set({rows:[],total:0,page:1,pageSize:20});this.reconciliation.set(null);this.context.set(null);this.rowKey.set('');this.field.set('');this.value.set('');this.entries.set([]);this.snapshot.set(null);this.tab.set('bindings');this.editControl();this.tab.set('bindings');this.requestKey='';this.requestBody='';++this.snapshotSequence;void this.load();}
 protected t(k:string){return this.i18n.t(k);}protected label(v:{labelEn:string;labelAr:string}){return this.i18n.lang()==='ar'?v.labelAr:v.labelEn;}
 protected ids(){return [...new Set(this.evidence().split(/[\s,;]+/u).filter(Boolean))];}
 protected chooseRow(value:string){this.rowKey.set(value);this.field.set('');this.value.set('');}protected chooseField(value:string){this.field.set(value);this.value.set('');}
 protected add(){if(!this.rule()||!this.value().trim())return;this.entries.update(entries=>[...entries.filter(e=>e.rowKey!==this.rowKey()||e.field!==this.field()),{rowKey:this.rowKey(),field:this.field(),value:this.value()}]);this.value.set('');}
 protected remove(index:number){this.entries.update(entries=>entries.filter((_,i)=>i!==index));}
 protected revise(v:Version){this.entries.set(v.entries.map(e=>({rowKey:e.rowKey,field:e.field,value:e.value})));this.justification.set('');this.evidence.set('');this.tab.set('bindings');}
 protected editControl(v?:Control){this.controlRow.set(v?.sourceRowKey??'');this.controlCode.set(v?.entry.controlCode??'');this.controlRound.set(v?.round??0);this.titleEn.set(v?.content['titleEn']??'');this.titleAr.set(v?.content['titleAr']??'');this.dimensionCodes.set(v?.dimensionPins.map(p=>p.code)??[]);this.justification.set('');this.evidence.set('');this.tab.set('controls');}
 protected toggle(code:string){this.dimensionCodes.update(c=>c.includes(code)?c.filter(v=>v!==code):[...c,code]);}
 protected latestControl(v:Control){return !this.context()?.controls.some(x=>x.entryId===v.entryId&&x.round>v.round);}
 protected async load(){const seq=++this.sequence;this.state.set('loading');try{const c=await firstValueFrom(this.http.get<Context>(`/api/ai/source-corrections/previews/${this.previewId}/context`));if(seq===this.sequence){this.context.set(c);this.state.set('ok');}}catch(e){if(seq===this.sequence){this.state.set('error');this.toast.errorFrom(e,this.t('aiCorrection.error'));}}}
 private async mutate(path:string,body:unknown,capture=false){if(this.working())return;const previewId=this.previewId;this.working.set(true);try{const response=await firstValueFrom(this.http.post<{id:string}>(path,body));if(previewId===this.previewId){this.justification.set('');this.evidence.set('');await this.load();if(capture)await this.openSnapshot(response.id);this.toast.success(this.t('aiCorrection.saved'));}return response;}catch(e){this.toast.errorFrom(e,this.t('aiCorrection.error'));return null;}finally{this.working.set(false);}}
 protected async propose(){const c=this.context();if(!c?.canPropose)return;const previewId=this.previewId;const body={expectedRound:c.latestRound,entries:this.entries(),justification:this.justification(),evidenceIds:this.ids()},serialized=JSON.stringify(body);if(serialized!==this.requestBody||!this.requestKey){this.requestKey=crypto.randomUUID();this.requestBody=serialized;}if(await this.mutate(`/api/ai/source-corrections/previews/${this.previewId}/versions`,{...body,requestKey:this.requestKey})&&previewId===this.previewId){this.requestKey='';this.requestBody='';this.entries.set([]);this.tab.set('history');}}
 protected async review(v:Version,outcome:string){await this.mutate(`/api/ai/source-corrections/versions/${v.id}/review`,{outcome,expectedDigest:v.digest,justification:this.justification(),evidenceIds:this.ids()});}
 protected async capture(v:Version){await this.mutate(`/api/ai/source-corrections/versions/${v.id}/capture`,{expectedDigest:v.digest,justification:this.justification(),evidenceIds:this.ids()},true);}
 protected async proposeControl(){await this.mutate(`/api/ai/source-corrections/previews/${this.previewId}/controls`,{sourceRowKey:this.controlRow(),controlCode:this.controlCode(),expectedRound:this.controlRound(),titleEn:this.titleEn(),titleAr:this.titleAr(),dimensionCodes:this.dimensionCodes(),justification:this.justification(),evidenceIds:this.ids()});}
 protected async publish(v:Control){await this.mutate(`/api/ai/source-corrections/controls/${v.id}/publish`,{expectedDigest:v.digest,justification:this.justification(),evidenceIds:this.ids()});}
 protected async openSnapshot(id:string){const seq=++this.snapshotSequence;try{const s=await firstValueFrom(this.http.get<NonNullable<ReturnType<typeof this.snapshot>>>(`/api/ai/source-corrections/snapshots/${id}`));if(seq===this.snapshotSequence){this.snapshot.set(s);this.sourceSelection.set([]);this.reconciliation.set(null);this.tab.set('snapshot');await this.loadImports();}}catch(e){this.toast.errorFrom(e,this.t('aiCorrection.error'));}}
 protected toggleSource(key:string){this.sourceSelection.update(v=>v.includes(key)?v.filter(x=>x!==key):[...v,key]);}
 protected async loadImports(page=1){const id=this.snapshot()?.id;if(!id)return;const seq=++this.sourceSequence;try{const data=await firstValueFrom(this.http.get<ReturnType<typeof this.imports>>('/api/ai/library-sources/snapshots/'+id+'/imports?page='+page));if(seq===this.sourceSequence&&id===this.snapshot()?.id)this.imports.set(data);}catch(e){this.toast.errorFrom(e,this.t('aiControls.error'));}}
 protected async proposeSource(){const snapshot=this.snapshot(),id=snapshot?.id;if(!snapshot||!id||this.working())return;const body={rowKeys:this.sourceSelection(),expectedDigest:(snapshot as unknown as {digest:string}).digest,justification:this.justification(),evidenceIds:this.ids()},serialized=JSON.stringify({id,body});if(this.sourceBody!==serialized||!this.sourceKey){this.sourceBody=serialized;this.sourceKey=crypto.randomUUID();}this.working.set(true);try{await firstValueFrom(this.http.post('/api/ai/library-sources/snapshots/'+id+'/proposals',{...body,requestKey:this.sourceKey}));if(id===this.snapshot()?.id){this.sourceSelection.set([]);this.sourceKey='';this.sourceBody='';this.justification.set('');this.evidence.set('');await this.loadImports();this.toast.success(this.t('aiControls.saved'));}}catch(e){this.toast.errorFrom(e,this.t('aiControls.error'));}finally{this.working.set(false);}}
 protected async publishSource(versionId:string){if(this.working())return;this.working.set(true);const id=this.snapshot()?.id;try{await firstValueFrom(this.http.post('/api/ai/risk-library/versions/'+versionId+'/publish',{justification:this.justification(),evidenceIds:this.ids()}));if(id===this.snapshot()?.id){await this.loadImports();this.reconciliation.set(null);this.toast.success(this.t('aiControls.saved'));}}catch(e){this.toast.errorFrom(e,this.t('aiControls.error'));}finally{this.working.set(false);}}
 protected async reconcileSource(id:string){const snapshotId=this.snapshot()?.id;try{const data=await firstValueFrom(this.http.get<SourceReconciliation>('/api/ai/library-sources/imports/'+id+'/reconciliation'));if(snapshotId===this.snapshot()?.id)this.reconciliation.set(data);}catch(e){this.toast.errorFrom(e,this.t('aiControls.error'));}}
 protected async downloadSource(id:string,format:string){if(this.working())return;this.working.set(true);try{const blob=await firstValueFrom(this.http.get('/api/ai/library-sources/imports/'+id+'/export?format='+format,{responseType:'blob'})),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dgop-ai-library-reconciliation.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){this.toast.errorFrom(e,this.t('aiControls.error'));}finally{this.working.set(false);}}
 protected async download(format:string){const snapshot=this.snapshot();if(!snapshot||this.working())return;this.working.set(true);try{const blob=await firstValueFrom(this.http.get(`/api/ai/source-corrections/snapshots/${snapshot.id}/export?format=${format}`,{responseType:'blob'})),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dgop-ai-source-corrections.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){this.toast.errorFrom(e,this.t('aiCorrection.error'));}finally{this.working.set(false);}}
}
