import { AiEvidencePanel } from '../../../shared/ai-evidence-panel';
import { ChangeDetectionStrategy, Component, computed, inject, OnInit, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { TableModule } from 'primeng/table';
import { I18nService } from '../../../core/i18n.service';
import { ToastService } from '../../../shared/toast.service';
import { AiControlPicker, ControlTag } from './ai-control-picker';
interface Mapping {id:string;categoryCode:string;round:number;digest:string;controlPins:ControlTag[];justification:string;review:{outcome:string;justification:string}|null}
interface Context {categories:Array<{code:string;labelEn:string;labelAr:string}>;controls:ControlTag[];versions:Mapping[];canPropose:boolean;canReview:boolean}
@Component({selector:'app-ai-category-controls',standalone:true,imports:[AiEvidencePanel,FormsModule,TableModule,AiControlPicker],template:`
<section class="ds-card decision-card"><h2>{{ t('aiCycle.categoryTitle') }}</h2><p>{{ t('aiCycle.categoryHelp') }}</p>
@if(context();as c){<div class="review-fields"><label>{{ t('aiCycle.category') }}<select class="ds-input" [ngModel]="category()" (ngModelChange)="choose($event)">@for(cat of c.categories;track cat.code){<option [value]="cat.code">{{ i18n.lang()==='ar'?cat.labelAr:cat.labelEn }}</option>}</select></label>
@if(c.canPropose||c.canReview){<label>{{ t('aiMigration.justification') }}<textarea class="ds-input" [ngModel]="reason()" (ngModelChange)="reason.set($event)"></textarea></label><label>{{ t('aiMigration.evidence') }}<input class="ds-input" [ngModel]="evidence()" (ngModelChange)="evidence.set($event)"/></label>}</div>
@if(c.canPropose){<app-ai-control-picker [choices]="c.controls" [selected]="selected()" [disabled]="working()" (changed)="selected.set($event)"/><button type="button" class="ds-btn ds-btn--primary" [disabled]="working()||!category()||!reason().trim()||!evidence().trim()" (click)="propose()">{{ t('aiCycle.proposeMapping') }}</button>}
<p-table [value]="versions()" [paginator]="versions().length>10" [rows]="10" [stripedRows]="true"><ng-template #header><tr><th>{{ t('aiCycle.round') }}</th><th>{{ t('aiControls.tags') }}</th><th>{{ t('aiMigration.review') }}</th></tr></ng-template><ng-template #body let-v><tr><td><app-ai-evidence-panel targetType="ai_category_control_mapping" [targetId]="v.id" />{{ v.round }}<p>{{ v.justification }}</p></td><td>@for(p of v.controlPins;track p.versionId){<p>{{ p.controlCode }} · {{ i18n.lang()==='ar'?p.titleAr:p.titleEn }}</p>}</td><td>{{ t('aiCorrection.'+(v.review?.outcome??'pending')) }}@if(v.review){<p>{{ v.review.justification }}</p>}@if(c.canReview&&!v.review&&v.round===latestRound()){<button type="button" class="ds-btn ds-btn--primary" [disabled]="working()||!reason().trim()||!evidence().trim()" (click)="review(v,'approve')">{{ t('aiCorrection.approve') }}</button><button type="button" class="ds-btn ds-btn--ghost" [disabled]="working()||!reason().trim()||!evidence().trim()" (click)="review(v,'return')">{{ t('aiCorrection.return') }}</button>}</td></tr></ng-template></p-table>
}@else if(error()){<button type="button" class="ds-btn ds-btn--ghost" (click)="load()">{{ t('crud.retry') }}</button>}@else{<p role="status">{{ t('crud.loading') }}</p>}</section>`,styleUrls:['../ai-review/ai-review.scss','../ai-reviews/ai-reviews.scss','./ai-risks.scss'],changeDetection:ChangeDetectionStrategy.OnPush})
export class AiCategoryControls implements OnInit {
 private readonly http=inject(HttpClient);protected readonly i18n=inject(I18nService);private readonly toast=inject(ToastService);protected readonly context=signal<Context|null>(null);protected readonly category=signal('');protected readonly selected=signal<string[]>([]);protected readonly reason=signal('');protected readonly evidence=signal('');protected readonly working=signal(false);protected readonly error=signal(false);protected readonly versions=computed(()=>this.context()?.versions.filter(v=>v.categoryCode===this.category())??[]);protected readonly latestRound=computed(()=>this.versions()[0]?.round??0);private sequence=0;
 ngOnInit(){void this.load();}protected t(k:string){return this.i18n.t(k);}protected choose(code:string){this.category.set(code);this.selected.set(this.versions().find(v=>v.review?.outcome==='approve')?.controlPins.map(p=>p.versionId)??[]);this.reason.set('');this.evidence.set('');}
 protected async load(){const seq=++this.sequence;this.error.set(false);try{const c=await firstValueFrom(this.http.get<Context>('/api/ai/category-control-mappings'));if(seq===this.sequence){this.context.set(c);this.choose(this.category()||c.categories[0]?.code||'');}}catch(e){if(seq===this.sequence){this.error.set(true);this.toast.errorFrom(e,this.t('aiControls.error'));}}}
 private ids(){return [...new Set(this.evidence().split(/[\s,;]+/u).filter(Boolean))];}protected async propose(){await this.mutate('/api/ai/category-control-mappings/categories/'+encodeURIComponent(this.category()),{expectedRound:this.latestRound(),controlVersionIds:this.selected(),justification:this.reason(),evidenceIds:this.ids()});}protected async review(v:Mapping,outcome:string){await this.mutate('/api/ai/category-control-mappings/'+v.id+'/review',{outcome,expectedDigest:v.digest,justification:this.reason(),evidenceIds:this.ids()});}
 private async mutate(url:string,body:unknown){if(this.working())return;this.working.set(true);try{await firstValueFrom(this.http.post(url,body));this.toast.success(this.t('aiControls.saved'));await this.load();}catch(e){this.toast.errorFrom(e,this.t('aiControls.error'));}finally{this.working.set(false);}}
}
