import { ChangeDetectionStrategy, Component, EventEmitter, inject, OnInit, Output, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import { I18nService } from '../../../core/i18n.service';
import { ToastService } from '../../../shared/toast.service';
import { AiRiskLibrary, LibraryRow } from './ai-risk-library';
@Component({selector:'app-ai-risk-initiation',standalone:true,imports:[FormsModule,AiRiskLibrary],template:`<section class="ds-card decision-card"><header class="section-head"><h2>{{ t('aiInitiation.title') }}</h2><button type="button" class="ds-btn ds-btn--ghost" (click)="showLibrary.set(!showLibrary())">{{ t('aiLibrary.title') }}</button></header><p>{{ t('aiInitiation.help') }}</p>@if(state()==='loading'){<p role="status">{{ t('crud.loading') }}</p>}@else if(state()==='error'){<p>{{ t('aiInitiation.error') }}</p><button type="button" class="ds-btn ds-btn--ghost" (click)="load()">{{ t('crud.retry') }}</button>}@else if(context().canCreate){<fieldset [disabled]="working()"><label><span>{{ t('aiInitiation.useCase') }}</span><select [ngModel]="useCaseId()" (ngModelChange)="useCaseId.set($event)"><option value="">{{ t('aiuc.select') }}</option>@for(p of context().parents;track p.id){<option [value]="p.id">{{ p.useCaseRef }} · {{ p.name }}</option>}</select></label>@if(library();as l){<p>{{ t('aiInitiation.librarySource') }} · {{ l.libraryRef }} · {{ t('aiDashboard.round') }} {{ l.round }}</p><button type="button" class="ds-btn ds-btn--ghost" (click)="library.set(null)">{{ t('aiInitiation.manual') }}</button>}<label><span>{{ t('aiReview.justification') }}</span><textarea rows="2" maxlength="5000" [ngModel]="justification()" (ngModelChange)="justification.set($event)"></textarea></label><button type="button" class="ds-btn ds-btn--primary" [disabled]="!useCaseId()||!justification().trim()" (click)="create()">{{ t('aiInitiation.create') }}</button></fieldset>}@else{<p>{{ t('aiInitiation.readOnly') }}</p>}</section>@if(showLibrary()){<app-ai-risk-library [allowChoose]="context().canCreate" (chosen)="choose($event)"/>}`,styleUrls:['../ai-review/ai-review.scss','./ai-risks.scss'],changeDetection:ChangeDetectionStrategy.OnPush})
export class AiRiskInitiation implements OnInit {
 @Output() created=new EventEmitter<string>();
 private readonly http=inject(HttpClient);private readonly i18n=inject(I18nService);private readonly toast=inject(ToastService);
 protected readonly context=signal<{canCreate:boolean;parents:Array<{id:string;useCaseRef:string;name:string}>}>({canCreate:false,parents:[]});protected readonly state=signal<'loading'|'ok'|'error'>('loading');protected readonly working=signal(false);protected readonly showLibrary=signal(false);protected readonly library=signal<LibraryRow|null>(null);protected readonly useCaseId=signal('');protected readonly justification=signal('');
 private requestKey='';private requestSignature='';
 protected t(k:string){return this.i18n.t(k);}
 ngOnInit(){void this.load();}
 protected choose(row:LibraryRow){if(this.context().canCreate){this.library.set(row);this.showLibrary.set(false);}}
 protected async load(){this.state.set('loading');try{this.context.set(await firstValueFrom(this.http.get<{canCreate:boolean;parents:Array<{id:string;useCaseRef:string;name:string}>}>('/api/ai/risks/initiation')));this.state.set('ok');}catch(e){this.state.set('error');this.toast.errorFrom(e,this.t('aiInitiation.error'));}}
 protected async create(){if(!this.context().canCreate||this.working())return;this.working.set(true);const signature=JSON.stringify([this.useCaseId(),this.library()?.versionId??null,this.justification()]);if(signature!==this.requestSignature){this.requestKey=crypto.randomUUID();this.requestSignature=signature;}
  try{const r=await firstValueFrom(this.http.post<{id:string}>('/api/ai/risks',{useCaseId:this.useCaseId(),libraryVersionId:this.library()?.versionId,initiationKey:this.requestKey,justification:this.justification()}));this.requestSignature='';this.justification.set('');this.library.set(null);this.toast.success(this.t('aiInitiation.created'));this.created.emit(r.id);}catch(e){this.toast.errorFrom(e,this.t('aiInitiation.error'));}finally{this.working.set(false);}}
}
