'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process'),{decrypt,inside,sha256}=require('./codec.cjs');
const quote=s=>'"'+s.replaceAll('"','""')+'"';
function pg(name,args,env){const binary=env.PG_BIN?path.join(env.PG_BIN,name+(process.platform==='win32'?'.exe':'')):name;const r=spawnSync(binary,args,{env,encoding:'utf8',windowsHide:true,maxBuffer:12*1024*1024});if(r.status!==0)throw Error(name+' failed: '+(r.stderr??r.error?.message??'unknown error'));return r.stdout;}
function counts(database,env){const sql="SELECT json_agg(json_build_object('name',tablename,'schema',schemaname)) FROM pg_tables WHERE schemaname='public'";const tables=JSON.parse(pg('psql',['-X','-At','-d',database,'-c',sql],env));const queries=tables.map(t=>"SELECT '"+t.name.replaceAll("'","''")+"' AS name,count(*) AS n FROM "+quote(t.schema)+'.'+quote(t.name));return JSON.parse(pg('psql',['-X','-At','-d',database,'-c','SELECT json_object_agg(name,n) FROM ('+queries.join(' UNION ALL ')+') AS counted'],env));}
function restore(folder,target,storage,env=process.env){assert(/^(?:localhost|127\.0\.0\.1|::1)$/.test(env.PGHOST??''),'Set a loopback PGHOST; this tool never restores remotely');assert(!env.PGHOSTADDR&&!env.PGSERVICE&&!env.PGSERVICEFILE,'Unset PGHOSTADDR, PGSERVICE and PGSERVICEFILE; indirect connection overrides are not supported');assert(/^dgop_restore_[a-z0-9_]{1,45}$/.test(target),'Choose a fresh dgop_restore_* database name');assert(env.DGOP_SNAPSHOT_KEY_FILE,'Set DGOP_SNAPSHOT_KEY_FILE to the separately shared private key');const keyDoc=JSON.parse(fs.readFileSync(env.DGOP_SNAPSHOT_KEY_FILE,'utf8')),key=Buffer.from(keyDoc.keyBase64,'base64');assert.equal(key.length,32);const manifest=JSON.parse(fs.readFileSync(path.join(folder,'manifest.json'),'utf8'));assert.equal(manifest.format,'dgop-encrypted-postgres-v1');const artifacts={};for(const kind of ['database','files']){const info=manifest.artifacts[kind],file=inside(folder,info.file);assert(fs.statSync(file).size<128*1024*1024,'Snapshot exceeds bounded restore size');const sealed=fs.readFileSync(file);assert.equal(sha256(sealed),info.sha256,'Encrypted artifact checksum differs');const plain=decrypt(sealed,key,manifest.snapshot+':'+kind);assert.equal(sha256(plain),info.plainSha256,'Decrypted artifact checksum differs');artifacts[kind]=plain;}
const files=JSON.parse(artifacts.files),targets=new Set();for(const file of files){const destination=inside(storage,file.path);assert(!targets.has(destination),'Duplicate archive file');targets.add(destination);assert.equal(sha256(Buffer.from(file.base64,'base64')),file.sha256);}assert(!fs.existsSync(storage),'Use a new storage destination; existing files are never overwritten');
const exists=pg('psql',['-X','-At','-d','postgres','-c',"SELECT 1 FROM pg_database WHERE datname='"+target+"'"],env).trim();assert(!exists,'Target database already exists; nothing was overwritten');const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'dgop-restore-'));fs.chmodSync(temporary,0o700);const dump=path.join(temporary,'database.dump');fs.writeFileSync(dump,artifacts.database,{mode:0o600});
try{pg('createdb',['--template=template0',target],env);pg('pg_restore',['--exit-on-error','--no-owner','--no-privileges','--dbname='+target,dump],env);const actual=counts(target,env);assert.deepEqual(actual,manifest.tableCounts,'Restored table counts differ');fs.mkdirSync(storage,{recursive:false});for(const file of files){const destination=inside(storage,file.path);fs.mkdirSync(path.dirname(destination),{recursive:true});fs.writeFileSync(destination,Buffer.from(file.base64,'base64'),{flag:'wx',mode:0o600});assert.equal(sha256(fs.readFileSync(destination)),file.sha256);}return{database:target,tables:Object.keys(actual).length,rows:Object.values(actual).reduce((a,b)=>a+b,0),files:files.length,checksumsVerified:true,missingSourceFiles:manifest.missingSourceFiles.length};}finally{fs.unlinkSync(dump);fs.rmdirSync(temporary);}}
module.exports={pg,counts,restore};
if(require.main===module){try{const [folder,target,storage]=process.argv.slice(2);assert(folder&&target&&storage,'Usage: node restore.cjs SNAPSHOT_DIRECTORY dgop_restore_NAME NEW_STORAGE_DIRECTORY');console.log(JSON.stringify(restore(path.resolve(folder),target,path.resolve(storage))));}catch(e){console.error(e.message);process.exitCode=1;}}
