import { TestBed } from '@angular/core/testing';
import { signal } from '@angular/core';
import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController,provideHttpClientTesting } from '@angular/common/http/testing';
import { AiLifecyclePanel } from './ai-lifecycle-panel';
import { I18nService } from '../core/i18n.service';
import { ToastService } from './toast.service';
describe('registered AI lifecycle panel',()=>{
 let http:HttpTestingController;const lang=signal('en');const page={data:[],total:0,page:1,totalPages:1,useCaseVersion:7,state:'active',canPropose:false,effectiveUseAllowed:true,effective:{payload:{objective_value:'Approved objective'},tierCode:'LIMITED'}};
 beforeEach(()=>{lang.set('en');TestBed.configureTestingModule({imports:[AiLifecyclePanel],providers:[provideHttpClient(),provideHttpClientTesting(),{provide:I18nService,useValue:{lang,t:(key:string)=>key}},{provide:ToastService,useValue:{errorFrom:()=>undefined}}]});http=TestBed.inject(HttpTestingController);});afterEach(()=>http.verify());
 function fixture(){const f=TestBed.createComponent(AiLifecyclePanel);f.componentRef.setInput('useCaseId','case-a');f.detectChanges();return f;}
 it('loads lifecycle work only when opened',async()=>{const f=fixture();http.expectNone('/api/ai/lifecycle/use-cases/case-a?page=1&pageSize=25');const d=f.nativeElement.querySelector('details');d.open=true;d.dispatchEvent(new Event('toggle'));http.expectOne('/api/ai/lifecycle/use-cases/case-a?page=1&pageSize=25').flush(page);await f.whenStable();});
 it('ignores responses for a previous selected case',async()=>{const f=fixture(),c=f.componentInstance as any;c.opened=true;const first=c.load();const old=http.expectOne('/api/ai/lifecycle/use-cases/case-a?page=1&pageSize=25');f.componentRef.setInput('useCaseId','case-b');f.detectChanges();http.expectOne('/api/ai/lifecycle/use-cases/case-b?page=1&pageSize=25').flush({...page,total:4});old.flush({...page,total:99});await first;await f.whenStable();expect(c.context().total).toBe(4);});
 it('keeps platform and auditor oversight read-only',async()=>{const f=fixture(),c=f.componentInstance as any;const done=c.load();http.expectOne('/api/ai/lifecycle/use-cases/case-a?page=1&pageSize=25').flush(page);await done;f.detectChanges();expect(f.nativeElement.querySelector('.proposal')).toBeNull();expect(f.nativeElement.textContent).toContain('Approved use may continue');});
 it('posts only proposed changes with the server version and preserves the effective settings',async()=>{const f=fixture(),c=f.componentInstance as any;c.context.set({...page,canPropose:true});c.draft={objective_value:'Proposed objective'};c.reason='Independent review required';c.assignments={AI_WORKING_GROUP:'working-a'};const done=c.propose(),request=http.expectOne('/api/ai/lifecycle/use-cases/case-a/propose');expect(request.request.body).toEqual({expectedVersion:7,action:'change',justification:'Independent review required',assignments:{AI_WORKING_GROUP:'working-a'},changes:{objective_value:'Proposed objective'}});expect(c.context().effective.payload.objective_value).toBe('Approved objective');request.flush({message:'Conflict'},{status:409,statusText:'Conflict'});await done;expect(c.draft.objective_value).toBe('Proposed objective');expect(c.busy()).toBe(false);});
 it('paginates scoped history through the server',async()=>{const f=fixture(),c=f.componentInstance as any;const done=c.load(5);http.expectOne('/api/ai/lifecycle/use-cases/case-a?page=5&pageSize=25').flush({...page,page:5,total:101,totalPages:5});await done;expect(c.context().total).toBe(101);expect(c.context().page).toBe(5);});
 it('retains Arabic controls and a clear operating hold',async()=>{lang.set('ar');const f=fixture(),c=f.componentInstance as any;const done=c.load();http.expectOne('/api/ai/lifecycle/use-cases/case-a?page=1&pageSize=25').flush({...page,state:'suspended',effectiveUseAllowed:false});await done;f.detectChanges();expect(f.nativeElement.textContent).toContain('الاستخدام التشغيلي معلق');expect(f.nativeElement.textContent).toContain('دورة حياة حالة الاستخدام المسجلة');});
 it('keeps a named assignment visible when its colleague is on an earlier server page',async()=>{const f=fixture(),c=f.componentInstance as any;let done=c.loadNominees(1);http.expectOne('/api/ai/lifecycle/use-cases/case-a/nominees?page=1&pageSize=25&search=').flush({roles:['AI_WORKING_GROUP'],data:[{id:'assigned',nameEn:'Assigned colleague',nameAr:'زميل مكلف',roles:['AI_WORKING_GROUP']}],page:1,totalPages:5});await done;c.assignments.AI_WORKING_GROUP='assigned';done=c.loadNominees(5);http.expectOne('/api/ai/lifecycle/use-cases/case-a/nominees?page=5&pageSize=25&search=').flush({roles:['AI_WORKING_GROUP'],data:[{id:'other',nameEn:'Other colleague',nameAr:'زميل آخر',roles:['AI_WORKING_GROUP']}],page:5,totalPages:5});await done;expect(c.roleUsers('AI_WORKING_GROUP').map((u:any)=>u.id)).toEqual(['other','assigned']);});
 it('uses the multiple-select contract for strategic streams and retains the array value',async()=>{const f=fixture(),c=f.componentInstance as any;f.componentRef.setInput('catalogs',{L_STREAMS:{values:[{code:'one',labelEn:'One',labelAr:'واحد'},{code:'two',labelEn:'Two',labelAr:'اثنان'}]}});c.context.set({...page,canPropose:true,effective:{...page.effective,payload:{strategic_streams:['one']}}});c.draft={strategic_streams:['one']};f.detectChanges();await f.whenStable();const select=f.nativeElement.querySelector('select[multiple]') as HTMLSelectElement;expect(select.options[0].selected).toBe(true);select.options[1].selected=true;select.dispatchEvent(new Event('change'));expect(c.draft.strategic_streams).toEqual(['one','two']);});
});
