import { ChangeDetectionStrategy,Component,effect,inject,input,output,signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import { I18nService } from '../core/i18n.service';
import { ToastService } from './toast.service';
import { AiEvidencePanel } from './ai-evidence-panel';
interface Task {id:string;title:string;status:string;assigneeUserId:string;assigneeRoleCode:string;canAct:boolean;formDataJson:{kind:string;dimension?:string;riskId?:string;configuration?:any};}
interface RequestRow {id:string;action:string;status:string;version:number;justification:string;proposerId:string;canWithdraw:boolean;proposedPayload:Record<string,any>;tasks:Task[];decisions:Array<{id:string;stage:string;actorRole:string;justification:string;decision:string}>;}
interface Context {data:RequestRow[];page:number;total:number;totalPages:number;useCaseVersion:number;state:string;canPropose:boolean;effectiveUseAllowed:boolean;effective:{payload:Record<string,any>;tierCode:string};}
const references:Record<string,string>={strategic_streams:'L_STREAMS',program_platform:'L_PROGRAMS',human_role:'L_HUMAN',target_stage:'L_STAGE',execution_model:'L_MODEL',data_availability:'L_AVAIL',personal_data_flag:'L_YN',data_classification:'L_CLASS',budget_band:'L_BUDGET'};
const criteria=['individual_impact','affected_scope','harm_likelihood','decision_autonomy','data_fairness_transparency','technical_resilience'];
@Component({selector:'app-ai-lifecycle-panel',standalone:true,imports:[FormsModule,AiEvidencePanel],changeDetection:ChangeDetectionStrategy.OnPush,
 template:`<details class="lifecycle" (toggle)="toggle($event)"><summary>{{label('Registered use-case lifecycle','دورة حياة حالة الاستخدام المسجلة')}}</summary>
 <p>{{label('Proposed settings stay held until independent approval and separate Data Owner confirmation. Retirement preserves history.','تبقى الإعدادات المقترحة معلقة حتى الاعتماد المستقل والتأكيد المنفصل من مالك البيانات. يحفظ التقاعد السجل التاريخي.')}}</p>
 @if(context();as c){<p role="status"><strong>{{status(c.state)}}</strong> · {{c.effectiveUseAllowed?label('Approved use may continue','يمكن استمرار الاستخدام المعتمد'):label('Operational use is held','الاستخدام التشغيلي معلق')}} · {{label('Effective tier','الفئة السارية')}}: {{c.effective.tierCode}}</p>
 @if(c.canPropose){<section class="proposal"><h3>{{label('Propose a lifecycle action','اقتراح إجراء لدورة الحياة')}}</h3>
 <label>{{label('Action','الإجراء')}}<select [(ngModel)]="action"><option value="change">{{status('change')}}</option>@if(c.state==='active'){<option value="suspend">{{status('suspend')}}</option>}@if(c.state==='suspended'){<option value="resume">{{status('resume')}}</option>}<option value="retire">{{status('retire')}}</option></select></label>
 @if(action==='change'){<p>{{label('Ownership changes use the separate handover workflow. Asset classification must already protect the proposed data.','تتم تغييرات الملكية عبر مسار التسليم المنفصل. يجب أن يحمي تصنيف الأصل البيانات المقترحة مسبقاً.')}}</p><div class="field-grid">
 @for(field of fields();track field){<label>{{fieldLabel(field)}}<small>{{label('Effective','الساري')}}: {{display(c.effective.payload[field])}}</small>
 @if(options(field).length){@if(field==='strategic_streams'){<select multiple [ngModel]="draft[field]" (ngModelChange)="draft[field]=$event">@for(option of options(field);track option.code){<option [value]="option.code">{{label(option.labelEn,option.labelAr)}}</option>}</select>}@else{<select [ngModel]="draft[field]" (ngModelChange)="draft[field]=$event">@for(option of options(field);track option.code){<option [value]="option.code">{{label(option.labelEn,option.labelAr)}}</option>}</select>}}
 @else if(field==='executive_sponsor'){<select [(ngModel)]="draft[field]">@for(user of directory();track user.id){<option [value]="user.id">{{label(user.nameEn,user.nameAr)}}</option>}</select>}
 @else if(field==='attachments'){<textarea rows="2" [ngModel]="display(draft[field])" (ngModelChange)="draft[field]=split($event)"></textarea>}
 @else if(objectField(field)){<label><input type="checkbox" [ngModel]="objectAnswer(field)" (ngModelChange)="setObjectAnswer(field,$event)"/>{{label('Yes / none where indicated','نعم / لا يوجد حيث يُشار لذلك')}}</label><textarea rows="2" [ngModel]="objectText(field)" (ngModelChange)="setObjectText(field,$event)" maxlength="5000"></textarea>}
 @else {<textarea rows="2" [(ngModel)]="draft[field]" maxlength="5000"></textarea>}
 </label>}
 </div>}
 <fieldset><legend>{{label('Named business assignments','التكليفات التجارية المحددة')}}</legend><label>{{label('Search colleagues','البحث عن الزملاء')}}<input [(ngModel)]="nomineeSearch" maxlength="200"/></label><button type="button" class="ds-btn" [disabled]="busy()" (click)="loadNominees(1)">{{label('Find colleagues','البحث عن الزملاء')}}</button><div class="field-grid">@for(role of nominations()?.roles||[];track role){<label>{{roleLabel(role)}}<select [(ngModel)]="assignments[role]"><option value="">{{label('Choose an eligible colleague','اختر زميلاً مؤهلاً')}}</option>@for(user of roleUsers(role);track user.id){<option [value]="user.id">{{label(user.nameEn,user.nameAr)}}</option>}</select></label>}</div><div class="pager"><button type="button" class="ds-btn" [disabled]="busy()||nomineePage()<=1" (click)="loadNominees(nomineePage()-1)">{{label('Previous colleagues','الزملاء السابقون')}}</button><span>{{nomineePage()}} / {{nomineeTotalPages()}}</span><button type="button" class="ds-btn" [disabled]="busy()||nomineePage()>=nomineeTotalPages()" (click)="loadNominees(nomineePage()+1)">{{label('More colleagues','المزيد من الزملاء')}}</button></div></fieldset>
 <label>{{label('Reason for the action','مبرر الإجراء')}}<textarea rows="3" [(ngModel)]="reason" maxlength="5000"></textarea></label><button type="button" class="ds-btn ds-btn--primary" [disabled]="busy()||!reason.trim()" (click)="propose()">{{label('Submit proposed action','تقديم الإجراء المقترح')}}</button></section>}
 <div class="history"><h3>{{label('Lifecycle history and assigned work','سجل دورة الحياة والعمل المكلف')}}</h3>@for(r of c.data;track r.id){<article><h4>{{status(r.action)}} · {{status(r.status)}}</h4><p>{{r.justification}}</p>
 @if(r.action==='change'){<dl>@for(field of changedFields(r);track field){<dt>{{fieldLabel(field)}}</dt><dd>{{label('Proposed, held','مقترح، معلق')}}: {{display(r.proposedPayload[field])}}</dd>}</dl>}
 <app-ai-evidence-panel targetType="ai_lifecycle_request" [targetId]="r.id" />
 @for(d of r.decisions;track d.id){<p>{{kindLabel(d.stage)}} · {{roleLabel(d.actorRole)}} · {{status(d.decision)}}: {{d.justification}}</p>}
 @for(t of r.tasks;track t.id){@if(t.canAct){<section class="task"><h4>{{kindLabel(t.formDataJson.kind)}}@if(t.formDataJson.dimension){ · {{dimensionLabel(t.formDataJson.dimension!)}}}</h4><p>{{roleLabel(t.assigneeRoleCode)}}</p>
 @if(t.formDataJson.kind==='classification'){@for(criterion of criteria;track criterion;let i=$index){<label>{{criterionLabel(criterion)}}<select [(ngModel)]="form(t.id).scores[i]"><option [ngValue]="1">1</option><option [ngValue]="2">2</option><option [ngValue]="3">3</option><option [ngValue]="4">4</option><option [ngValue]="5">5</option></select><textarea rows="2" [(ngModel)]="form(t.id).reasons[i]" maxlength="2000" [attr.aria-label]="criterionLabel(criterion)+' '+label('justification','المبرر')"></textarea></label>}}
 @else if(assessment(t)){<label>{{label('Fresh score (1–4)','الدرجة الجديدة (١–٤)')}}<select [(ngModel)]="form(t.id).score"><option [ngValue]="1">1</option><option [ngValue]="2">2</option><option [ngValue]="3">3</option><option [ngValue]="4">4</option></select></label>}
 @else {<label>{{label('Decision','القرار')}}<select [(ngModel)]="form(t.id).decision"><option value="approve">{{status('approve')}}</option><option value="return">{{status('return')}}</option><option value="reject">{{status('reject')}}</option></select></label><label>{{label('Linked approved evidence identifiers','معرفات الأدلة المعتمدة المرتبطة')}}<textarea rows="2" [(ngModel)]="form(t.id).evidence" maxlength="800"></textarea></label>@if(t.formDataJson.kind==='authority'){<label>{{label('Additional approval obligations, one per line','التزامات اعتماد إضافية، التزام في كل سطر')}}<textarea rows="2" [(ngModel)]="form(t.id).conditions" maxlength="10000"></textarea></label>}}
 <label>{{label('Written justification','المبرر المكتوب')}}<textarea rows="2" [(ngModel)]="form(t.id).reason" maxlength="5000"></textarea></label><button type="button" class="ds-btn ds-btn--primary" [disabled]="busy()||!form(t.id).reason.trim()" (click)="submitTask(r,t)">{{assessment(t)?label('Record reassessment','تسجيل إعادة التقييم'):label('Record independent decision','تسجيل القرار المستقل')}}</button></section>}}
 @if(r.canWithdraw){<label>{{label('Withdrawal reason (only proposer or current owner)','مبرر السحب (للمقترح أو المالك الحالي فقط)')}}<textarea rows="2" [(ngModel)]="withdrawal[r.id]" maxlength="5000"></textarea></label><button type="button" class="ds-btn" [disabled]="busy()||!withdrawal[r.id]?.trim()" (click)="withdraw(r)">{{label('Withdraw pending action','سحب الإجراء المعلق')}}</button>}
 </article>}
 <div class="pager"><button class="ds-btn" type="button" [disabled]="busy()||c.page<=1" (click)="load(c.page-1)">{{label('Previous','السابق')}}</button><span>{{c.page}} / {{c.totalPages}} · {{c.total}}</span><button class="ds-btn" type="button" [disabled]="busy()||c.page>=c.totalPages" (click)="load(c.page+1)">{{label('Next','التالي')}}</button></div></div>}
 @if(error()){<p role="alert">{{error()}}</p>}<button type="button" class="ds-btn" [disabled]="busy()" (click)="load()">{{label('Refresh lifecycle','تحديث دورة الحياة')}}</button></details>`,
 styles:[`:host{display:block;min-inline-size:0}.lifecycle{border:1px solid var(--border-color,#68788a);border-radius:.8rem;padding:1rem;overflow-wrap:anywhere;margin-block:1rem}summary{font-weight:700;cursor:pointer}label{display:block;margin-block:.6rem}label small{display:block;opacity:.8}textarea,select{inline-size:100%;max-inline-size:100%;box-sizing:border-box;color:inherit;background:var(--surface-card,transparent);border:1px solid var(--border-color,#68788a);border-radius:.4rem;padding:.5rem}input[type=checkbox]{inline-size:auto}.field-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,16rem),1fr));gap:1rem;min-inline-size:0}fieldset,article,.task{min-inline-size:0;border:1px solid var(--border-color,#68788a);border-radius:.5rem;padding:.8rem;margin-block:1rem}fieldset{margin-inline:0}dl{display:grid;grid-template-columns:minmax(0,1fr);gap:.3rem}dd{margin-inline:0;margin-block-end:.5rem}.pager{display:flex;gap:.6rem;flex-wrap:wrap;align-items:center}`]})
export class AiLifecyclePanel {
 readonly useCaseId=input.required<string>();readonly catalogs=input<Record<string,{values:Array<{code:string;labelEn:string;labelAr:string}>}>|null>(null);readonly directory=input<Array<{id:string;nameEn:string;nameAr:string}>>([]);readonly changed=output<void>();
 private http=inject(HttpClient);private i18n=inject(I18nService);private toast=inject(ToastService);protected context=signal<Context|null>(null);protected busy=signal(false);protected error=signal('');protected nominations=signal<{roles:string[];users:Array<{id:string;nameEn:string;nameAr:string;roles:string[]}>}|null>(null);
 protected action='change';protected reason='';protected assignments:Record<string,string>={};protected draft:Record<string,any>={};protected withdrawal:Record<string,string>={};protected criteria=criteria;private forms:Record<string,any>={};private generation=0;private opened=false;protected nomineeSearch='';protected nomineePage=signal(1);protected nomineeTotalPages=signal(1);private nomineeGeneration=0;private nomineeCache=new Map<string,{id:string;nameEn:string;nameAr:string;roles:string[]}>();
 constructor(){effect(()=>{this.useCaseId();++this.generation;++this.nomineeGeneration;this.context.set(null);this.nominations.set(null);this.nomineeCache.clear();this.forms={};this.assignments={};this.reason='';this.busy.set(false);if(this.opened)void this.load();});}
 protected label(en:string,ar:string){return this.i18n.lang()==='ar'?ar:en;}
 protected status(s:string){const map:Record<string,[string,string]>={active:['Active','نشط'],suspended:['Suspended','معلق'],retired:['Retired','متقاعد'],change:['Change settings','تغيير الإعدادات'],suspend:['Suspend use','تعليق الاستخدام'],resume:['Resume use','استئناف الاستخدام'],retire:['Retire use case','تقاعد حالة الاستخدام'],assessment:['Reassessment pending','إعادة التقييم معلقة'],review:['Verification and specialist review','التحقق والمراجعة المتخصصة'],authority:['Tier authority pending','اعتماد السلطة المختصة معلق'],confirmation:['Data Owner confirmation pending','تأكيد مالك البيانات معلق'],applied:['Effective','ساري'],returned:['Returned, history preserved','معاد مع حفظ السجل'],rejected:['Rejected','مرفوض'],withdrawn:['Withdrawn','مسحوب'],approve:['Approve','اعتماد'],return:['Return for a new proposal','إعادة لتقديم مقترح جديد'],reject:['Reject','رفض']};return map[s]?this.label(...map[s]):s;}
 protected kindLabel(s:string){const names:Record<string,[string,string]>={classification:['Six-criterion classification','التصنيف وفق المعايير الستة'],dimension:['Risk impact reassessment','إعادة تقييم أثر الخطر'],likelihood:['Risk likelihood reassessment','إعادة تقييم احتمالية الخطر'],verification:['Independent classification verification','التحقق المستقل من التصنيف'],privacy:['Privacy review','مراجعة الخصوصية'],security:['Security review','مراجعة الأمن'],ethics:['Ethics review','مراجعة الأخلاقيات'],authority:['Tier authority decision','قرار السلطة المختصة بالفئة'],confirmation:['Separate Data Owner confirmation','التأكيد المنفصل من مالك البيانات']};return names[s]?this.label(...names[s]):s;}
 protected roleLabel(role:string){const map:Record<string,[string,string]>={AI_WORKING_GROUP:['AI Working Group','مجموعة عمل الذكاء الاصطناعي'],AI_GOVERNANCE_OFFICER:['AI Governance Officer','مسؤول حوكمة الذكاء الاصطناعي'],AI_EXECUTIVE_TEAM:['AI Executive Team','الفريق التنفيذي للذكاء الاصطناعي'],STEERING_COMMITTEE:['Steering Committee','اللجنة التوجيهية'],AI_ETHICS_COMMITTEE:['Ethics Committee','لجنة الأخلاقيات'],privacy_officer:['Privacy Officer','مسؤول الخصوصية'],security_reviewer:['Security Reviewer','مراجع الأمن'],AI_MODEL_OWNER:['Model Owner','مالك النموذج'],AI_MLOPS_LEAD:['Model Operations','عمليات النماذج'],business_steward:['Business Steward','مشرف الأعمال'],AI_RISK_OWNER:['Risk Owner','مالك الخطر'],AI_USECASE_OWNER:['Use-case Owner','مالك حالة الاستخدام'],data_owner:['Data Owner','مالك البيانات']};return map[role]?this.label(...map[role]):role;}
 protected fieldLabel(field:string){return this.i18n.t('aiuc.field.'+field);}protected criterionLabel(c:string){return this.i18n.t('aiReview.criterion.'+c);}protected dimensionLabel(d:string){return this.i18n.t('aiAssessment.dimension.'+d);}
 protected fields(){return Object.keys(this.context()?.effective.payload??{}).filter(k=>!['requester','request_date','proposed_owner','data_owner'].includes(k));}
 protected options(field:string){return this.catalogs()?.[references[field]]?.values??[];}protected roleUsers(role:string){const current=this.nominations()?.users??[],selected=this.nomineeCache.get(this.assignments[role]);return [...current,...(selected&&!current.some(u=>u.id===selected.id)?[selected]:[])].filter(u=>u.roles.includes(role));}
 protected objectField(field:string){return ['simpler_alternatives','existing_solutions_check','constraints_dependencies'].includes(field);}protected objectAnswer(field:string){return !!this.draft[field]?.[field==='constraints_dependencies'?'none':'answer'];}protected objectText(field:string){return this.draft[field]?.[field==='constraints_dependencies'?'text':field==='simpler_alternatives'?'justification':'details']??'';}
 protected setObjectAnswer(field:string,value:boolean){this.draft[field]={...this.draft[field],[field==='constraints_dependencies'?'none':'answer']:value};}protected setObjectText(field:string,value:string){this.draft[field]={...this.draft[field],[field==='constraints_dependencies'?'text':field==='simpler_alternatives'?'justification':'details']:value};}
 protected display(value:any):string{return Array.isArray(value)?value.join(', '):typeof value==='object'&&value?Object.values(value).join(' · '):String(value??'');}protected split(value:string){return value.split(/[\s,;]+/u).filter(Boolean);}
 protected changedFields(r:RequestRow){return Object.keys(r.proposedPayload).filter(k=>JSON.stringify(r.proposedPayload[k])!==JSON.stringify(this.context()?.effective.payload[k]));}
 protected form(id:string){return this.forms[id]??= {reason:'',evidence:'',conditions:'',decision:'approve',score:1,scores:[1,1,1,1,1,1],reasons:['','','','','','']};}protected assessment(t:Task){return ['classification','dimension','likelihood'].includes(t.formDataJson.kind);}
 protected toggle(e:Event){this.opened=(e.target as HTMLDetailsElement).open;if(this.opened&&!this.context())void this.load();}
 protected async load(page=1){const generation=++this.generation;this.busy.set(true);this.error.set('');try{const c=await firstValueFrom(this.http.get<Context>('/api/ai/lifecycle/use-cases/'+this.useCaseId()+'?page='+page+'&pageSize=25'));if(generation!==this.generation)return;this.context.set(c);this.draft=structuredClone(c.effective.payload);if(this.action==='resume'&&c.state!=='suspended'||this.action==='suspend'&&c.state!=='active')this.action='change';if(c.canPropose)await this.loadNominees(1);}catch(e){if(generation===this.generation){this.error.set(this.label('Could not load lifecycle work. Refresh to retry.','تعذر تحميل عمل دورة الحياة. حدّث لإعادة المحاولة.'));this.toast.errorFrom(e,this.error());}}finally{if(generation===this.generation)this.busy.set(false);}}
 protected async loadNominees(page=1){const generation=++this.nomineeGeneration,id=this.useCaseId();try{const n=await firstValueFrom(this.http.get<any>('/api/ai/lifecycle/use-cases/'+id+'/nominees?page='+page+'&pageSize=25&search='+encodeURIComponent(this.nomineeSearch)));if(generation===this.nomineeGeneration&&id===this.useCaseId()){const selected=new Set(Object.values(this.assignments));for(const key of this.nomineeCache.keys())if(!selected.has(key))this.nomineeCache.delete(key);for(const user of n.data)this.nomineeCache.set(user.id,user);this.nominations.set({roles:n.roles,users:n.data});this.nomineePage.set(n.page);this.nomineeTotalPages.set(n.totalPages);}}catch(e){if(generation===this.nomineeGeneration)this.toast.errorFrom(e,this.label('Could not load scoped nominations','تعذر تحميل المرشحين ضمن النطاق'));}}
 private async post(url:string,body:unknown){if(this.busy())return;const generation=this.generation;this.busy.set(true);try{await firstValueFrom(this.http.post(url,body));if(generation===this.generation){this.forms={};await this.load();this.changed.emit();}}catch(e){if(generation===this.generation)this.toast.errorFrom(e,this.label('Lifecycle action could not be completed','تعذر إكمال إجراء دورة الحياة'));}finally{if(generation===this.generation)this.busy.set(false);}}
 protected async propose(){const c=this.context();if(!c)return;const changes=this.action==='change'?Object.fromEntries(Object.entries(this.draft).filter(([k,v])=>JSON.stringify(v)!==JSON.stringify(c.effective.payload[k]))):undefined;await this.post('/api/ai/lifecycle/use-cases/'+this.useCaseId()+'/propose',{expectedVersion:c.useCaseVersion,action:this.action,justification:this.reason,assignments:this.assignments,...(changes?{changes}:{})});}
 protected async submitTask(r:RequestRow,t:Task){const f=this.form(t.id);await this.post('/api/ai/lifecycle/'+r.id+'/tasks/'+t.id+'/'+(this.assessment(t)?'assess':'decide'),{expectedVersion:r.version,justification:f.reason,...(t.formDataJson.kind==='classification'?{input:{kind:'classification',scores:f.scores.map((value:number,i:number)=>({value,justification:f.reasons[i]}))}}:this.assessment(t)?{score:f.score}:{decision:f.decision,evidenceIds:this.split(f.evidence),...(t.formDataJson.kind==='authority'?{conditions:f.conditions.split('\n').map((s:string)=>s.trim()).filter(Boolean)}:{})})});}
 protected async withdraw(r:RequestRow){await this.post('/api/ai/lifecycle/'+r.id+'/withdraw',{expectedVersion:r.version,justification:this.withdrawal[r.id]});}
}
