// Shared canonical definitions. Installation policy belongs to the caller.
export const roles = [
  { code: 'system_admin', nameEn: 'System Administrator', nameAr: 'مدير النظام' },
  { code: 'dmo_admin', nameEn: 'DMO Admin', nameAr: 'مدير مكتب إدارة البيانات' },
  { code: 'data_owner', nameEn: 'Data Owner', nameAr: 'مالك البيانات' },
  { code: 'business_steward', nameEn: 'Business Steward', nameAr: 'أمين البيانات (الأعمال)' },
  { code: 'technical_steward', nameEn: 'Technical Steward', nameAr: 'أمين البيانات (التقني)' },
  { code: 'operational_data_steward', nameEn: 'Operational Data Steward', nameAr: 'أمين البيانات التشغيلي' },
  { code: 'project_data_steward', nameEn: 'Project Data Steward', nameAr: 'أمين بيانات المشروع' },
  { code: 'enterprise_data_steward', nameEn: 'Enterprise Data Steward', nameAr: 'أمين بيانات المؤسسة' },
  { code: 'dq_steward', nameEn: 'Data Quality Steward', nameAr: 'أمين جودة البيانات' },
  { code: 'privacy_officer', nameEn: 'Privacy Officer', nameAr: 'مسؤول الخصوصية' },
  { code: 'security_reviewer', nameEn: 'Security Reviewer', nameAr: 'مراجع الأمن' },
  { code: 'workflow_designer', nameEn: 'Workflow Designer', nameAr: 'مصمم سير العمل' },
  { code: 'workflow_reviewer', nameEn: 'Workflow Reviewer', nameAr: 'مراجع سير العمل' },
  { code: 'workflow_publisher', nameEn: 'Workflow Publisher', nameAr: 'ناشر سير العمل' },
  { code: 'od_officer', nameEn: 'Open Data Officer', nameAr: 'مسؤول البيانات المفتوحة' },
  { code: 'foi_officer', nameEn: 'FOI Officer', nameAr: 'مسؤول حرية المعلومات' },
  { code: 'ndi_evidence_owner', nameEn: 'NDI Evidence Owner', nameAr: 'مالك أدلة المؤشر الوطني' },
  { code: 'auditor', nameEn: 'Auditor', nameAr: 'مدقق' },
  { code: 'executive', nameEn: 'Executive', nameAr: 'تنفيذي' },
];

// Resources whose screens support full CRUD administration.
const ADMIN_RESOURCES = [
  'users',
  'roles',
  'data_domains',
  'data_subjects',
  'business_capabilities',
  'org_units',
  'systems',
  'classifications',
  'role_types',
  'raci_templates',
  'status_values',
  'data_assets',
  'people',
  'assignments',
  'assignment_rules',
  'workflow_cases',
  'workflow_tasks',
  'ndi_specifications',
  'training_courses',
  'training_requirements',
  'training_assignments',
  'certification_tracks',
  'certification_attempts',
  'ce_activities',
  'community_articles',
  'expert_profiles',
  'mentorship_pairs',
  'data_quality_issues',
  'data_quality_rules',
  'data_quality_profiles',
  'security_governance',
  'masking_policies',
  'role_data_access_maps',
  'access_reviews',
  'dlp_incidents',
  'classification_change_requests',
  'integrations',
  'open_data_candidates',
  'foi_requests',
  'foi_disclosures',
  'foi_appeals',
  'privacy_operations',
  'privacy_legal_bases',
  'privacy_ropa_records',
  'privacy_dpias',
  'privacy_dsr_requests',
  'privacy_breaches',
  'data_sharing_requests',
  'data_sharing_agreements',
  'ndi_audit_packs',
  'extended_domains',
  'business_value',
  'governance_operations',
];
const CRUD_ACTIONS = ['view', 'create', 'edit', 'delete'];

// Canonical permission catalog (resource + action pairs).
export const permissionCatalog: { resource: string; action: string }[] = [
  { resource: 'dashboard', action: 'view' },
  { resource: 'design_system', action: 'view' },
  { resource: 'search', action: 'view' },
  { resource: 'search', action: 'create' },
  { resource: 'search', action: 'analytics' },
  { resource: 'audit', action: 'view' },
  { resource: 'audit', action: 'baseline_accept' },
  // Bulk CSV import is a distinct, higher-privilege action on data assets.
  { resource: 'data_assets', action: 'import' },
  // Bulk CSV import of NDI specifications.
  { resource: 'ndi_specifications', action: 'import' },
  // NDI evidence repository (review instead of edit, so not a standard CRUD resource).
  { resource: 'evidence', action: 'view' },
  { resource: 'evidence', action: 'create' },
  { resource: 'evidence', action: 'review' },
  { resource: 'evidence', action: 'delete' },
  // NDI scoring & gap analysis (read-only readiness views).
  { resource: 'ndi_scoring', action: 'view' },
  // Audit-pack packaging needs explicit generate/download actions.
  { resource: 'ndi_audit_packs', action: 'generate' },
  { resource: 'ndi_audit_packs', action: 'download' },
  // Bulk CSV import of data quality issues.
  { resource: 'data_quality_issues', action: 'import' },
  // Catalog and external tool integration operations.
  { resource: 'integrations', action: 'run' },
  { resource: 'integrations', action: 'writeback' },
  { resource: 'governance_operations', action: 'run' },
  { resource: 'access_grants', action: 'view' },
  { resource: 'access_grants', action: 'create' },
  { resource: 'access_grants', action: 'edit' },
  ...ADMIN_RESOURCES.flatMap((r) => CRUD_ACTIONS.map((a) => ({ resource: r, action: a }))),
];

const BASE_PERMS = ['dashboard.view', 'design_system.view', 'search.view', 'search.create', 'search.analytics'];
const ADMIN_ALL = ADMIN_RESOURCES.flatMap((r) => CRUD_ACTIONS.map((a) => `${r}.${a}`));

// Default role -> permission keys. system_admin receives the full catalog.
export const rolePermissionMap: Record<string, string[]> = {
  dmo_admin: [
    ...BASE_PERMS,
    ...ADMIN_ALL,
    'data_assets.import',
    'ndi_specifications.import',
    'evidence.view',
    'evidence.create',
    'evidence.review',
    'evidence.delete',
    'ndi_scoring.view',
    'ndi_audit_packs.generate',
    'ndi_audit_packs.download',
    'data_quality_issues.import',
    'integrations.run',
    'integrations.writeback',
    'governance_operations.run',
    'access_grants.view',
    'access_grants.create',
    'access_grants.edit',
    'audit.view',
    'audit.baseline_accept',
  ],
  workflow_designer: [
    ...BASE_PERMS,
    'workflow_cases.view',
    'workflow_cases.create',
    'workflow_cases.edit',
    'workflow_tasks.view',
    'workflow_tasks.create',
    'workflow_tasks.edit',
    'data_assets.view',
    'people.view',
    'assignments.view',
    'audit.view',
  ],
  workflow_reviewer: [
    ...BASE_PERMS,
    'workflow_cases.view',
    'workflow_cases.edit',
    'workflow_tasks.view',
    'data_assets.view',
    'people.view',
    'assignments.view',
    'audit.view',
  ],
  workflow_publisher: [
    ...BASE_PERMS,
    'workflow_cases.view',
    'workflow_cases.edit',
    'workflow_tasks.view',
    'data_assets.view',
    'people.view',
    'assignments.view',
    'audit.view',
  ],
  business_steward: [
    ...BASE_PERMS,
    'data_assets.view',
    'assignments.view',
    'workflow_cases.view',
    'workflow_tasks.view',
    'ndi_specifications.view',
    'extended_domains.view',
    'business_value.view',
    'business_value.create',
    'business_value.edit',
    'governance_operations.view',
    'training_courses.view',
    'training_assignments.view',
    'training_assignments.edit',
    'certification_tracks.view',
    'certification_attempts.view',
    'certification_attempts.create',
    'ce_activities.view',
    'ce_activities.create',
    'community_articles.view',
    'expert_profiles.view',
    'mentorship_pairs.view',
  ],
  data_owner: [
    ...BASE_PERMS,
    'data_assets.view',
    'assignments.view',
    'workflow_cases.view',
    'workflow_tasks.view',
    'security_governance.view',
    'access_reviews.view',
    'access_reviews.edit',
    'access_grants.view',
    'access_grants.create',
    'access_grants.edit',
    'open_data_candidates.view',
    'open_data_candidates.create',
    'open_data_candidates.edit',
    'privacy_operations.view',
    'data_sharing_requests.view',
    'data_sharing_requests.edit',
    'extended_domains.view',
    'business_value.view',
    'business_value.create',
    'business_value.edit',
    'governance_operations.view',
    'training_courses.view',
    'training_assignments.view',
    'training_assignments.edit',
    'certification_tracks.view',
    'certification_attempts.view',
    'certification_attempts.create',
    'ce_activities.view',
    'ce_activities.create',
    'community_articles.view',
    'expert_profiles.view',
    'mentorship_pairs.view',
  ],
  technical_steward: [
    ...BASE_PERMS,
    'data_assets.view',
    'assignments.view',
    'workflow_cases.view',
    'workflow_tasks.view',
    'extended_domains.view',
    'extended_domains.create',
    'extended_domains.edit',
    'business_value.view',
    'business_value.create',
    'business_value.edit',
    'governance_operations.view',
    'training_courses.view',
    'training_assignments.view',
    'training_assignments.edit',
    'certification_tracks.view',
    'certification_attempts.view',
    'certification_attempts.create',
    'ce_activities.view',
    'ce_activities.create',
    'community_articles.view',
    'expert_profiles.view',
    'mentorship_pairs.view',
  ],
  operational_data_steward: [
    ...BASE_PERMS,
    'data_assets.view',
    'assignments.view',
    'workflow_cases.view',
    'workflow_tasks.view',
    'extended_domains.view',
    'business_value.view',
    'business_value.create',
    'governance_operations.view',
    'training_courses.view',
    'training_assignments.view',
    'training_assignments.edit',
    'certification_tracks.view',
    'certification_attempts.view',
    'certification_attempts.create',
    'ce_activities.view',
    'ce_activities.create',
    'community_articles.view',
    'expert_profiles.view',
    'mentorship_pairs.view',
  ],
  project_data_steward: [
    ...BASE_PERMS,
    'data_assets.view',
    'assignments.view',
    'workflow_cases.view',
    'workflow_tasks.view',
    'extended_domains.view',
    'extended_domains.create',
    'extended_domains.edit',
    'business_value.view',
    'business_value.create',
    'business_value.edit',
    'governance_operations.view',
    'training_courses.view',
    'training_assignments.view',
    'training_assignments.edit',
    'certification_tracks.view',
    'certification_attempts.view',
    'certification_attempts.create',
    'ce_activities.view',
    'ce_activities.create',
    'community_articles.view',
    'expert_profiles.view',
    'mentorship_pairs.view',
  ],
  enterprise_data_steward: [
    ...BASE_PERMS,
    'data_assets.view',
    'people.view',
    'assignments.view',
    'workflow_cases.view',
    'workflow_tasks.view',
    'ndi_specifications.view',
    'ndi_scoring.view',
    'ndi_audit_packs.view',
    'extended_domains.view',
    'extended_domains.create',
    'extended_domains.edit',
    'business_value.view',
    'business_value.create',
    'business_value.edit',
    'governance_operations.view',
    'governance_operations.run',
    'security_governance.view',
    'access_reviews.view',
    'open_data_candidates.view',
    'training_courses.view',
    'training_requirements.view',
    'training_assignments.view',
    'training_assignments.edit',
    'certification_tracks.view',
    'certification_attempts.view',
    'certification_attempts.create',
    'ce_activities.view',
    'ce_activities.create',
    'community_articles.view',
    'community_articles.create',
    'expert_profiles.view',
    'expert_profiles.create',
    'mentorship_pairs.view',
    'mentorship_pairs.create',
  ],
  dq_steward: [
    ...BASE_PERMS,
    'data_assets.view',
    'people.view',
    'assignments.view',
    'workflow_cases.view',
    'workflow_cases.create',
    'workflow_cases.edit',
    'workflow_tasks.view',
    'workflow_tasks.create',
    'workflow_tasks.edit',
    'data_quality_issues.view',
    'data_quality_issues.create',
    'data_quality_issues.edit',
    'data_quality_issues.import',
    'data_quality_rules.view',
    'data_quality_rules.create',
    'data_quality_rules.edit',
    'data_quality_profiles.view',
    'data_quality_profiles.create',
    'governance_operations.view',
    'training_assignments.view',
    'training_assignments.edit',
    'certification_tracks.view',
    'certification_attempts.view',
    'certification_attempts.create',
    'ce_activities.view',
    'ce_activities.create',
    'community_articles.view',
    'expert_profiles.view',
    'mentorship_pairs.view',
  ],
  auditor: [
    ...BASE_PERMS,
    'data_assets.view',
    'people.view',
    'assignments.view',
    'assignment_rules.view',
    'workflow_cases.view',
    'workflow_tasks.view',
    'ndi_specifications.view',
    'evidence.view',
    'ndi_scoring.view',
    'ndi_audit_packs.view',
    'ndi_audit_packs.download',
    'extended_domains.view',
    'business_value.view',
    'governance_operations.view',
    'training_courses.view',
    'training_requirements.view',
    'training_assignments.view',
    'certification_tracks.view',
    'certification_attempts.view',
    'ce_activities.view',
    'community_articles.view',
    'expert_profiles.view',
    'mentorship_pairs.view',
    'data_quality_issues.view',
    'data_quality_rules.view',
    'data_quality_profiles.view',
    'security_governance.view',
    'masking_policies.view',
    'role_data_access_maps.view',
    'access_reviews.view',
    'access_grants.view',
    'dlp_incidents.view',
    'classification_change_requests.view',
    'integrations.view',
    'open_data_candidates.view',
    'audit.view',
    'privacy_operations.view',
    'privacy_legal_bases.view',
    'privacy_ropa_records.view',
    'privacy_dpias.view',
    'privacy_dsr_requests.view',
    'privacy_breaches.view',
    'data_sharing_requests.view',
    'data_sharing_agreements.view',
    'governance_operations.view',
  ],
  privacy_officer: [
    ...BASE_PERMS,
    'data_assets.view',
    'people.view',
    'roles.view',
    'classifications.view',
    'security_governance.view',
    'security_governance.create',
    'security_governance.edit',
    'masking_policies.view',
    'masking_policies.create',
    'masking_policies.edit',
    'role_data_access_maps.view',
    'access_reviews.view',
    'access_reviews.edit',
    'access_grants.view',
    'access_grants.edit',
    'dlp_incidents.view',
    'dlp_incidents.create',
    'dlp_incidents.edit',
    'classification_change_requests.view',
    'classification_change_requests.create',
    'classification_change_requests.edit',
    'integrations.view',
    'integrations.run',
    'integrations.writeback',
    'open_data_candidates.view',
    'privacy_operations.view',
    'privacy_operations.create',
    'privacy_operations.edit',
    'privacy_legal_bases.view',
    'privacy_legal_bases.create',
    'privacy_legal_bases.edit',
    'privacy_ropa_records.view',
    'privacy_ropa_records.create',
    'privacy_ropa_records.edit',
    'privacy_dpias.view',
    'privacy_dpias.create',
    'privacy_dpias.edit',
    'privacy_dsr_requests.view',
    'privacy_dsr_requests.create',
    'privacy_dsr_requests.edit',
    'privacy_breaches.view',
    'privacy_breaches.create',
    'privacy_breaches.edit',
    'data_sharing_requests.view',
    'data_sharing_requests.create',
    'data_sharing_requests.edit',
    'data_sharing_agreements.view',
    'governance_operations.view',
    'audit.view',
  ],
  od_officer: [
    ...BASE_PERMS,
    'data_assets.view',
    'people.view',
    'classifications.view',
    'assignments.view',
    'workflow_cases.view',
    'workflow_tasks.view',
    'data_quality_issues.view',
    'data_quality_rules.view',
    'data_quality_profiles.view',
    'security_governance.view',
    'open_data_candidates.view',
    'open_data_candidates.create',
    'open_data_candidates.edit',
    'open_data_candidates.delete',
    'privacy_operations.view',
    'data_sharing_requests.view',
    'data_sharing_agreements.view',
    'governance_operations.view',
    'audit.view',
  ],
  foi_officer: [
    ...BASE_PERMS,
    'data_assets.view',
    'people.view',
    'classifications.view',
    'workflow_cases.view',
    'workflow_tasks.view',
    'governance_operations.view',
    'foi_requests.view',
    'foi_requests.create',
    'foi_requests.edit',
    'foi_disclosures.view',
    'foi_disclosures.create',
    'foi_appeals.view',
    'foi_appeals.create',
    'audit.view',
  ],
  security_reviewer: [
    ...BASE_PERMS,
    'data_assets.view',
    'people.view',
    'users.view',
    'roles.view',
    'classifications.view',
    'security_governance.view',
    'security_governance.create',
    'security_governance.edit',
    'masking_policies.view',
    'role_data_access_maps.view',
    'role_data_access_maps.create',
    'role_data_access_maps.edit',
    'access_reviews.view',
    'access_reviews.create',
    'access_reviews.edit',
    'dlp_incidents.view',
    'dlp_incidents.create',
    'dlp_incidents.edit',
    'classification_change_requests.view',
    'classification_change_requests.edit',
    'privacy_operations.view',
    'privacy_breaches.view',
    'privacy_breaches.edit',
    'data_sharing_requests.view',
    'data_sharing_requests.edit',
    'data_sharing_agreements.view',
    'data_sharing_agreements.edit',
    'governance_operations.view',
    'audit.view',
  ],
  ndi_evidence_owner: [
    ...BASE_PERMS,
    'ndi_specifications.view',
    'evidence.view',
    'evidence.create',
    'ndi_audit_packs.view',
    'governance_operations.view',
    'training_courses.view',
    'training_assignments.view',
    'training_assignments.edit',
    'certification_tracks.view',
    'certification_attempts.view',
    'ce_activities.view',
    'ce_activities.create',
    'community_articles.view',
    'expert_profiles.view',
    'mentorship_pairs.view',
  ],
};

export const classifications = [
  { code: 'public', nameEn: 'Public', nameAr: 'عام', rank: 1, color: '#1a7f4b' },
  { code: 'internal', nameEn: 'Internal', nameAr: 'داخلي', rank: 2, color: '#1f6feb' },
  { code: 'restricted', nameEn: 'Restricted', nameAr: 'مقيّد', rank: 3, color: '#b5790a' },
  { code: 'secret', nameEn: 'Secret', nameAr: 'سري', rank: 4, color: '#c0392b' },
  { code: 'top_secret', nameEn: 'Top Secret', nameAr: 'سري للغاية', rank: 5, color: '#6b1414' },
];

export const roleTypes = [
  { code: 'data_owner', nameEn: 'Data Owner', nameAr: 'مالك البيانات' },
  { code: 'business_steward', nameEn: 'Business Steward', nameAr: 'أمين البيانات (الأعمال)' },
  { code: 'technical_steward', nameEn: 'Technical Steward', nameAr: 'أمين البيانات (التقني)' },
  { code: 'operational_data_steward', nameEn: 'Operational Data Steward', nameAr: 'أمين البيانات التشغيلي' },
  { code: 'project_data_steward', nameEn: 'Project Data Steward', nameAr: 'أمين بيانات المشروع' },
  { code: 'enterprise_data_steward', nameEn: 'Enterprise Data Steward', nameAr: 'أمين بيانات المؤسسة' },
  { code: 'dq_steward', nameEn: 'Data Quality Steward', nameAr: 'أمين جودة البيانات' },
  { code: 'data_custodian', nameEn: 'Data Custodian', nameAr: 'حافظ البيانات' },
];

export const statusValues = [
  { domain: 'workflow', code: 'draft', nameEn: 'Draft', nameAr: 'مسودة', color: '#6b7280', sortOrder: 1 },
  { domain: 'workflow', code: 'submitted', nameEn: 'Submitted', nameAr: 'مُقدَّم', color: '#1f6feb', sortOrder: 2 },
  { domain: 'workflow', code: 'under_review', nameEn: 'Under Review', nameAr: 'قيد المراجعة', color: '#b5790a', sortOrder: 3 },
  { domain: 'workflow', code: 'approved', nameEn: 'Approved', nameAr: 'مُعتمد', color: '#1a7f4b', sortOrder: 4 },
  { domain: 'workflow', code: 'rejected', nameEn: 'Rejected', nameAr: 'مرفوض', color: '#c0392b', sortOrder: 5 },
  { domain: 'compliance', code: 'on_track', nameEn: 'On Track', nameAr: 'على المسار', color: '#1a7f4b', sortOrder: 1 },
  { domain: 'compliance', code: 'at_risk', nameEn: 'At Risk', nameAr: 'معرّض للخطر', color: '#b5790a', sortOrder: 2 },
  { domain: 'compliance', code: 'overdue', nameEn: 'Overdue', nameAr: 'متأخر', color: '#c0392b', sortOrder: 3 },
  // Lifecycle states for governed data assets (Sprint 4).
  { domain: 'lifecycle', code: 'draft', nameEn: 'Draft', nameAr: 'مسودة', color: '#6b7280', sortOrder: 1 },
  { domain: 'lifecycle', code: 'active', nameEn: 'Active', nameAr: 'نشِط', color: '#1a7f4b', sortOrder: 2 },
  { domain: 'lifecycle', code: 'deprecated', nameEn: 'Deprecated', nameAr: 'مُهمَل', color: '#b5790a', sortOrder: 3 },
  { domain: 'lifecycle', code: 'retired', nameEn: 'Retired', nameAr: 'مُتقاعد', color: '#c0392b', sortOrder: 4 },
];

export const ndiDomains = [
  { code: 'data_strategy', shortCode: 'DG', nameEn: 'Data Strategy & Governance', nameAr: 'استراتيجية وحوكمة البيانات', sortOrder: 1 },
  { code: 'data_catalog', shortCode: 'DCM', nameEn: 'Data Catalog & Metadata', nameAr: 'فهرس البيانات والبيانات الوصفية', sortOrder: 2 },
  { code: 'data_quality', shortCode: 'DQ', nameEn: 'Data Quality', nameAr: 'جودة البيانات', sortOrder: 3 },
  { code: 'data_architecture', shortCode: 'DA', nameEn: 'Data Architecture', nameAr: 'بنية البيانات', sortOrder: 4 },
  { code: 'data_security', shortCode: 'DSI', nameEn: 'Data Security & Protection', nameAr: 'أمن وحماية البيانات', sortOrder: 5 },
  { code: 'data_privacy', shortCode: 'PDP', nameEn: 'Personal Data Protection', nameAr: 'حماية البيانات الشخصية', sortOrder: 6 },
  { code: 'data_sharing', shortCode: 'DSh', nameEn: 'Data Sharing & Integration', nameAr: 'مشاركة وتكامل البيانات', sortOrder: 7 },
  { code: 'open_data', shortCode: 'OD', nameEn: 'Open Data', nameAr: 'البيانات المفتوحة', sortOrder: 8 },
  { code: 'freedom_of_information', shortCode: 'FOI', nameEn: 'Freedom of Information', nameAr: 'حرية المعلومات', sortOrder: 9 },
  { code: 'data_classification', shortCode: 'DC', nameEn: 'Data Classification', nameAr: 'تصنيف البيانات', sortOrder: 10 },
  { code: 'reference_master_data', shortCode: 'RMD', nameEn: 'Reference & Master Data', nameAr: 'البيانات المرجعية والرئيسية', sortOrder: 11 },
  { code: 'data_lifecycle', shortCode: 'DLM', nameEn: 'Data Lifecycle & Retention', nameAr: 'دورة حياة البيانات والاحتفاظ', sortOrder: 12 },
];

// Sample NDI specifications (linked to NDI domains by domain code).
export const ndiSpecifications: {
  code: string;
  domainCode: string;
  criterion?: string;
  type: string;
  maturityLevel: string;
  nameEn: string;
  nameAr: string;
  descriptionEn?: string;
  acceptanceCriteria?: string;
  reference?: string;
  sortOrder?: number;
}[] = [
  {
    code: 'DG.1.1',
    domainCode: 'data_strategy',
    criterion: 'Governance Operating Model',
    type: 'policy',
    maturityLevel: 'level_1',
    nameEn: 'Approved data governance policy',
    nameAr: 'سياسة حوكمة بيانات معتمدة',
    descriptionEn: 'An entity-wide data governance policy is documented, approved and published.',
    acceptanceCriteria: 'Signed policy document exists and is communicated to staff.',
    reference: 'NDI DG-01',
    sortOrder: 1,
  },
  {
    code: 'DG.1.2',
    domainCode: 'data_strategy',
    criterion: 'Roles & Responsibilities',
    type: 'standard',
    maturityLevel: 'level_2',
    nameEn: 'Defined data ownership and stewardship roles',
    nameAr: 'تعريف أدوار ملكية وأمانة البيانات',
    descriptionEn: 'Data owners and stewards are assigned for governed data assets.',
    acceptanceCriteria: 'Ownership registry lists an approved data owner for each critical asset.',
    reference: 'NDI DG-04',
    sortOrder: 2,
  },
  {
    code: 'CAT.1.1',
    domainCode: 'data_catalog',
    criterion: 'Metadata Management',
    type: 'standard',
    maturityLevel: 'level_2',
    nameEn: 'Maintained data catalog with business metadata',
    nameAr: 'فهرس بيانات محدّث يحتوي البيانات الوصفية',
    descriptionEn: 'Governed data assets are registered with descriptive business metadata.',
    acceptanceCriteria: 'Catalog coverage of critical assets is at least 80%.',
    reference: 'NDI MD-02',
    sortOrder: 1,
  },
  {
    code: 'DQ.1.1',
    domainCode: 'data_quality',
    criterion: 'Quality Controls',
    type: 'control',
    maturityLevel: 'level_2',
    nameEn: 'Data quality rules for critical data elements',
    nameAr: 'قواعد جودة البيانات للعناصر الحرجة',
    descriptionEn: 'Quality rules (completeness, validity) are defined and monitored.',
    acceptanceCriteria: 'Quality rules exist and results are reported periodically.',
    reference: 'NDI DQ-03',
    sortOrder: 1,
  },
  {
    code: 'DQ.2.1',
    domainCode: 'data_quality',
    criterion: 'Issue Remediation',
    type: 'procedure',
    maturityLevel: 'level_3',
    nameEn: 'Data quality issue remediation workflow',
    nameAr: 'سير عمل معالجة مشكلات جودة البيانات',
    descriptionEn: 'Identified quality issues are tracked and remediated through a workflow.',
    acceptanceCriteria: 'Open issues are triaged with owners and target dates.',
    reference: 'NDI DQ-07',
    sortOrder: 2,
  },
  {
    code: 'DSI.1.1',
    domainCode: 'data_sharing',
    criterion: 'Sharing Agreements',
    type: 'standard',
    maturityLevel: 'level_2',
    nameEn: 'Documented data sharing agreements',
    nameAr: 'اتفاقيات مشاركة بيانات موثقة',
    descriptionEn: 'Inter-entity data sharing is governed by approved agreements.',
    acceptanceCriteria: 'Each external data exchange has a signed agreement on file.',
    reference: 'NDI DS-02',
    sortOrder: 1,
  },
  {
    code: 'PDP.1.1',
    domainCode: 'data_privacy',
    criterion: 'Personal Data Inventory',
    type: 'control',
    maturityLevel: 'level_2',
    nameEn: 'Inventory of personal data processing',
    nameAr: 'سجل معالجة البيانات الشخصية',
    descriptionEn: 'Personal data processing activities are inventoried and classified.',
    acceptanceCriteria: 'Records of processing are maintained and reviewed annually.',
    reference: 'NDI PDP-01',
    sortOrder: 1,
  },
  {
    code: 'OD.1.1',
    domainCode: 'open_data',
    criterion: 'Open Data Publishing',
    type: 'guideline',
    maturityLevel: 'level_1',
    nameEn: 'Open data publishing guideline',
    nameAr: 'إرشادات نشر البيانات المفتوحة',
    descriptionEn: 'Eligible datasets are published as open data using approved formats.',
    acceptanceCriteria: 'At least one dataset is published in a machine-readable format.',
    reference: 'NDI OD-01',
    sortOrder: 1,
  },
  {
    code: 'FOI.1.1',
    domainCode: 'freedom_of_information',
    criterion: 'Information Requests',
    type: 'procedure',
    maturityLevel: 'level_1',
    nameEn: 'Freedom of information request handling',
    nameAr: 'إجراء معالجة طلبات حرية المعلومات',
    descriptionEn: 'A documented procedure handles information access requests within SLA.',
    acceptanceCriteria: 'Requests are logged and answered within the mandated period.',
    reference: 'NDI FOI-02',
    sortOrder: 1,
  },
  {
    code: 'CLS.1.1',
    domainCode: 'data_classification',
    criterion: 'Classification Scheme',
    type: 'standard',
    maturityLevel: 'level_2',
    nameEn: 'Applied data classification scheme',
    nameAr: 'تطبيق مخطط تصنيف البيانات',
    descriptionEn: 'Data assets are classified using the approved sensitivity scheme.',
    acceptanceCriteria: 'Critical assets carry a classification label.',
    reference: 'NDI CL-01',
    sortOrder: 1,
  },
];
