import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { ScopeService } from '../access/scope.service';
import { AiRiskIntakeService } from './ai-risk-intake.service';
import { AI_RISK_REPORT_SELECT, projectRisk } from './ai-dashboard.service';
import { jsonRecord } from './ai-risk-scoring';
import { aiReviewStatus } from './ai-risk-review.service';
import { isSystemAdministrator } from '../auth/system-admin';
@Injectable()
export class AiAssetRiskService {
 constructor(private readonly prisma:PrismaService,private readonly risks:AiRiskIntakeService,private readonly scope:ScopeService){}
 private page(page:number,size:number){if(!Number.isInteger(page)||page<1||!Number.isInteger(size)||size<1||size>100)throw new BadRequestException('Use page >=1 and page size 1–100');}
 private async access(tx:Prisma.TransactionClient,userId:string,assetId:string){
  const a=await this.risks.visibility(userId,tx),scope=await this.scope.resolve(a.actor.roles);
  const nativeGrant=isSystemAdministrator(a.actor.roles)||!!await tx.rolePermission.count({where:{role:{is:{code:{in:a.actor.roles},isActive:true,deletedAt:null}},permission:{is:{resource:'data_assets',action:'view'}}}});if(!nativeGrant)throw new ForbiddenException('Existing data_assets.view authority is required');
  const asset=await tx.dataAsset.findFirst({where:{id:assetId,isActive:true,deletedAt:null,assetType:'ai_data_product',...(scope.orgUnits==='all'?{}:{orgUnitId:{in:scope.orgUnits}}),...(scope.domains==='all'?{}:{domainId:{in:scope.domains}}),...(scope.maxClassRank===null?{}:{classification:{is:{rank:{lte:scope.maxClassRank}}}})},select:{id:true,code:true,nameEn:true,nameAr:true}});if(!asset)throw new NotFoundException('Active scoped AI Data Product not found');
  const aggregateOnly=a.actor.roles.some(r=>['executive','AI_EXECUTIVE_TEAM','STEERING_COMMITTEE'].includes(r))&&!a.actor.roles.some(r=>['auditor','AI_GOVERNANCE_OFFICER','AI_COMPLIANCE_OFFICER','AI_WORKING_GROUP','dmo_admin'].includes(r));
  const where:Prisma.AiRiskWhereInput={AND:[a.where,{isSampleData:false,riskRef:{not:null},useCase:{is:{assetId,isSampleData:false,useCaseRef:{not:null},...(scope.orgUnits==='all'?{}:{organizationUnitId:{in:scope.orgUnits}})}}}]};return {...a,asset,where,aggregateOnly};
 }
 private async population(tx:Prisma.TransactionClient,userId:string,assetId:string){
  const a=await this.access(tx,userId,assetId),asOf=new Date(),source=await tx.aiRisk.findMany({where:a.where,select:{...AI_RISK_REPORT_SELECT,useCase:{select:{useCaseRef:true,id:true}},workflowCase:{select:{id:true,code:true,status:true}},controlPins:true,suggestedControlPins:true},orderBy:[{riskRef:'asc'},{id:'asc'}]});
  type Assessment={id:string;riskId:string;kind:string;round:number;result:Prisma.JsonValue;inputs:Prisma.JsonValue};
  const latest=source.length?await tx.$queryRaw<Assessment[]>`SELECT DISTINCT ON ("riskId",kind) id,"riskId",kind,round,result,jsonb_build_object('inherentAssessmentId',inputs->'inherentAssessmentId') AS inputs FROM ai_assessment_rounds WHERE "riskId" IN (${Prisma.join(source.map(r=>r.id))}) AND kind::text IN ('inherent','residual') ORDER BY "riskId",kind,round DESC`:[];
  const rows=source.map(r=>({...projectRisk({...r,assessments:latest.filter(x=>x.riskId===r.id)},asOf),caseId:r.workflowCase?.id,caseCode:r.workflowCase?.code,useCaseRef:r.useCase.useCaseRef,useCaseId:r.useCase.id,controlPins:r.controlPins,suggestedControlPins:r.suggestedControlPins}));return {a,asOf,rows};
 }
 private detailOnly(a:{aggregateOnly:boolean}){if(a.aggregateOnly)throw new ForbiddenException('Executive asset risk access is aggregate only');}
 async summary(userId:string,assetId:string){return this.prisma.$transaction(async tx=>{const p=await this.population(tx,userId,assetId),open=p.rows.filter(r=>!['closed','archived','rejected','cancelled'].includes(r.status)),scored=open.filter(r=>r.residualScore!==null),highest=scored.sort((a,b)=>b.residualScore!-a.residualScore!)[0]??null,actions=open.flatMap(r=>r.actions);
  const reviews=await tx.aiRiskReview.findMany({where:{risk:{is:p.a.where},completion:{is:null},cancellation:{is:null},riskId:{in:open.map(r=>r.id)}},select:{dueAt:true},orderBy:{dueAt:'asc'},take:1});
  return {asset:p.a.asset,asOf:p.asOf,visibility:'permitted_risks',aggregateOnly:p.a.aggregateOnly,registeredRiskCount:p.rows.length,openRiskCount:open.length,currentResidualCount:scored.length,unscoredOpenCount:open.length-scored.length,highestResidualScore:highest?.residualScore??null,highestResidualBand:highest?.residualBand??null,nextReviewAt:reviews[0]?.dueAt??null,approvedActionCount:actions.length,completedActionCount:actions.filter(a=>a.completed).length,overdueActionCount:actions.filter(a=>a.overdue).length,completionPct:actions.length?Math.round(actions.reduce((sum,a)=>sum+a.completionPct,0)/actions.length*100)/100:null};},{isolationLevel:Prisma.TransactionIsolationLevel.RepeatableRead});}
 async register(userId:string,assetId:string,page=1,size=20){this.page(page,size);return this.prisma.$transaction(async tx=>{const p=await this.population(tx,userId,assetId);this.detailOnly(p.a);return {rows:p.rows.slice((page-1)*size,page*size),total:p.rows.length,page,pageSize:size,asOf:p.asOf,visibility:'permitted_risks'};},{isolationLevel:Prisma.TransactionIsolationLevel.RepeatableRead});}
 async actions(userId:string,assetId:string,page=1,size=20,filter='all'){this.page(page,size);if(!['all','overdue','completed','pending'].includes(filter))throw new BadRequestException('Unknown asset action filter');return this.prisma.$transaction(async tx=>{const p=await this.population(tx,userId,assetId);this.detailOnly(p.a);const rows=p.rows.flatMap(r=>r.actions.map(a=>({...a,riskId:r.id,riskRef:r.riskRef,caseCode:r.caseCode}))).filter(a=>filter==='all'||filter==='overdue'&&a.overdue||filter==='completed'&&a.completed||filter==='pending'&&!a.completed).sort((a,b)=>(a.dueAt?.getTime()??Infinity)-(b.dueAt?.getTime()??Infinity)||a.id.localeCompare(b.id));return {rows:rows.slice((page-1)*size,page*size),total:rows.length,page,pageSize:size,asOf:p.asOf};});}
 async history(userId:string,assetId:string,riskId:string,page=1,size=20){this.page(page,size);return this.prisma.$transaction(async tx=>{const a=await this.access(tx,userId,assetId);this.detailOnly(a);if(!await tx.aiRisk.findFirst({where:{AND:[a.where,{id:riskId}]},select:{id:true}}))throw new NotFoundException('Linked permitted AI risk not found');const where={riskId};return {rows:await tx.aiAssessmentRound.findMany({where,select:{id:true,kind:true,round:true,engineVersion:true,createdAt:true,result:true,decisions:{select:{id:true,kind:true,decision:true,actorId:true,createdAt:true,justification:true}}},orderBy:[{createdAt:'desc'},{id:'desc'}],skip:(page-1)*size,take:size}),total:await tx.aiAssessmentRound.count({where}),page,pageSize:size};});}
 async reviews(userId:string,assetId:string,page=1,size=20,filter='active'){this.page(page,size);if(!['active','all','completed','overdue','superseded'].includes(filter))throw new BadRequestException('Unknown asset review filter');return this.prisma.$transaction(async tx=>{const a=await this.access(tx,userId,assetId);this.detailOnly(a);const now=new Date(),where:Prisma.AiRiskReviewWhereInput={risk:{is:a.where},...(filter==='active'?{completion:{is:null},cancellation:{is:null}}:filter==='completed'?{completion:{isNot:null},cancellation:{is:null}}:filter==='overdue'?{dueAt:{lte:now},completion:{is:null},cancellation:{is:null}}:filter==='superseded'?{cancellation:{isNot:null}}:{})};const rows=await tx.aiRiskReview.findMany({where,include:{completion:true,cancellation:true,risk:{select:{riskRef:true,workflowCase:{select:{code:true}}}}},orderBy:[{dueAt:'asc'},{id:'asc'}],skip:(page-1)*size,take:size});return {rows:rows.map(r=>({id:r.id,riskRef:r.risk.riskRef,caseCode:r.risk.workflowCase?.code,bandCode:r.bandCode,dueAt:r.dueAt,round:r.round,intervalDays:r.intervalDays,status:r.cancellation?'superseded':aiReviewStatus(!!r.completion,r.dueAt,now),completedAt:r.completion?.completedAt??null})),total:await tx.aiRiskReview.count({where}),page,pageSize:size};});}
}
