import { RISK_DIMENSIONS, RISK_DIMENSION_ROLES, jsonRecord } from './ai-risk-scoring';
export interface CoverageTask {id:string;caseId:string;stageCode:string;status:string;assigneeRoleCode:string|null;assigneeUserId:string|null;formSubmittedBy:string|null;completedAt:Date|null;dueDate:Date|null;createdAt:Date;formDataJson:unknown}
/** Dimension coverage does not imply calculation, adoption or risk acceptance. */
export function dimensionCoverage(coordinator:CoverageTask,children:CoverageTask[],asOf:Date){
 const form=jsonRecord(coordinator.formDataJson),round=form['assessmentRound'],config=jsonRecord(form['configuration']),mappings=config['dimensions'];
 const pinned=jsonRecord(config['referenceVersions']),configured=Number.isInteger(round)&&Number(round)>0&&['R_SCORE14','R_IMPD','R_LEVEL'].every(k=>typeof pinned[k]==='string'&&!!pinned[k])&&Array.isArray(mappings)&&mappings.length===8&&RISK_DIMENSIONS.every(d=>mappings.filter(m=>jsonRecord(m)['dimension']===d&&jsonRecord(m)['assessorRoleCode']===RISK_DIMENSION_ROLES[d]).length===1);
 const rows=children.filter(t=>t.status!=='cancelled'&&t.caseId===coordinator.caseId&&t.stageCode===coordinator.stageCode&&jsonRecord(t.formDataJson)['coordinatorTaskId']===coordinator.id);
 const validDimensions=configured?RISK_DIMENSIONS.filter(d=>{const matching=rows.filter(t=>jsonRecord(t.formDataJson)['dimension']===d);if(matching.length!==1)return false;const t=matching[0],data=jsonRecord(t.formDataJson),score=jsonRecord(data['score']),role=RISK_DIMENSION_ROLES[d];return data['assessmentRound']===round&&t.status==='completed'&&!!t.completedAt&&t.completedAt<=asOf&&t.assigneeRoleCode===role&&data['assessedRoleCode']===role&&!!t.formSubmittedBy&&t.formSubmittedBy===t.assigneeUserId&&data['assessedBy']===t.formSubmittedBy&&Number.isInteger(score['value'])&&Number(score['value'])>=1&&Number(score['value'])<=4&&typeof score['justification']==='string'&&!!score['justification'].trim();}).length:0;
 return {round:typeof round==='number'?round:null,validDimensions,complete:configured&&rows.length===8&&validDimensions===8};
}
export function ethicsCoverage(classificationId:string,result:unknown,tasks:CoverageTask[],asOf:Date,requesterId:string,ownerId:string|null){
 const r=jsonRecord(result),high=r['approvedTierCode']==='HIGH',mandatory=high||r['proposedTierCode']==='HIGH'&&typeof r['approvedTierCode']==='string'||r['approvedTierCode']==='UNACCEPTABLE';
 const reviewed=tasks.some(t=>{const f=jsonRecord(t.formDataJson),e=f['evidenceIds'];return t.stageCode==='aiuc-ethics-review'&&t.status==='completed'&&!!t.completedAt&&t.completedAt<=asOf&&t.assigneeRoleCode==='AI_ETHICS_COMMITTEE'&&!!t.formSubmittedBy&&t.formSubmittedBy===t.assigneeUserId&&t.formSubmittedBy!==requesterId&&t.formSubmittedBy!==ownerId&&f['classificationDecisionId']===classificationId&&['approve','return','reject'].includes(String(f['reviewDecision']))&&typeof f['justification']==='string'&&!!f['justification'].trim()&&Array.isArray(e)&&e.length>0&&e.length<=20&&e.every(id=>typeof id==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(id));});
 return {high,mandatory,reviewed};
}
