// FD §8.1: live current scoped KPI definitions; scheduled period snapshots remain separate.
export const AI_KPI_CATALOG = [
  {
    "id": "GEN-81",
    "labelEn": "Submitted adoption requests",
    "labelAr": "طلبات التبني المقدمة",
    "group": "pipeline",
    "unit": "count",
    "frequency": "Monthly",
    "owner": "AI_WORKING_GROUP",
    "formulaEn": "Submitted AIUC cases, excluding drafts and sample rows.",
    "formulaAr": "طلبات AIUC المقدمة باستثناء المسودات والسجلات التجريبية.",
    "filter": null,
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-82",
    "labelEn": "Acceptance rate",
    "labelAr": "نسبة القبول",
    "group": "pipeline",
    "unit": "percent",
    "frequency": "Monthly",
    "owner": "AI_GOVERNANCE_OFFICER",
    "formulaEn": "Terminal AIUC cases with Approved or Approved with Conditions resolution / all terminal AIUC cases.",
    "formulaAr": "طلبات التبني المنتهية بقرار قبول أو قبول مشروط ÷ جميع الطلبات المنتهية.",
    "filter": null,
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-83",
    "labelEn": "Triage SLA compliance",
    "labelAr": "الالتزام بمهلة الفرز",
    "group": "pipeline",
    "unit": "percent",
    "frequency": "Monthly",
    "owner": "AI_WORKING_GROUP",
    "formulaEn": "Completed triage attempts at or before pinned five-business-day deadline / all completed triage attempts.",
    "formulaAr": "محاولات الفرز المنجزة بحلول مهلة خمسة أيام عمل المثبتة ÷ جميع محاولات الفرز المنجزة.",
    "filter": null,
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-84",
    "labelEn": "Return-for-completion rate",
    "labelAr": "نسبة الإعادة للاستكمال",
    "group": "pipeline",
    "unit": "percent",
    "frequency": "Monthly",
    "owner": "AI_WORKING_GROUP",
    "formulaEn": "Completed triage attempts with return event / all completed triage attempts.",
    "formulaAr": "محاولات الفرز المنجزة ذات حدث إعادة للاستكمال ÷ جميع محاولات الفرز المنجزة.",
    "filter": null,
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-85",
    "labelEn": "Registered AI use cases",
    "labelAr": "إجمالي حالات الاستخدام",
    "group": "register",
    "unit": "count",
    "frequency": "Daily",
    "owner": "AI_WORKING_GROUP",
    "formulaEn": "Non-sample use cases with business reference and active registered asset.",
    "formulaAr": "حالات الاستخدام غير التجريبية ذات المرجع وأصل مسجل نشط.",
    "filter": "registered",
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-86",
    "labelEn": "Total identified risks",
    "labelAr": "إجمالي المخاطر",
    "group": "posture",
    "unit": "count",
    "frequency": "Daily",
    "owner": "AI_GOVERNANCE_OFFICER",
    "formulaEn": "Eligible identified non-sample risks with AIR reference.",
    "formulaAr": "المخاطر المؤهلة غير التجريبية ذات مرجع AIR.",
    "filter": "identified",
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-87",
    "labelEn": "Critical/High residual risks",
    "labelAr": "كارثية/مرتفعة متبقية",
    "group": "posture",
    "unit": "count",
    "frequency": "Daily",
    "owner": "AI_EXECUTIVE_TEAM",
    "formulaEn": "Current calculated residual band is exactly HIGH or CRITICAL.",
    "formulaAr": "مستوى الخطر المتبقي المحسوب حالياً مرتفع أو كارثي.",
    "filter": "residual_high",
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-88",
    "labelEn": "Open risks",
    "labelAr": "مخاطر مفتوحة",
    "group": "posture",
    "unit": "count",
    "frequency": "Daily",
    "owner": "AI_RISK_OWNER",
    "formulaEn": "Identified risk cases excluding closed and cancelled lifecycle states.",
    "formulaAr": "حالات المخاطر المعرفة باستثناء حالات سير العمل المغلقة والملغاة.",
    "filter": "open",
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-89",
    "labelEn": "Risks without owner",
    "labelAr": "مخاطر بدون مالك",
    "group": "posture",
    "unit": "count",
    "frequency": "Daily",
    "owner": "AI_GOVERNANCE_OFFICER",
    "formulaEn": "Identified risks with no assigned risk-owner person.",
    "formulaAr": "المخاطر المعرفة التي لم يُعيّن لها مالك خطر.",
    "filter": "without_owner",
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-90",
    "labelEn": "Average inherent score",
    "labelAr": "متوسط الخطر المتأصل",
    "group": "posture",
    "unit": "score",
    "frequency": "Monthly",
    "owner": "AI_GOVERNANCE_OFFICER",
    "formulaEn": "Mean current calculated inherent score; unassessed risks excluded.",
    "formulaAr": "متوسط الخطر المتأصل المحسوب حالياً؛ تُستبعد المخاطر غير المقيمة.",
    "filter": null,
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-91",
    "labelEn": "Average residual score",
    "labelAr": "متوسط الخطر المتبقي",
    "group": "posture",
    "unit": "score",
    "frequency": "Monthly",
    "owner": "AI_GOVERNANCE_OFFICER",
    "formulaEn": "Mean current calculated residual score paired with its inherent round.",
    "formulaAr": "متوسط الخطر المتبقي المحسوب حالياً والمرتبط بجولته المتأصلة.",
    "filter": null,
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-92",
    "labelEn": "Risk reduction ratio",
    "labelAr": "نسبة تخفيض الخطر",
    "group": "posture",
    "unit": "percent",
    "frequency": "Monthly",
    "owner": "AI_GOVERNANCE_OFFICER",
    "formulaEn": "Mean (inherent - residual) / inherent for valid current pairs, expressed as percent. Negative values remain visible.",
    "formulaAr": "متوسط (المتأصل − المتبقي) ÷ المتأصل لأزواج الجولات الحالية الصالحة، بالنسبة المئوية؛ تظهر القيم السالبة.",
    "filter": null,
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-93",
    "labelEn": "Treated-risk ratio",
    "labelAr": "نسبة المخاطر المعالجة",
    "group": "treatment",
    "unit": "percent",
    "frequency": "Monthly",
    "owner": "AI_RISK_OWNER",
    "formulaEn": "Risks with every current approved non-cancelled action verified complete / risks with current approved non-sample plan actions.",
    "formulaAr": "المخاطر المنجزة جميع إجراءات خطتها الحالية المعتمدة وغير الملغاة ÷ المخاطر ذات إجراءات خطة معتمدة حالية غير تجريبية.",
    "filter": "treated",
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-94",
    "labelEn": "Overdue treatment actions",
    "labelAr": "إجراءات متأخرة",
    "group": "treatment",
    "unit": "count",
    "frequency": "Daily",
    "owner": "AI_RISK_OWNER",
    "formulaEn": "Current approved non-sample actions still uncompleted at or after protected Saudi due date.",
    "formulaAr": "إجراءات المعالجة الحالية المعتمدة وغير التجريبية التي لم تُنجز وحلّ موعدها السعودي المثبت.",
    "filter": "overdue_actions",
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-95",
    "labelEn": "Overdue reviews",
    "labelAr": "مراجعات متأخرة",
    "group": "reviews",
    "unit": "count",
    "frequency": "Daily",
    "owner": "AI_GOVERNANCE_OFFICER",
    "formulaEn": "Uncompleted unsuperseded reviews due at or before server as-of time.",
    "formulaAr": "المراجعات غير المنجزة وغير المستبدلة التي حلّ موعدها حتى وقت التقرير.",
    "filter": null,
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-96",
    "labelEn": "On-time review compliance",
    "labelAr": "إنجاز الدوريات في موعدها",
    "group": "reviews",
    "unit": "percent",
    "frequency": "Monthly",
    "owner": "AI_GOVERNANCE_OFFICER",
    "formulaEn": "Unsuperseded reviews closed by due date / all unsuperseded reviews due as of server time.",
    "formulaAr": "المراجعات غير المستبدلة المنجزة بحلول موعدها ÷ المراجعات غير المستبدلة التي حلّ موعدها حتى وقت التقرير.",
    "filter": null,
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-97",
    "labelEn": "High/Critical plan completeness",
    "labelAr": "اكتمال خطط معالجة المرتفعة/الكارثية",
    "group": "treatment",
    "unit": "percent",
    "frequency": "Monthly",
    "owner": "AI_EXECUTIVE_TEAM",
    "formulaEn": "Current inherently High/Critical risks with at least one verified completed action in their current approved plan / all current inherently High/Critical risks.",
    "formulaAr": "المخاطر المتأصلة المرتفعة أو الكارثية ذات إجراء منجز موثق واحد على الأقل في خطتها الحالية المعتمدة ÷ جميع المخاطر المتأصلة المرتفعة أو الكارثية الحالية.",
    "filter": "plan_incomplete",
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-98",
    "labelEn": "High-risk use cases (SDAIA)",
    "labelAr": "حالات عالية المخاطر (سدايا)",
    "group": "register",
    "unit": "count",
    "frequency": "Daily",
    "owner": "AI_EXECUTIVE_TEAM",
    "formulaEn": "Exact approved SDAIA tier HIGH in eligible register; proposed tier and residual risk band are not used.",
    "formulaAr": "تصنيف سدايا المعتمد «مخاطر عالية» حصراً في السجل المؤهل؛ لا يُستخدم التصنيف المقترح أو مستوى الخطر المتبقي.",
    "filter": "sdaia_high",
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-99",
    "labelEn": "Unclassified use cases",
    "labelAr": "حالات غير مصنفة",
    "group": "register",
    "unit": "count",
    "frequency": "Daily",
    "owner": "AI_WORKING_GROUP",
    "formulaEn": "Eligible register rows with no approved SDAIA tier.",
    "formulaAr": "سجلات الاستخدام المؤهلة التي لا تحمل تصنيف سدايا معتمداً.",
    "filter": "unclassified",
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-100",
    "labelEn": "Dimension-assessment completeness",
    "labelAr": "اكتمال تقييمات الأبعاد بالمبررات",
    "group": "governance",
    "unit": "percent",
    "frequency": "Monthly",
    "owner": "AI_GOVERNANCE_OFFICER",
    "formulaEn": "Current non-cancelled native assessment rounds with eight verified justified dimensions / current rounds due by server as-of time. Missing deadlines are reported separately.",
    "formulaAr": "جولات التقييم الحالية غير الملغاة المكتملة بالأبعاد الثمانية الموثقة ومبرراتها ÷ الجولات المستحقة حتى وقت التقرير؛ تُعرض المواعيد المفقودة منفصلة.",
    "filter": "assessment_gaps",
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  },
  {
    "id": "GEN-101",
    "labelEn": "Ethics-committee coverage",
    "labelAr": "خضوع الحالات عالية المخاطر لمراجعة اللجنة",
    "group": "governance",
    "unit": "percent",
    "frequency": "Monthly",
    "owner": "AI_ETHICS_COMMITTEE",
    "formulaEn": "Approved SDAIA HIGH cases with an evidenced independent stage-five outcome for the current classification decision / all approved HIGH submitted cases. Approve, return and reject are reviewed outcomes.",
    "formulaAr": "طلبات التبني المقدمة ذات تصنيف سدايا العالي المعتمد ونتيجة موثقة مستقلة للمرحلة الخامسة مرتبطة بقرار التصنيف الحالي ÷ جميع الطلبات المقدمة ذات التصنيف العالي المعتمد؛ تشمل النتائج القبول والإعادة والرفض.",
    "filter": "ethics_gaps",
    "coverage": "live",
    "coverageNote": "Current scoped projection; scheduled period snapshots are not implemented."
  }
] as const;
