import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { TestBed } from '@angular/core/testing';
import { I18nService } from '../../../core/i18n.service';
import { ToastService } from '../../../shared/toast.service';
import { AiReviewsPage } from './ai-reviews';

describe('AI review history paging and stale requests',()=>{
  let http:HttpTestingController,page:any,errors:unknown[];
  beforeEach(()=>{vi.stubGlobal('ResizeObserver',class{observe(){}unobserve(){}disconnect(){}});errors=[];
    TestBed.configureTestingModule({imports:[AiReviewsPage],providers:[provideHttpClient(),provideHttpClientTesting(),{provide:I18nService,useValue:{t:(key:string)=>key,lang:()=> 'en'}},{provide:ToastService,useValue:{errorFrom:(e:unknown)=>errors.push(e),success:()=>{}}}]});
    http=TestBed.inject(HttpTestingController);page=TestBed.runInInjectionContext(()=>new AiReviewsPage());page.unitId='unit';
  });
  afterEach(()=>{http.verify();vi.unstubAllGlobals();});
  function annual(id='current',overrides:Record<string,unknown>={}){return{data:[{id,round:101,canHandover:false,canComplete:false}],total:101,page:1,pageSize:25,totalPages:5,canRegister:false,canCaptureMonthly:false,...overrides};}
  it('requests annual page 5 and Arabic search on the server',async()=>{page.annualSearch='بحث';const work=page.loadAnnual(5),req=http.expectOne(r=>r.url.endsWith('/annual/unit'));expect(req.request.params.get('page')).toBe('5');expect(req.request.params.get('pageSize')).toBe('25');expect(req.request.params.get('search')).toBe('بحث');req.flush(annual('old',{page:5}));await work;expect(page.annual().total).toBe(101);expect(page.annual().data[0].id).toBe('old');});
  it('ignores older annual success after a newer organization selection',async()=>{const old=page.loadAnnual(),older=http.expectOne(r=>r.url.endsWith('/annual/unit'));page.unitId='new';const latest=page.selectUnit(),newer=http.expectOne(r=>r.url.endsWith('/annual/new'));newer.flush(annual('new'));await latest;older.flush(annual('old'));await old;expect(page.annual().data[0].id).toBe('new');});
  it('ignores an old annual error and keeps the new state',async()=>{const old=page.loadAnnual(),older=http.expectOne(r=>r.url.endsWith('/annual/unit'));const latest=page.loadAnnual(2),newer=http.expectOne(r=>r.url.endsWith('/annual/unit'));newer.flush(annual('new',{page:2}));await latest;older.flush({},{status:500,statusText:'old failure'});await old;expect(page.annualState()).toBe('ok');expect(errors).toEqual([]);});
  it('loads paged nominees only for an actionable handover',async()=>{const work=page.loadAnnual(),req=http.expectOne(r=>r.url.endsWith('/annual/unit'));req.flush(annual('live',{data:[{id:'live',canHandover:true}]}));await vi.waitFor(()=>expect(page.nomineeLoading()).toBe(true));const nominees=http.expectOne(r=>r.url.endsWith('/nominees'));expect(nominees.request.params.get('pageSize')).toBe('25');nominees.flush({data:[{id:'officer101',email:'eligible@example.invalid'}],total:1,page:1,pageSize:25,totalPages:1});await work;expect(page.nominees().data[0].id).toBe('officer101');});
  it('clears nominee selection and ignores stale results during a new search',async()=>{page.nomineeId='old';const old=page.loadNominees(),older=http.expectOne(r=>r.url.endsWith('/nominees'));page.nomineeSearch='new';const latest=page.loadNominees(2),newer=http.expectOne(r=>r.url.endsWith('/nominees'));expect(page.nomineeId).toBe('');newer.flush({data:[],total:0,page:2,pageSize:25,totalPages:1});await latest;older.flush({data:[{id:'old'}],total:1,page:1,pageSize:25,totalPages:1});await old;expect(page.nominees().data).toEqual([]);});
  it('uses monthly envelopes and server page/search beyond the old limit',async()=>{page.monthlySearch='2000';const work=page.loadMonthly(5),req=http.expectOne(r=>r.url.endsWith('/monthly/unit'));expect(req.request.params.get('page')).toBe('5');expect(req.request.params.get('search')).toBe('2000');req.flush({data:[{id:'old',periodMonth:'2000-01'}],total:101,page:5,pageSize:25,totalPages:5});await work;expect(page.monthlyRows()[0].id).toBe('old');expect(page.monthlyPage().total).toBe(101);});
  it('does not present failed monthly loads as empty history',async()=>{const work=page.loadMonthly(),req=http.expectOne(r=>r.url.endsWith('/monthly/unit'));req.flush({},{status:503,statusText:'unavailable'});await work;expect(page.monthlyError()).toBe(true);expect(page.monthlyPage()).toBeNull();expect(errors.length).toBe(1);});
  it('discards a snapshot response after switching organizations',async()=>{const old=page.openMonthly('snapshot'),req=http.expectOne(r=>r.url.endsWith('/monthly-snapshots/snapshot'));page.unitId='';await page.selectUnit();req.flush({id:'snapshot'});await old;expect(page.monthlySnapshot()).toBeNull();expect(page.monthlyLoading()).toBe(false);});
  it('renders history search bounds and keyboard-friendly pager controls',async()=>{const fixture=TestBed.createComponent(AiReviewsPage);fixture.detectChanges();const report=http.expectOne(r=>r.url.includes('/report?'));report.flush({mode:'audit',periodic:{},aggregateOnly:true,calendar:[],calendarTotal:0,page:1,pageSize:20});await vi.waitFor(()=>expect((fixture.componentInstance as any).state()).toBe('ok'));http.expectOne('/api/ai/review-operations/units').flush({units:[]});const component:any=fixture.componentInstance;component.tab.set('annual');component.unitId='unit';component.annualState.set('ok');component.annual.set(annual('old',{data:[]}));fixture.detectChanges();expect(fixture.nativeElement.querySelector('input[type="search"]').maxLength).toBe(200);expect(fixture.nativeElement.querySelectorAll('nav.review-pagination button').length).toBe(2);expect(fixture.nativeElement.textContent).toContain('101');fixture.destroy();});
});
