import 'reflect-metadata';
import assert from 'node:assert/strict';
import { PrismaClient } from '@prisma/client';
import { AiIdentifiersService } from '../src/ai-governance/ai-identifiers.service';
import { GovernedReferenceService } from '../src/master-data/governed-reference.service';
import { PrismaService } from '../src/prisma/prisma.service';
import { NestFactory } from '@nestjs/core';
import { AppModule } from '../src/app.module';
import { testPhase1B } from './ai-phase1b.integration';
import { testPhase2A } from './ai-phase2a.integration';
import { testAiRequestLifecycle } from './ai-request-lifecycle.integration';

const url = new URL(process.env.DGOP_AI_TEST_DATABASE_URL ?? '');
assert.equal(url.hostname, '127.0.0.1');
assert.equal(url.port, '55438');
assert.match(url.pathname, /^\/dgop_ai_test_/);
process.env.DATABASE_URL = url.href;
process.env.NODE_ENV = 'test';
process.env.WORKFLOW_EXECUTION_SCHEDULER = 'false';
process.env.GOVERNANCE_OPERATIONS_SCHEDULER = 'false';
const db = new PrismaClient({ datasources: { db: { url: url.href } } });
const ids = new AiIdentifiersService();
let rejected = 0;
async function blocked(operation: Promise<unknown>) { await assert.rejects(operation); rejected++; }
async function main() {
  if (process.argv[2] === 'upgrade') assert.equal((await db.user.findUniqueOrThrow({ where: { id: 'baseline-sentinel' } })).displayName, 'Existing DGOP user');
  const user = await db.user.create({ data: { email: 'ai-fixture@example.test', passwordHash: 'not-a-login', displayName: 'AI fixture' } });
  const identity = { requesterUserId: user.id, createdBy: user.id, name: 'Test use case' };
  const first = await db.aiUseCase.create({ data: { ...identity, useCaseRef: 'AI-001' } });
  const allocated = await Promise.all(Array.from({ length: 8 }, () => db.$transaction(async tx => {
    const useCaseRef = await ids.nextUseCaseRef(tx);
    return tx.aiUseCase.create({ data: { ...identity, useCaseRef } });
  }, { maxWait: 15000, timeout: 15000 })));
  assert.deepEqual(allocated.map(x => x.useCaseRef).sort(), ['AI-002','AI-003','AI-004','AI-005','AI-006','AI-007','AI-008','AI-009']);
  await assert.rejects(db.$transaction(async tx => { assert.equal(await ids.nextUseCaseRef(tx), 'AI-010'); throw new Error('rollback'); }));
  assert.equal(await db.$transaction(tx => ids.nextUseCaseRef(tx)), 'AI-010');
  assert.equal(await db.$transaction(tx => ids.nextCaseCode(tx, 'AIUC', 2026)), 'AIUC-2026-000001');
  assert.equal(await db.$transaction(tx => ids.nextCaseCode(tx, 'AIRS', 2026)), 'AIRS-2026-000001');
  assert.equal(await db.$transaction(tx => ids.nextCaseCode(tx, 'AIUC', 2027)), 'AIUC-2027-000001');
  await blocked(db.aiUseCase.update({ where: { id: first.id }, data: { name: 'stale' } }));
  await db.aiUseCase.update({ where: { id: first.id }, data: { name: 'Updated', version: 2 } });
  await blocked(db.aiUseCase.update({ where: { id: first.id }, data: { useCaseRef: 'AI-900', version: 3 } }));
  await blocked(db.aiUseCase.delete({ where: { id: first.id } }));
  const revision = await db.aiIntakeRevision.create({ data: { useCaseId: first.id, revision: 1, payload: { usecase_name: 'اختبار' }, createdBy: user.id } });
  await blocked(db.aiIntakeRevision.update({ where: { id: revision.id }, data: { payload: {} } }));
  await blocked(db.aiIntakeRevision.delete({ where: { id: revision.id } }));
  await blocked(db.aiRisk.create({ data: { useCaseId: first.id, riskRef: 'AIR-001', createdBy: user.id } }));
  const risk = await db.$transaction(async tx => tx.aiRisk.create({ data: { useCaseId: first.id, riskRef: await ids.nextRiskRef(tx), title: 'Risk', cause: 'Cause', event: 'Event', effect: 'Effect', createdBy: user.id } }));
  assert.equal(risk.riskRef, 'AIR-001');
  const action = await db.$transaction(async tx => tx.aiTreatmentAction.create({ data: { riskId: risk.id, actionRef: await ids.nextActionRef(tx), title: 'Mitigate', createdBy: user.id } }));
  assert.equal(action.actionRef, 'ACT-001');
  await blocked(db.aiRisk.update({ where: { id: risk.id }, data: { useCaseId: allocated[0].id, version: 2 } }));
  await blocked(db.aiApprovalObligation.create({ data: { useCaseId: allocated[0].id, riskId: risk.id, sourceKey: 'condition1', description: 'Condition', createdBy: user.id } }));
  await db.governedReferenceList.create({ data: { code: 'TEST_RULES', nameEn: 'Rules', nameAr: 'قواعد', ownerRoleCode: 'test' } });
  const draft = await db.governedReferenceVersion.create({ data: { listCode: 'TEST_RULES', version: 1, createdBy: user.id } });
  const publish = { state: 'published' as const, effectiveFrom: new Date('2026-01-01'), approvedBy: user.id, approvedAt: new Date() };
  await blocked(db.governedReferenceVersion.update({ where: { id: draft.id }, data: publish }));
  await db.governedReferenceValue.create({ data: { versionId: draft.id, code: 'LOW', labelEn: 'Low', labelAr: 'منخفض', metadata: { score: 1 } } });
  const assessment = { useCaseId: first.id, kind: 'classification' as const, round: 1, engineVersion: 'fixture-v1', ruleReferenceVersionId: draft.id, inputs: {}, result: {}, createdBy: user.id };
  await blocked(db.aiAssessmentRound.create({ data: assessment }));
  await db.governedReferenceVersion.update({ where: { id: draft.id }, data: publish });
  const snapshot = await db.aiAssessmentRound.create({ data: assessment });
  await blocked(db.aiAssessmentRound.create({ data: assessment }));
  await blocked(db.aiAssessmentRound.update({ where: { id: snapshot.id }, data: { result: { changed: true } } }));
  await blocked(db.aiAssessmentRound.delete({ where: { id: snapshot.id } }));
  await blocked(db.aiAssessmentRound.create({ data: { ...assessment, kind: 'inherent', riskId: risk.id, useCaseId: allocated[0].id } }));
  await db.aiAssessmentRound.create({ data: { ...assessment, kind: 'inherent', riskId: risk.id } });
  const next = await db.governedReferenceVersion.create({ data: { listCode: 'TEST_RULES', version: 2, createdBy: user.id } });
  await blocked(db.governedReferenceValue.update({ where: { versionId_code: { versionId: draft.id, code: 'LOW' } }, data: { versionId: next.id } }));
  await blocked(db.governedReferenceVersion.update({ where: { id: draft.id }, data: { sourceLocator: 'changed' } }));
  const refs = new GovernedReferenceService(db as PrismaService);
  assert.equal((await refs.activeVersion('TEST_RULES', new Date('2026-06-01'))).id, draft.id);
  await db.governedReferenceVersion.update({ where: { id: draft.id }, data: { state: 'retired', effectiveTo: new Date('2026-09-01') } });
  assert.equal((await refs.historicalVersion(draft.id)).values[0].code, 'LOW');
  await blocked(db.aiAssessmentRound.create({ data: { ...assessment, round: 2 } }));
  await blocked(refs.activeVersion('TEST_RULES'));
  await blocked(refs.historicalVersion(next.id));
  const app = await NestFactory.createApplicationContext(AppModule, { logger: false });
  assert.ok(app.get(AiIdentifiersService));
  assert.ok(app.get(GovernedReferenceService));
  await app.close();
  await testPhase1B(db);
  await testPhase2A(db);
  await testAiRequestLifecycle(db);
  console.log(`Database foundation passed: concurrent/collision/rollback numbering, parent integrity, immutable history, reference lifecycle, ${rejected} rejected invalid writes/reads, full Nest application startup.`);
}
main().finally(() => db.$disconnect()).catch(error => { console.error(error); process.exitCode = 1; });
