import 'reflect-metadata';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFileSync,writeFileSync } from 'node:fs';
import { NestFactory } from '@nestjs/core';
import { AppModule } from '../src/app.module';
import { PrismaService } from '../src/prisma/prisma.service';
import { AuditService } from '../src/audit/audit.service';
import { EvidenceService } from '../src/evidence/evidence.service';
import { AiEvidenceService } from '../src/ai-governance/ai-evidence.service';
import { AiLifecycleService } from '../src/ai-governance/ai-lifecycle.service';
import { AiRiskIntakeService } from '../src/ai-governance/ai-risk-intake.service';
import { AiIdentifiersService } from '../src/ai-governance/ai-identifiers.service';
import { isManagedDemoProfile } from '../src/common/demo-profile';
import { AuthUser } from '../src/auth/auth.types';
const startedAt=new Date().toISOString(),checks:string[]=[],url=new URL(process.env.DATABASE_URL!);
async function main(){assert.equal(url.hostname,'127.0.0.1');assert.equal(url.port,'55438');assert.match(url.pathname,/^\/dgop_ai_test_repair_batch1_\d+$/);assert.equal(isManagedDemoProfile(),true);
 const manifest=JSON.parse(readFileSync(process.env.DGOP_DEMO_MANIFEST!,'utf8')),app=await NestFactory.createApplicationContext(AppModule,{logger:false}),db=app.get(PrismaService),audit=app.get(AuditService),lifecycle=app.get(AiLifecycleService),proof=app.get(AiEvidenceService),files=app.get(EvidenceService),risks=app.get(AiRiskIntakeService);
 const actor=async(name:string):Promise<AuthUser>=>{const u=await db.user.findUniqueOrThrow({where:{id:manifest.actors[name]},include:{userRoles:{include:{role:true}}}});return{id:u.id,email:u.email,roles:u.userRoles.map(r=>r.role.code)}};
 const author=await actor('showcase'),reviewer=await actor('custodian');let ucId='',evidenceId='',passed=false,error:string|null=null;
 const assignments={AI_WORKING_GROUP:manifest.actors.working,AI_GOVERNANCE_OFFICER:manifest.actors.officer,AI_EXECUTIVE_TEAM:manifest.actors.executive,STEERING_COMMITTEE:manifest.actors.steering,AI_ETHICS_COMMITTEE:manifest.actors.ethics,privacy_officer:manifest.actors.privacy,security_reviewer:manifest.actors.security,AI_MODEL_OWNER:manifest.actors.model,AI_MLOPS_LEAD:manifest.actors.mlops,business_steward:manifest.actors.business};
 const source=await db.aiUseCase.findFirstOrThrow({where:{assetId:{not:null},name:{startsWith:'DEMO'},deletedAt:null},include:{intakeRevisions:{orderBy:{revision:'desc'},take:1},assessments:{where:{kind:'classification'},orderBy:{round:'desc'},take:1},risks:{where:{deletedAt:null},take:1}}});
 const tag='B5 SYNTHETIC lifecycle '+randomUUID(),assetBefore=await db.dataAsset.findUniqueOrThrow({where:{id:source.assetId!}}),initialAudit=await audit.verifyChain();assert.equal(initialAudit.valid,true);
 const pending=async(id:string)=>{const r=await db.aiLifecycleRequest.findUniqueOrThrow({where:{id},include:{workflowCase:{include:{tasks:{where:{status:'pending'},orderBy:{createdAt:'asc'}}}}}});return r;};
 const link=async(id:string)=>proof.link(author.id,'ai_lifecycle_request',id,[evidenceId],'Synthetic approved proof explicitly supports this exact registered lifecycle request');
 const decideAll=async(id:string,until='applied')=>{for(let i=0;i<20;i++){const r=await pending(id);if(r.status===until||['returned','rejected'].includes(r.status))return r;const t=r.workflowCase.tasks[0];assert.ok(t,'A native next-action task is required');await lifecycle.decide(t.assigneeUserId!,id,t.id,{expectedVersion:r.version,decision:'approve',justification:'Independent synthetic '+String((t.formDataJson as any).kind)+' decision',evidenceIds:[evidenceId],...((t.formDataJson as any).kind==='authority'?{conditions:['Retain human oversight for the synthetic demonstration']}:{})});}throw Error('Lifecycle exceeded its bounded task sequence');};
 const assessAll=async(id:string)=>{for(let i=0;i<100;i++){const r=await pending(id);if(r.status!=='assessment')return r;const t=r.workflowCase.tasks[0];assert.ok(t);const kind=(t.formDataJson as any).kind;await lifecycle.assess(t.assigneeUserId!,id,t.id,{expectedVersion:r.version,justification:'Fresh synthetic assessment of this proposed configuration',...(kind==='classification'?{input:{kind:'classification',scores:Array.from({length:6},()=>({value:3,justification:'Fresh supervised synthetic configuration'}))}}:{score:1})});}throw Error('Assessment exceeded bounded fixture risk tasks');};
 try{
  const registration=await db.workflowCase.create({data:{code:await db.$transaction(tx=>app.get(AiIdentifiersService).nextCaseCode(tx,'AIUC',2026)),type:'AIUC',title:tag,status:'closed',assetId:source.assetId,createdBy:'diagnostic:historical-registration'}});
  const uc=await db.aiUseCase.create({data:{
   workflowCaseId:registration.id,name:tag,useCaseRef:await db.$transaction(tx=>app.get(AiIdentifiersService).nextUseCaseRef(tx)),assetId:source.assetId,requesterUserId:source.requesterUserId,
   ownerPersonId:source.ownerPersonId,organizationUnitId:source.organizationUnitId,createdBy:'diagnostic:batch5',
   intakeRevisions:{create:{revision:1,payload:{...(source.intakeRevisions[0].payload as object),usecase_name:tag},submittedAt:new Date(),createdBy:author.id}},
   assessments:{create:{kind:'classification',round:1,engineVersion:source.assessments[0].engineVersion,
    ruleReferenceVersionId:source.assessments[0].ruleReferenceVersionId,inputs:source.assessments[0].inputs as any,
    result:source.assessments[0].result as any,createdBy:'diagnostic:historical-baseline'}}
  }});ucId=uc.id;
  const wf=await db.workflowCase.create({data:{code:await db.$transaction(tx=>app.get(AiIdentifiersService).nextCaseCode(tx,'AIRS',2026)),type:'AIRS',title:tag,status:'implemented',assetId:source.assetId,createdBy:'diagnostic:batch5'}});
  const sourceRisk=source.risks[0];assert.ok(sourceRisk);
  await db.aiRisk.create({data:{useCaseId:uc.id,workflowCaseId:wf.id,ownerPersonId:sourceRisk.ownerPersonId,riskRef:await db.$transaction(tx=>app.get(AiIdentifiersService).nextRiskRef(tx)),title:tag,cause:'Synthetic source dependency',event:'Synthetic incorrect response',effect:'Synthetic process disruption',createdBy:'diagnostic:batch5'}});
  await db.aiApprovalObligation.create({data:{useCaseId:uc.id,assetId:source.assetId,riskId:(await db.aiRisk.findFirstOrThrow({where:{useCaseId:uc.id}})).id,sourceKey:'diagnostic-baseline',description:'Preserved historical diagnostic obligation',createdBy:author.id}});
  const spec=await db.ndiSpecification.findFirstOrThrow(),buffer=Buffer.from('Synthetic lifecycle review evidence '+tag),e=await files.create({specId:spec.id,title:tag,submit:'true'},{buffer,size:buffer.length,originalname:'synthetic-lifecycle.txt',mimetype:'text/plain'},author);evidenceId=e.id;await files.review(e.id,{decision:'approve',comment:'Independent approval of synthetic lifecycle proof'},reviewer);
  const baseline=await lifecycle.context(author.id,uc.id);assert.equal(baseline.baselineAssurance,'review_needed');checks.push('historical registration is retained without invented trustworthy proof');
  await assert.rejects(lifecycle.propose(manifest.actors.administrator,uc.id,{expectedVersion:1,action:'suspend',justification:tag,assignments}),/explicit eligible/);await assert.rejects(lifecycle.propose(manifest.actors.auditor,uc.id,{expectedVersion:1,action:'suspend',justification:tag,assignments}),/explicit eligible/);checks.push('platform-only administrator and auditor cannot perform business lifecycle proposals');
  await assert.rejects(lifecycle.propose(author.id,uc.id,{expectedVersion:1,action:'resume',justification:tag,assignments}),/invalid/);assert.equal(await db.aiLifecycleRequest.count({where:{useCaseId:uc.id}}),0);checks.push('invalid transitions roll back without orphan workflow or baseline records');
  const requests=await Promise.allSettled([lifecycle.propose(author.id,uc.id,{expectedVersion:1,action:'change',changes:{objective_value:'B5 independently approved objective'},justification:tag,assignments}),lifecycle.propose(author.id,uc.id,{expectedVersion:1,action:'suspend',justification:tag,assignments})]);assert.equal(requests.filter(r=>r.status==='fulfilled').length,1);
  const first=(requests.find(r=>r.status==='fulfilled') as PromiseFulfilledResult<any>).value;await lifecycle.withdraw(author.id,first.id,1,'Preserve concurrency diagnostic and continue one fresh journey');checks.push('concurrent proposals admit exactly one pending native request and preserve the withdrawn record');
  const changed=await lifecycle.propose(author.id,uc.id,{expectedVersion:2,action:'change',changes:{objective_value:'B5 independently approved objective'},justification:tag,assignments});await link(changed.id);
  const stillOld=await lifecycle.context(author.id,uc.id);assert.equal((stillOld.effective.payload as any).objective_value,(source.intakeRevisions[0].payload as any).objective_value);assert.equal(stillOld.effectiveUseAllowed,true);assert.equal(stillOld.data[0].proposedUseAllowed,false);assert.equal(stillOld.canPropose,false);checks.push('pending changed configuration is held while unaffected approved use remains effective and duplicate proposal controls are disabled');
  const modelContext=await lifecycle.context(manifest.actors.model,uc.id);assert.ok(modelContext.data.some(r=>r.tasks.some(t=>t.canAct&&t.assigneeUserId===manifest.actors.model)));await proof.read(manifest.actors.model,'ai_lifecycle_request',changed.id,new (class {page=1;pageSize=25;search=''})());checks.push('named specialist own-scope access discovers assigned lifecycle work and its relevant proof');
  let r=await pending(changed.id),t=r.workflowCase.tasks[0];await assert.rejects(lifecycle.assess(manifest.actors.administrator,r.id,t.id,{expectedVersion:r.version,justification:tag,score:1}),/named active/);await assessAll(r.id);r=await pending(r.id);assert.ok(r.assessmentSnapshot);assert.equal((r.riskSnapshot as any[]).length,1);assert.equal((r.riskSnapshot as any[])[0].contributors.length,8);checks.push('fresh six-criterion and nine-task risk assessment use live competent named grants and governed methodology');
  t=r.workflowCase.tasks[0];await assert.rejects(lifecycle.decide(t.assigneeUserId!,r.id,t.id,{expectedVersion:r.version-1,decision:'approve',justification:tag,evidenceIds:[evidenceId]}),/changed/);checks.push('stale task versions reject without modifying decisions');
  await assert.rejects(lifecycle.decide(t.assigneeUserId!,r.id,t.id,{expectedVersion:r.version,decision:'approve',justification:tag,evidenceIds:[]}),/evidence/);assert.equal(await db.aiLifecycleDecision.count({where:{requestId:r.id}}),0);checks.push('a final lifecycle decision cannot commit without verified relevant evidence');
  await decideAll(r.id,'confirmation');const confirmation=await pending(r.id);assert.equal((await lifecycle.context(author.id,uc.id)).effectiveUseAllowed,true);assert.equal(await db.aiIntakeRevision.count({where:{useCaseId:uc.id}}),1);
  const ct=confirmation.workflowCase.tasks[0],beforeDecisions=await db.aiLifecycleDecision.count({where:{requestId:r.id}}),injectedAudit=new Proxy(audit,{get(target,key){if(key==='logRequired')return async()=>{throw Error('Injected lifecycle audit failure')};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}});
  const dataOwnerContext=await lifecycle.context(manifest.actors.dataOwner,uc.id);assert.ok(dataOwnerContext.data.some(r=>r.tasks.some(t=>t.canAct&&t.id===ct.id)));checks.push('separate nominated Data Owner can discover and independently confirm their own scoped task');
  const broken=new AiLifecycleService(db,(lifecycle as any).authorization,(lifecycle as any).intake,(lifecycle as any).classification,(lifecycle as any).riskAssessment,(lifecycle as any).routing,(lifecycle as any).ids,injectedAudit);
  await assert.rejects(broken.decide(ct.assigneeUserId!,r.id,ct.id,{expectedVersion:confirmation.version,decision:'approve',justification:tag,evidenceIds:[evidenceId]}),/Injected lifecycle audit/);assert.equal(await db.aiLifecycleDecision.count({where:{requestId:r.id}}),beforeDecisions);assert.equal((await pending(r.id)).status,'confirmation');checks.push('audit failure rolls back effective configuration, intake revision, obligation, task and decision atomically');
  await decideAll(r.id);const effective=await lifecycle.context(author.id,uc.id);assert.equal((effective.effective.payload as any).objective_value,'B5 independently approved objective');assert.equal(await db.aiEffectiveConfiguration.count({where:{useCaseId:uc.id}}),2);assert.equal((await proof.read(author.id,'ai_lifecycle_request',r.id,new (class {page=1;pageSize=25;search=''})())).data[0].assurance,'demo_verified');checks.push('independent verification, required specialists, tier authority and Data Owner confirmation atomically activate immutable configuration with relevant verified proof');
  await assert.rejects(lifecycle.decide(ct.assigneeUserId!,r.id,ct.id,{expectedVersion:confirmation.version,decision:'approve',justification:tag,evidenceIds:[evidenceId]}),/changed/);assert.equal(await db.aiEffectiveConfiguration.count({where:{useCaseId:uc.id}}),2);checks.push('replayed completed decisions reject as conflicts without duplicating effective configuration or obligations');
  const originalCfg=await db.aiEffectiveConfiguration.findFirstOrThrow({where:{useCaseId:uc.id,sequence:1}});await assert.rejects(db.aiEffectiveConfiguration.update({where:{id:originalCfg.id},data:{tierCode:'MINIMAL'}}),/append-only/);await assert.rejects(db.aiLifecycleRequest.update({where:{id:r.id},data:{justification:'overwrite'}}),/immutable/);checks.push('database guards preserve original configurations and closed lifecycle history');
  const suspend=await lifecycle.propose(author.id,uc.id,{expectedVersion:effective.useCaseVersion,action:'suspend',justification:tag,assignments});await link(suspend.id);await decideAll(suspend.id);let c=await lifecycle.context(author.id,uc.id);assert.equal(c.state,'suspended');assert.equal(c.effectiveUseAllowed,false);assert.equal((await db.dataAsset.findUniqueOrThrow({where:{id:source.assetId!}})).isActive,true);checks.push('suspension blocks this use case without disabling a shared asset or hiding risk remediation');
  const resume=await lifecycle.propose(author.id,uc.id,{expectedVersion:c.useCaseVersion,action:'resume',justification:tag,assignments});await link(resume.id);await assert.rejects(lifecycle.decide(manifest.actors.executive,resume.id,(await pending(resume.id)).workflowCase.tasks[0].id,{expectedVersion:1,decision:'approve',justification:tag,evidenceIds:[evidenceId]}),/named active/);await assessAll(resume.id);await decideAll(resume.id);c=await lifecycle.context(author.id,uc.id);assert.equal(c.state,'active');assert.equal(c.effectiveUseAllowed,true);checks.push('resumption cannot skip fresh classification, competent risk reassessment and independent approval gates');
  const self=await lifecycle.propose(manifest.actors.officer,uc.id,{expectedVersion:c.useCaseVersion,action:'suspend',justification:tag,assignments});await link(self.id);r=await pending(self.id);assert.equal(r.workflowCase.tasks[0].assigneeUserId,manifest.actors.officer);assert.equal((await lifecycle.context(manifest.actors.officer,uc.id)).data.find(request=>request.id===self.id)!.tasks[0].canAct,false);await assert.rejects(lifecycle.decide(manifest.actors.officer,r.id,r.workflowCase.tasks[0].id,{expectedVersion:r.version,decision:'approve',justification:tag,evidenceIds:[evidenceId]}),/independent/);await lifecycle.withdraw(manifest.actors.officer,r.id,r.version,'Withdraw the denied self-approval diagnostic');checks.push('an eligible named tier authority cannot approve its own lifecycle proposal and sees no approval control');
  c=await lifecycle.context(author.id,uc.id);const stale=await lifecycle.propose(author.id,uc.id,{expectedVersion:c.useCaseVersion,action:'suspend',justification:tag,assignments}),risk=await db.aiRisk.findFirstOrThrow({where:{useCaseId:uc.id}});await db.aiRisk.update({where:{id:risk.id},data:{version:{increment:1}}});await link(stale.id);r=await pending(stale.id);await assert.rejects(lifecycle.decide(r.workflowCase.tasks[0].assigneeUserId!,r.id,r.workflowCase.tasks[0].id,{expectedVersion:r.version,decision:'approve',justification:tag,evidenceIds:[evidenceId]}),/risk, ownership or obligations changed/);await lifecycle.withdraw(author.id,r.id,r.version,'Withdraw stale pins without changing effective use');checks.push('concurrent risk changes invalidate proposal pins and remain recoverable through native withdrawal');
  for(const decision of ['return','reject'] as const){c=await lifecycle.context(author.id,uc.id);const proposed=await lifecycle.propose(author.id,uc.id,{expectedVersion:c.useCaseVersion,action:'suspend',justification:tag,assignments});await link(proposed.id);r=await pending(proposed.id);t=r.workflowCase.tasks[0];await lifecycle.decide(t.assigneeUserId!,r.id,t.id,{expectedVersion:r.version,decision,justification:tag,evidenceIds:[evidenceId]});const rejected=await lifecycle.context(author.id,uc.id);assert.equal(rejected.state,'active');assert.equal(rejected.effectiveUseAllowed,true);assert.equal((await pending(r.id)).status,decision==='return'?'returned':'rejected');assert.equal(await db.workflowTask.count({where:{caseId:r.workflowCaseId,status:'pending'}}),0);}checks.push('independently returned and rejected proposals preserve approved use, proof and history without stranded pending work');
  c=await lifecycle.context(author.id,uc.id);const retire=await lifecycle.propose(author.id,uc.id,{expectedVersion:c.useCaseVersion,action:'retire',justification:tag,assignments});await link(retire.id);await decideAll(retire.id);c=await lifecycle.context(author.id,uc.id);assert.equal(c.state,'retired');assert.equal(c.effectiveUseAllowed,false);assert.ok(c.total>=6);assert.equal((await db.aiApprovalObligation.findMany({where:{useCaseId:uc.id}})).every(o=>o.operationalState==='retired'),true);assert.equal(await db.aiRisk.count({where:{useCaseId:uc.id}}),1);assert.equal(await db.aiIntakeRevision.count({where:{useCaseId:uc.id}}),2);checks.push('retirement archives business work and obligations while preserving risk, intake and decision history');
  const live=await risks.visibility(manifest.actors.officer),history=await risks.visibility(manifest.actors.officer,db,true);assert.equal(await db.aiRisk.count({where:{AND:[live.where,{useCaseId:uc.id}]}}),0);assert.equal(await db.aiRisk.count({where:{AND:[history.where,{useCaseId:uc.id}]}}),1);await lifecycle.context(manifest.actors.auditor,uc.id);checks.push('retired resources leave active risk operations but retain scoped authorized historical and audit reads');
  assert.deepEqual(await db.dataAsset.findUniqueOrThrow({where:{id:source.assetId!}}),assetBefore);assert.equal((await db.aiUseCase.findUniqueOrThrow({where:{id:source.id}})).version,source.version);const chain=await audit.verifyChain();assert.equal(chain.valid,true);assert.equal(chain.truncated,false);checks.push('shared asset and original registered fixture remain unchanged; required native audit chain is complete');
  passed=true;
 }catch(cause){error=cause instanceof Error?cause.message:String(cause);throw cause;}finally{if(evidenceId){const e=await db.ndiEvidence.findUnique({where:{id:evidenceId}});if(e?.status==='approved')await files.revoke(evidenceId,reviewer);}await app.close();if(process.env.DGOP_LIFECYCLE_RECEIPT)writeFileSync(process.env.DGOP_LIFECYCLE_RECEIPT,JSON.stringify({startedAt,finishedAt:new Date().toISOString(),database:url.pathname.slice(1),passed,error,checks:checks.length,scenarios:checks,diagnosticUseCaseId:ucId,evidenceId,fixtureManifestSha256:require('node:crypto').createHash('sha256').update(readFileSync(process.env.DGOP_DEMO_MANIFEST!)).digest('hex')},null,2)+'\n');}
 console.log(JSON.stringify({passed,checks:checks.length,scenarios:checks}));
}
main().catch(e=>{console.error(e);process.exitCode=1;});
