import { AiCategoryControlsService } from '../src/ai-governance/ai-category-controls.service';
import { testCycleA } from './ai-cycle-a.integration';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { INestApplication } from '@nestjs/common';
import { Prisma, PrismaClient } from '@prisma/client';
import { JwtService } from '@nestjs/jwt';
import { AuditService } from '../src/audit/audit.service';
import { PrismaService } from '../src/prisma/prisma.service';
import { AiSourceCorrectionsService } from '../src/ai-governance/ai-source-corrections.service';
import { AiLibrarySourceService } from '../src/ai-governance/ai-library-source.service';
import { AiMigrationPreviewService } from '../src/ai-governance/ai-migration-preview.service';
import { AiRiskLibraryService } from '../src/ai-governance/ai-risk-library.service';
import { AiLibraryControlLinksService } from '../src/ai-governance/ai-library-control-links.service';
import { AiControlDomainsService } from '../src/ai-governance/ai-control-domains.service';
import { AiRiskInitiationService } from '../src/ai-governance/ai-risk-initiation.service';
import { AiRiskIntakeService } from '../src/ai-governance/ai-risk-intake.service';
import { AiRiskAssessmentService } from '../src/ai-governance/ai-risk-assessment.service';
import { AiWorkflowRoutingService, AIRS_TEMPLATE_CODE, AIRS_STAGE } from '../src/ai-governance/ai-workflow-routing.service';
import { AiTreatmentService } from '../src/ai-governance/ai-treatment.service';
import { AiAssetRiskService } from '../src/ai-governance/ai-asset-risk.service';
import { AiAuthorizationService } from '../src/ai-governance/ai-authorization.service';
import { governanceDigest } from '../src/ai-governance/ai-governance-ledger';
import { computeInherentRisk, jsonRecord, RISK_DIMENSIONS } from '../src/ai-governance/ai-risk-scoring';
import { PreviewRow } from '../src/ai-governance/ai-migration-preview';
export async function testLibraryControlsAsset(db:PrismaClient,app:INestApplication,previewId:string,f:{officerId:string;auditorId:string;dmoId:string;riskOwnerId:string;evidenceId:string}){
 const corrections=app.get(AiSourceCorrectionsService),source=app.get(AiLibrarySourceService),previews=app.get(AiMigrationPreviewService),library=app.get(AiRiskLibraryService),links=app.get(AiLibraryControlLinksService),controls=app.get(AiControlDomainsService),intake=app.get(AiRiskIntakeService),initiation=app.get(AiRiskInitiationService),assets=app.get(AiAssetRiskService),treatment=app.get(AiTreatmentService),routing=app.get(AiWorkflowRoutingService),context=await corrections.context(f.officerId,previewId),evidenceIds=[f.evidenceId],reason={justification:'Isolated engineering fixture; no live migration or source activation',evidenceIds};
 const rows=(await previews.get(f.officerId,previewId)).report['rows'] as PreviewRow[],selected=rows.filter(r=>r.kind==='library'&&['AIRL-065','AIRL-066'].includes(r.sourceRef)),entries=selected.flatMap(r=>[{rowKey:r.key,field:'titleEn',value:'Engineering title '+r.sourceRef},...['dev_stage','ethics_principle','risk_category'].map(field=>({rowKey:r.key,field,value:context.references.find(v=>v.listCode===context.rules['library'][field].listCode)!.values[0].code}))]);
 const v=await corrections.propose(f.officerId,previewId,{...reason,expectedRound:context.latestRound,requestKey:randomUUID(),entries});await corrections.review(f.dmoId,v.id,{...reason,expectedDigest:v.digest,outcome:'approve'});const snapshot=await corrections.capture(f.officerId,v.id,{...reason,expectedDigest:v.digest}),dto={...reason,requestKey:randomUUID(),rowKeys:selected.map(r=>r.key),expectedDigest:snapshot.digest};
 const before=await db.aiRiskLibraryEntry.count(),failedAudit={logRequired:async()=>{throw new Error('Injected library source audit failure');}} as unknown as AuditService,failed=new AiLibrarySourceService(db as PrismaService,corrections,previews,library,failedAudit);
 await assert.rejects(source.propose(f.auditorId,snapshot.id,dto),/explicit eligible/);await assert.rejects(source.propose(f.officerId,snapshot.id,{...dto,rowKeys:[selected[0].key,rows.find(r=>r.kind==='risk')!.key]}),/prepared nonsample/);assert.equal(await db.aiLibrarySourceImport.count(),0);assert.equal(await db.aiRiskLibraryEntry.count(),before);
 await assert.rejects(failed.propose(f.officerId,snapshot.id,dto),/Injected/);assert.equal(await db.aiRiskLibraryEntry.count(),before);assert.equal(await db.aiLibrarySourceImport.count(),0);
 const batches=await Promise.all([source.propose(f.officerId,snapshot.id,dto),source.propose(f.officerId,snapshot.id,dto)]),batch=batches[0];assert.equal(batch.id,batches[1].id);assert.equal(batches.filter(b=>b.created).length,1);assert.equal(batch.items.length,2);assert.equal(await db.aiRiskLibraryEntry.count(),before+2);await assert.rejects(source.propose(f.officerId,snapshot.id,{...dto,justification:'Changed replay'}),/another proposal/);await assert.rejects(source.propose(f.officerId,snapshot.id,{...dto,requestKey:randomUUID()}),/already has/);
 const recon=await source.reconcile(f.auditorId,batch.id);assert.equal(recon.selectedLibraryZeroDiff,true);assert.equal(recon.publishedCount,0);assert.equal(recon.overallZeroDiff,null);assert.equal(recon.productionReady,false);assert.equal((await source.list(f.auditorId,snapshot.id,1,1)).total,1);assert.ok((await source.export(f.auditorId,batch.id,'csv')).startsWith('\uFEFF'));await assert.rejects(db.aiLibrarySourceImport.delete({where:{id:batch.id}}),/append-only/);await assert.rejects(db.aiLibrarySourceItem.update({where:{id:batch.items[0].id},data:{sourceRef:'AIRL-999'}}),/append-only/);
 for(const item of batch.items){await assert.rejects(library.publish(f.officerId,item.libraryVersionId,reason.justification,evidenceIds),/explicit eligible/);await library.publish(f.dmoId,item.libraryVersionId,reason.justification,evidenceIds);}assert.equal((await source.reconcile(f.auditorId,batch.id)).publishedCount,2);
 const libraryId=batch.items[0].libraryVersionId,cv=(await controls.list(f.officerId)).rows[0];assert.ok(cv);await assert.rejects(controls.pins(db,[cv.versionId,cv.versionId]),/unique/);await assert.rejects(controls.pins(db,[randomUUID()]),/current published/);
 const failedLinks=new AiLibraryControlLinksService(db as PrismaService,app.get(AiAuthorizationService),library,controls,failedAudit,app.get(AiCategoryControlsService));await assert.rejects(failedLinks.propose(f.officerId,libraryId,{...reason,expectedRound:0,controlVersionIds:[cv.versionId]}),/Injected/);assert.equal(await db.aiLibraryControlLinkVersion.count(),0);
 const mapping=await links.propose(f.officerId,libraryId,{...reason,expectedRound:0,controlVersionIds:[cv.versionId]});await assert.rejects(links.review(f.officerId,mapping.id,{...reason,outcome:'approve',expectedDigest:mapping.digest}),/explicit eligible/);await assert.rejects(db.aiLibraryControlLinkReview.create({data:{...reason,versionId:mapping.id,outcome:'approve',actorId:f.officerId}}),/independent/i);await assert.rejects(failedLinks.review(f.dmoId,mapping.id,{...reason,outcome:'approve',expectedDigest:mapping.digest}),/Injected/);const approved=await links.review(f.dmoId,mapping.id,{...reason,outcome:'approve',expectedDigest:mapping.digest});await assert.rejects(db.aiLibraryControlLinkVersion.delete({where:{id:mapping.id}}),/append-only/);await assert.rejects(db.aiLibraryControlLinkReview.delete({where:{id:approved.id}}),/append-only/);
 const parent=(await initiation.context(f.riskOwnerId)).parents[0];assert.ok(parent);const draft=await initiation.create(f.riskOwnerId,{useCaseId:parent.id,libraryVersionId:libraryId,initiationKey:randomUUID(),justification:reason.justification}),risk=await db.aiRisk.findUniqueOrThrow({where:{id:draft.id}});assert.equal(risk.controlPins,null);assert.equal(jsonRecord(risk.suggestedControlPins)['mappingVersionId'],mapping.id);await assert.rejects(db.aiRisk.update({where:{id:risk.id},data:{suggestedControlPins:{}}}),/immutable provenance/);
 const riskRefs=await intake.lookups(f.riskOwnerId),input={title:'Engineering control-tag risk',cause:'Fixture cause',event:'Fixture event',effect:'Fixture effect',current_controls:'Fixture described controls; not a production claim',third_party_involved:false,evidence:evidenceIds,...Object.fromEntries(riskRefs.lists.map(l=>[l.field,l.values[0].code])),control_domain_version_ids:[cv.versionId]};const saved=await intake.save(f.riskOwnerId,risk.id,risk.version,input);assert.equal((await db.aiRisk.findUniqueOrThrow({where:{id:risk.id}})).controlPins instanceof Array,true);const submitted=await intake.submit(f.riskOwnerId,risk.id,saved.version);await assert.rejects(db.aiRisk.update({where:{id:risk.id},data:{controlPins:[]}}),/immutable/);assert.equal(await db.aiAssessmentRound.count({where:{riskId:risk.id}}),0);
 // Synthetic native prerequisites keep tests independent of old assessment gates. Production writes use the inherited assessment/response workflow.
 const config=await app.get(AiRiskAssessmentService).configuration(),calculated=computeInherentRisk(1,RISK_DIMENSIONS.map(dimension=>({dimension,value:2,justification:'Engineering dimension fixture'})),config),inherent=await db.aiAssessmentRound.create({data:{riskId:risk.id,useCaseId:risk.useCaseId,kind:'inherent',round:1,engineVersion:'isolated-engineering-fixture',ruleReferenceVersionId:config.referenceVersions.R_LEVEL,inputs:{configuration:config},result:calculated,createdBy:f.riskOwnerId}});
 const adoptTask=await routing.createStageTask(db as PrismaService,risk.workflowCaseId!,AIRS_STAGE.adoption,new Date(),{templateCode:AIRS_TEMPLATE_CODE,assigneeUserId:f.officerId,formDataJson:{assessmentId:inherent.id}});await db.aiRiskAssessmentDecision.create({data:{...reason,assessmentId:inherent.id,taskId:adoptTask.id,kind:'adoption',decision:'approve',actorId:f.officerId,actorRoleCode:'AI_GOVERNANCE_OFFICER'}});
 const proposalTask=await routing.createStageTask(db as PrismaService,risk.workflowCaseId!,AIRS_STAGE.proposal,new Date(),{templateCode:AIRS_TEMPLATE_CODE,assigneeUserId:f.riskOwnerId,formDataJson:{assessmentId:inherent.id}}),strategy=await db.governedReferenceVersion.findFirstOrThrow({where:{listCode:'R_STRATEGY',state:'published'}}),response=await db.aiRiskResponse.create({data:{riskId:risk.id,assessmentId:inherent.id,round:1,proposalTaskId:proposalTask.id,referenceVersionId:strategy.id,strategyCode:'MITIGATE',payload:{},submittedBy:f.riskOwnerId}}),responseTask=await routing.createStageTask(db as PrismaService,risk.workflowCaseId!,AIRS_STAGE.response,new Date(),{templateCode:AIRS_TEMPLATE_CODE,formDataJson:{responseId:response.id}});await db.aiRiskResponseDecision.create({data:{...reason,responseId:response.id,taskId:responseTask.id,kind:'officer',decision:'approve',actorId:f.officerId,actorRoleCode:'AI_GOVERNANCE_OFFICER'}});await routing.createStageTask(db as PrismaService,risk.workflowCaseId!,'airs-treatment-plan',new Date(),{templateCode:AIRS_TEMPLATE_CODE,assigneeUserId:f.riskOwnerId,formDataJson:{responseId:response.id}});
 const model=await db.user.findUniqueOrThrow({where:{email:'AI_MODEL_OWNER@phase3b.test'}}),actionDto={expectedVersion:submitted.version,title:'Engineering tagged action',description:'Engineering action fixture',actionType:'PREVENTIVE' as const,priorityCode:'HIGH',assigneeUserId:model.id,targetDate:new Date(Date.now()+40*86400000).toISOString().slice(0,10),evidenceRequired:'Engineering evidence',evidenceIds,taskType:'evidence_upload',controlVersionIds:[cv.versionId]};const action=await treatment.save(f.riskOwnerId,risk.id,actionDto);assert.equal((jsonRecord((await db.aiTreatmentAction.findUniqueOrThrow({where:{id:action.actionId}})).planData)['controlDomains'] as Array<{versionId:string}>)[0].versionId,cv.versionId);
 const controlVersion=await db.aiControlDomainVersion.findUniqueOrThrow({where:{id:cv.versionId},include:{entry:true}}),content=jsonRecord(controlVersion.content),nextControl=await corrections.proposeControl(f.officerId,previewId,{...reason,sourceRowKey:controlVersion.sourceRowKey,controlCode:controlVersion.entry.controlCode,expectedRound:controlVersion.round,titleEn:String(content['titleEn'])+' revision',titleAr:String(content['titleAr']),dimensionCodes:(controlVersion.dimensionPins as Array<{code:string}>).map(p=>p.code)});await corrections.publishControl(f.dmoId,nextControl.id,{...reason,expectedDigest:nextControl.digest});await assert.rejects(treatment.submit(f.riskOwnerId,risk.id,action.version),/current published/);await assert.rejects(initiation.create(f.riskOwnerId,{useCaseId:parent.id,libraryVersionId:libraryId,initiationKey:randomUUID(),justification:reason.justification}),/current published/);
 const updated=await treatment.save(f.riskOwnerId,risk.id,{...actionDto,expectedVersion:action.version,controlVersionIds:[nextControl.id]},action.actionId);const plan=await treatment.submit(f.riskOwnerId,risk.id,updated.version),reviewContext=await treatment.context(f.officerId,risk.id);await treatment.review(f.officerId,risk.id,reviewContext.taskId!,{expectedVersion:plan.version,decision:'approve',...reason});const finalAction=await db.aiTreatmentAction.findUniqueOrThrow({where:{id:action.actionId},include:{workflowTask:true}});assert.equal((jsonRecord(jsonRecord(finalAction.workflowTask!.formDataJson)['actionPlan'])['controlDomains'] as Array<{versionId:string}>)[0].versionId,nextControl.id);await assert.rejects(db.aiTreatmentAction.update({where:{id:finalAction.id},data:{planData:{controlDomains:[]},version:{increment:1}}}),/frozen/);
 await treatment.execute(model.id,risk.id,action.actionId,{expectedVersion:(await db.aiRisk.findUniqueOrThrow({where:{id:risk.id}})).version,completionPct:100,...reason});
 const residualCoordinator=await routing.createStageTask(db as PrismaService,risk.workflowCaseId!,'airs-residual-assessment',new Date(),{templateCode:AIRS_TEMPLATE_CODE,assigneeUserId:f.riskOwnerId,assigneeRoleCode:'AI_RISK_OWNER',formDataJson:{responseId:response.id}}),controlEffectiveness=await db.governedReferenceVersion.findFirstOrThrow({where:{listCode:'R_CTRLEFF',state:'published'},include:{values:true}});
 const residual=await db.aiAssessmentRound.create({data:{riskId:risk.id,useCaseId:risk.useCaseId,kind:'residual',round:1,engineVersion:'isolated-engineering-fixture',ruleReferenceVersionId:config.referenceVersions.R_LEVEL,inputs:{inherentAssessmentId:inherent.id,responseId:response.id,planId:plan.planId,coordinatorTaskId:residualCoordinator.id,currentControls:'Engineering completed controls',controlEffectiveness:{referenceVersionId:controlEffectiveness.id,code:controlEffectiveness.values[0].code}},result:calculated,createdBy:f.riskOwnerId}}),linked=await db.aiUseCase.findUniqueOrThrow({where:{id:risk.useCaseId}}),assetId=linked.assetId!;
 const native=await db.permission.upsert({where:{resource_action:{resource:'data_assets',action:'view'}},create:{resource:'data_assets',action:'view',descriptionEn:'Existing native asset read'},update:{}});for(const code of ['AI_GOVERNANCE_OFFICER','auditor','AI_RISK_OWNER','AI_EXECUTIVE_TEAM']){const role=await db.role.findUniqueOrThrow({where:{code}});await db.rolePermission.upsert({where:{roleId_permissionId:{roleId:role.id,permissionId:native.id}},create:{roleId:role.id,permissionId:native.id},update:{}});}
 const register=await assets.register(f.officerId,assetId,1,100);assert.equal(register.rows.find(r=>r.id===risk.id)!.residualScore,2);const summary=await assets.summary(f.officerId,assetId);assert.equal(summary.registeredRiskCount,register.total);assert.ok(summary.approvedActionCount>=1);assert.equal((await assets.actions(f.auditorId,assetId,1,1)).rows.length,1);assert.ok((await assets.history(f.auditorId,assetId,risk.id)).rows.some(a=>a.id===residual.id));await assert.rejects(assets.history(f.officerId,assetId,randomUUID()),/Linked permitted/);await assert.rejects(assets.register(f.officerId,assetId,1,101),/page size/);await assert.rejects(assets.actions(f.officerId,assetId,1,20,'injected'),/Unknown/);assert.equal((await assets.reviews(f.officerId,assetId)).page,1);
 await db.aiAssessmentRound.create({data:{riskId:risk.id,useCaseId:risk.useCaseId,kind:'inherent',round:2,engineVersion:'isolated-engineering-fixture',ruleReferenceVersionId:config.referenceVersions.R_LEVEL,inputs:{configuration:config},result:calculated,createdBy:f.riskOwnerId}});assert.equal((await assets.register(f.officerId,assetId,1,100)).rows.find(r=>r.id===risk.id)!.residualScore,null);
 const executive=await db.user.findFirstOrThrow({where:{userRoles:{some:{role:{is:{code:'AI_EXECUTIVE_TEAM'}}}},isActive:true}});assert.equal((await assets.summary(executive.id,assetId)).aggregateOnly,true);await assert.rejects(assets.register(executive.id,assetId),/aggregate only/);await assert.rejects(assets.history(executive.id,assetId,risk.id),/aggregate only/);
 const officerRole=await db.role.findUniqueOrThrow({where:{code:'AI_GOVERNANCE_OFFICER'}}),excluded=await db.roleDataScope.create({data:{roleId:officerRole.id,scopeType:'data_domain',refId:randomUUID()}});try{await assert.rejects(assets.summary(f.officerId,assetId),/scoped/);}finally{await db.roleDataScope.delete({where:{id:excluded.id}});}
 const headers={authorization:'Bearer '+app.get(JwtService).sign({sub:f.officerId,tokenVersion:0,roles:['system_admin']}),'content-type':'application/json'},base=await app.getUrl();assert.equal((await fetch(base+'/api/ai/assets/'+assetId+'/risk-summary',{headers})).status,200);assert.equal((await fetch(base+'/api/ai/assets/'+assetId+'/risk-summary')).status,401);assert.equal((await fetch(base+'/api/ai/library-sources/snapshots/'+snapshot.id+'/proposals',{method:'POST',headers,body:JSON.stringify({...dto,requestKey:randomUUID(),productionReady:true,mode:'COMMIT'})})).status,400);assert.equal((await fetch(base+'/api/ai/library-sources/imports/'+batch.id+'/export?format=csv',{headers})).headers.get('content-type'),'text/csv; charset=utf-8');assert.equal(governanceDigest(snapshot.report),snapshot.digest);
 await testCycleA(db,app,f,{snapshotId:snapshot.id,libraryId,controlId:nextControl.id,parentId:parent.id,riskId:risk.id});
 console.log('Twenty packets 5G–5Z passed: atomic source AIRL batches/replay/provenance/independent publication/subset reconciliation/exports; governed ISO library links and explicit risk/action tags/stale pins/native frozen execution; standard Asset 360 scoped register/current residual pairing/mitigation/history/reviews and executive aggregate privacy/HTTP guards.');
}
