import { testSourceCorrections } from './ai-source-corrections.integration';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { INestApplication } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';
import { JwtService } from '@nestjs/jwt';
import { AiMigrationPreviewService } from '../src/ai-governance/ai-migration-preview.service';
import { parseMigrationWorkbook, AI_MIGRATION_SOURCES, workbookArchive } from '../src/ai-governance/ai-migration-workbook';
import { buildMigrationPreview, exactReference, PreviewEnvironment, PreviewRow, sourceDecimalSum } from '../src/ai-governance/ai-migration-preview';
import { RISK_DIMENSIONS, RISK_DIMENSION_ROLES, jsonRecord } from '../src/ai-governance/ai-risk-scoring';
import { AiRiskIntakeService } from '../src/ai-governance/ai-risk-intake.service';
import { AiRiskAssessmentService } from '../src/ai-governance/ai-risk-assessment.service';
import { AiAuthorizationService } from '../src/ai-governance/ai-authorization.service';
import { ScopeService } from '../src/access/scope.service';
import { AuditService } from '../src/audit/audit.service';
import { PrismaService } from '../src/prisma/prisma.service';
import { governanceDigest } from '../src/ai-governance/ai-governance-ledger';

function sourceFixture(){return AI_MIGRATION_SOURCES.map(s=>parseMigrationWorkbook(readFileSync(resolve(__dirname,'../../../storage/ai-sources',s.file)),s.source,s.sha256));}
function envFixture():PreviewEnvironment{
 const anchor={en:'Engineering fixture',ar:'مرساة اختبار'},bands=[{code:'LOW',minScore:1,maxScore:2,severityCode:'P4',labelEn:'Low',labelAr:'منخفض'},{code:'MEDIUM',minScore:3,maxScore:6,severityCode:'P3',labelEn:'Medium',labelAr:'متوسط'},{code:'HIGH',minScore:8,maxScore:12,severityCode:'P2',labelEn:'High',labelAr:'مرتفع'},{code:'CRITICAL',minScore:16,maxScore:16,severityCode:'P1',labelEn:'Critical',labelAr:'كارثي'}];
 return {references:[{listCode:'R_SDAIA_TIER',id:'tier-fixture',values:[{code:'HIGH',labelEn:'High',labelAr:'مخاطر عالية',metadata:{minScore:4,maxScore:5,automatic:true}},{code:'LIMITED',labelEn:'Limited',labelAr:'مخاطر محدودة',metadata:{minScore:3,maxScore:3,automatic:true}},{code:'MINIMAL',labelEn:'Minimal',labelAr:'مخاطر قليلة أو معدومة',metadata:{minScore:1,maxScore:2,automatic:true}}]}],people:[],units:[],scoring:{referenceVersions:{R_SCORE14:'s',R_IMPD:'d',R_LEVEL:'b'},scores:[1,2,3,4].map(score=>({code:String(score),score,labelEn:String(score),labelAr:String(score),anchors:{likelihood:anchor,impact:anchor}})),dimensions:RISK_DIMENSIONS.map((dimension,i)=>({code:dimension,dimension,tieBreakOrder:i+1,assessorRoleCode:RISK_DIMENSION_ROLES[dimension],labelEn:dimension,labelAr:dimension})),bands}};
}
export function testMigrationSourceTransform(){
 assert.equal(sourceDecimalSum('0.1','0.2'),'0.3');assert.equal(sourceDecimalSum('1000','-1.25e2'),'875');assert.equal(sourceDecimalSum('1e-6','0.000009'),'0.00001');assert.equal(sourceDecimalSum('0.60000000000000001','0.4'),'1.00000000000000001');
 const books=sourceFixture(),env=envFixture(),report=buildMigrationPreview(books,env),counts=report.reconciliation.counts;
 assert.equal(books[0].sheets.length,13);assert.equal(books[1].sheets.length,4);assert.equal(counts['library'],66);assert.equal(counts['control'],10);assert.equal(counts['usecase'],1);assert.equal(counts['risk'],10);assert.equal(counts['action'],15);assert.equal(counts['assessment'],10);assert.equal(counts['classification'],1);assert.equal(counts['intake'],1);
 assert.equal(report.reconciliation.sourceCount,report.reconciliation.preparedCount+report.reconciliation.quarantinedCount);assert.equal(report.reconciliation.loadedCount,0);assert.equal(report.reconciliation.zeroDiff,null);assert.equal(report.reconciliation.targetCompared,false);assert.equal(report.reconciliation.targetNumericTotals,null);assert.equal(report.reconciliation.productionReady,false);assert.equal(report.reconciliation.pilot.missingRefs.length,19);
 const risk=report.rows.find(r=>r.kind==='risk'&&r.sourceRef==='AIR-001')!,action=report.rows.find(r=>r.kind==='action'&&r.sourceRef==='ACT-001')!,library=report.rows.find(r=>r.kind==='library')!,classification=report.rows.find(r=>r.kind==='classification')!;
 assert.equal(jsonRecord(risk.prepared['inherentPreview'])['score'],16);assert.equal(risk.prepared['residualScorePreview'],2);assert.equal(action.prepared['completionPct'],60);assert.equal(action.prepared['targetDate'],'2026-08-01T00:00:00.000Z');assert.equal(library.sourceRef,'AIRL-001');assert.equal(library.prepared['titleEn'],undefined);assert.equal(library.prepared['suggestionsOnly'],true);assert.equal(risk.prepared['authorityImported'],false);assert.ok(risk.raw.P.formula);assert.equal(risk.raw.P.value,16);assert.equal(classification.prepared['maxScore'],5);assert.equal(jsonRecord(classification.prepared['proposedTier'])['code'],'HIGH');assert.ok(classification.issues.includes('LEGACY_CLASSIFICATION_APPROVAL_REVIEW_REQUIRED'));
 assert.ok(report.rows.filter(r=>['usecase','risk','assessment','action','classification'].includes(r.kind)).every(r=>r.sample));assert.ok(report.rows.find(r=>r.kind==='intake')!.issues.includes('EMPTY_INTAKE_FORM'));
 assert.equal(exactReference('العدالة','R_ETHICS',env).issue,'REFERENCE_VERSION:R_ETHICS');const refs={...env,references:[{listCode:'R_ETHICS',id:'one',values:[{code:'FAIR',labelAr:'العدالة',labelEn:'Fairness'}]}]};assert.equal(exactReference('العدالة','R_ETHICS',refs).value?.code,'FAIR');assert.equal(exactReference(' العدالة','R_ETHICS',refs).issue,'UNKNOWN_LABEL:R_ETHICS');assert.equal(exactReference('عدالة','R_ETHICS',refs).issue,'UNKNOWN_LABEL:R_ETHICS');assert.equal(exactReference('العدالة','R_ETHICS',{...refs,references:[...refs.references,...refs.references]}).issue,'REFERENCE_VERSION:R_ETHICS');assert.equal(exactReference('العدالة','R_ETHICS',{...refs,references:[{...refs.references[0],values:[...refs.references[0].values,{code:'OTHER',labelAr:'العدالة',labelEn:'Different'}]}]}).issue,'AMBIGUOUS_LABEL:R_ETHICS');
 const clone=structuredClone(books),riskSheet=clone[0].sheets.find(s=>s.name==='سجل المخاطر')!,actions=clone[0].sheets.find(s=>s.name==='خطة المعالجة')!;riskSheet.cells.B5.value='AI-999';riskSheet.cells.A6.value='AIR-001';actions.cells.K5.value=60;actions.cells.K5.numberFormat='0';const invalid=buildMigrationPreview(clone,env);
 assert.ok(invalid.rows.find(r=>r.kind==='risk'&&r.row===5)!.issues.includes('ORPHAN_OR_AMBIGUOUS_PARENT'));assert.ok(invalid.rows.find(r=>r.kind==='risk'&&r.row===6)!.issues.includes('DUPLICATE_SOURCE_ID'));assert.ok(invalid.rows.find(r=>r.kind==='action'&&r.row===5)!.issues.includes('COMPLETION_UNIT_OR_RANGE_INVALID'));assert.ok(invalid.rows.find(r=>r.kind==='action'&&r.row===5)!.issues.includes('ORPHAN_OR_AMBIGUOUS_PARENT'));
 const bytes=readFileSync(resolve(__dirname,'../../../storage/ai-sources',AI_MIGRATION_SOURCES[0].file));assert.throws(()=>parseMigrationWorkbook(bytes,'risk','0'.repeat(64)),/checksum differs/);assert.throws(()=>workbookArchive(Buffer.alloc(22)),/directory/);const oversized=Buffer.from(bytes),end=oversized.length-22;oversized.writeUInt16LE(201,end+10);assert.throws(()=>workbookArchive(oversized),/limits/);const corrupt=Buffer.from(bytes),first=corrupt.readUInt32LE(end+16);corrupt.writeUInt32LE(0,first+16);assert.throws(()=>workbookArchive(corrupt),/checksum/);
 assert.equal(governanceDigest(books),governanceDigest(sourceFixture()));console.log('AI retained-source parsing, exact resolution, scoring, sample, orphan and unit checks passed');
}

export async function testMigrationPreviews(db:PrismaClient,app:INestApplication,f:{officerId:string;auditorId:string;dmoId:string;riskOwnerId:string;evidenceId:string}){
 testMigrationSourceTransform();const service=app.get(AiMigrationPreviewService),evidenceIds=[f.evidenceId],dto={requestKey:randomUUID(),justification:'Isolated engineering source-preparation proposal',evidenceIds};
 const baseline={risks:await db.aiRisk.count(),library:await db.aiRiskLibraryEntry.count(),assets:await db.dataAsset.count(),cases:await db.workflowCase.count(),actions:await db.aiTreatmentAction.count()};
 assert.equal((await service.context(f.officerId)).canPropose,true);assert.equal((await service.context(f.auditorId)).canPropose,false);assert.equal((await service.context(f.dmoId)).canReview,true);await assert.rejects(service.context(f.riskOwnerId),/governance role/);await assert.rejects(service.create(f.auditorId,dto),/explicit eligible/);
 const results=await Promise.all([service.create(f.officerId,dto),service.create(f.officerId,dto)]),id=results[0].id;assert.equal(results[1].id,id);assert.equal(results.filter(r=>r.created).length,1);await assert.rejects(service.create(f.officerId,{...dto,justification:'Changed body'}),/another proposal/);
 const saved=await service.get(f.auditorId,id),report=saved.report,rows=report['rows'] as PreviewRow[];assert.equal(saved.digest,governanceDigest(report));assert.equal(jsonRecord(report['reconciliation'])['loadedCount'],0);assert.equal(saved.productionReady,false);assert.equal((await service.list(f.auditorId,1,1)).rows[0].id,id);assert.ok((await service.export(f.auditorId,id,'json')).includes('VALIDATE_ONLY'));assert.ok((await service.export(f.auditorId,id,'csv')).startsWith('\uFEFF'));await assert.rejects(service.list(f.officerId,1,101),/pagination/);await assert.rejects(service.export(f.officerId,id,'xlsx'),/JSON or CSV/);
 await assert.rejects(db.aiMigrationPreview.update({where:{id},data:{justification:'Tampered'}}),/append-only/);await assert.rejects(db.aiMigrationPreview.delete({where:{id}}),/append-only/);
 const failedAudit={logRequired:async()=>{throw new Error('Injected source preparation audit failure');}} as unknown as AuditService,failed=new AiMigrationPreviewService(db as PrismaService,app.get(AiAuthorizationService),app.get(AiRiskIntakeService),app.get(ScopeService),app.get(AiRiskAssessmentService),failedAudit),before=await db.aiMigrationPreview.count();await assert.rejects(failed.create(f.officerId,{...dto,requestKey:randomUUID()}),/Injected/);assert.equal(await db.aiMigrationPreview.count(),before);
 const q=rows.find(r=>r.status==='quarantined')!,disposition={rowKey:q.key,outcome:'defer',expectedDigest:saved.digest,justification:'Withheld pending documented source correction',evidenceIds},review={outcome:'accept',expectedDigest:saved.digest,justification:'Independent review of preparation, not load authorization',evidenceIds};
 await assert.rejects(service.review(f.dmoId,id,review),/Every quarantined/);await assert.rejects(service.disposition(f.auditorId,id,disposition),/explicit eligible/);await assert.rejects(service.disposition(f.officerId,id,{...disposition,rowKey:'unknown'}),/quarantined row/);await assert.rejects(service.disposition(f.officerId,id,{...disposition,expectedDigest:'0'.repeat(64)}),/changed/);await assert.rejects(failed.disposition(f.officerId,id,disposition),/Injected/);assert.equal(await db.aiMigrationDisposition.count({where:{previewId:id}}),0);
 const d=await service.disposition(f.officerId,id,disposition);await assert.rejects(service.disposition(f.officerId,id,disposition),/immutable/);await assert.rejects(db.aiMigrationDisposition.delete({where:{id:d.id}}),/append-only/);
 const officerRole=await db.role.findUniqueOrThrow({where:{code:'AI_GOVERNANCE_OFFICER'}}),scope=await db.roleDataScope.create({data:{roleId:officerRole.id,scopeType:'data_domain',refId:randomUUID()}});try{await assert.rejects(service.get(f.officerId,id),/full organization/);}finally{await db.roleDataScope.delete({where:{id:scope.id}});}
 // Populate remaining documented dispositions as isolated DB fixtures, then exercise the public review service.
 await db.aiMigrationDisposition.createMany({data:rows.filter(r=>r.status==='quarantined'&&r.key!==q.key).map(r=>({previewId:id,rowKey:r.key,outcome:'defer',actorId:f.officerId,justification:'Engineering fixture: source correction required before any load',evidenceIds}))});
 const person=await db.person.findFirstOrThrow({where:{isActive:true,deletedAt:null}});await db.person.update({where:{id:person.id},data:{fullNameEn:person.fullNameEn+' changed'}});try{await assert.rejects(service.review(f.dmoId,id,review),/configuration changed/);}finally{await db.person.update({where:{id:person.id},data:{fullNameEn:person.fullNameEn}});}
 await assert.rejects(db.aiMigrationPreviewReview.create({data:{previewId:id,outcome:'accept',actorId:f.officerId,justification:'Self-review must fail',evidenceIds}}),/independent/);await assert.rejects(failed.review(f.dmoId,id,review),/Injected/);assert.equal(await db.aiMigrationPreviewReview.count({where:{previewId:id}}),0);
 const reviewed=await service.review(f.dmoId,id,review);assert.equal(reviewed.productionReady,false);assert.equal(reviewed.outcome,'accept');assert.equal((await service.get(f.auditorId,id)).review?.id,reviewed.id);await assert.rejects(service.review(f.dmoId,id,review),/closed/);await assert.rejects(db.aiMigrationPreviewReview.delete({where:{id:reviewed.id}}),/append-only/);await assert.rejects(service.disposition(f.officerId,id,disposition),/closed/);
 const another=await service.create(f.officerId,{...dto,requestKey:randomUUID()});await service.review(f.dmoId,another.id,{...review,outcome:'reject',expectedDigest:another.digest});assert.equal((await service.list(f.auditorId,1,1)).total,2);assert.notEqual((await service.list(f.auditorId,1,1)).rows[0].id,(await service.list(f.auditorId,2,1)).rows[0].id);
 const jwt=app.get(JwtService),base=await app.getUrl(),headers={authorization:'Bearer '+jwt.sign({sub:f.officerId,tokenVersion:0,roles:['system_admin']}),'content-type':'application/json'};
 assert.equal((await fetch(base+'/api/ai/migration-previews/'+id,{headers})).status,200);assert.equal((await fetch(base+'/api/ai/migration-previews')).status,401);assert.equal((await fetch(base+'/api/ai/migration-previews',{method:'POST',headers,body:JSON.stringify({...dto,requestKey:randomUUID(),mode:'COMMIT',sourcePath:'C:/unknown',loadedCount:66})})).status,400);assert.equal((await fetch(base+'/api/ai/migration-previews/'+id+'/export?format=csv',{headers})).headers.get('content-type'),'text/csv; charset=utf-8');
 await db.user.update({where:{id:f.officerId},data:{isActive:false}});try{await assert.rejects(service.get(f.officerId,id),/explicit eligible/);}finally{await db.user.update({where:{id:f.officerId},data:{isActive:true}});}
 assert.deepEqual({risks:await db.aiRisk.count(),library:await db.aiRiskLibraryEntry.count(),assets:await db.dataAsset.count(),cases:await db.workflowCase.count(),actions:await db.aiTreatmentAction.count()},baseline);assert.equal(governanceDigest(sourceFixture()),governanceDigest(sourceFixture()));console.log('AI source previews: replay, audit rollback, quarantine, scope, independent review, immutable history, exports and no target mutations passed');
 await testSourceCorrections(db,app,id,f);
}
