import assert from 'node:assert/strict';
import { PrismaClient } from '@prisma/client';
import { AuditService } from '../src/audit/audit.service';
import { ScopeService } from '../src/access/scope.service';
import { PrismaService } from '../src/prisma/prisma.service';
import { AiAuthorizationService } from '../src/ai-governance/ai-authorization.service';
import { AiIdentifiersService } from '../src/ai-governance/ai-identifiers.service';
import { AiRiskIntakeService } from '../src/ai-governance/ai-risk-intake.service';
import { AiWorkflowRoutingService } from '../src/ai-governance/ai-workflow-routing.service';
import { AiTreatmentService } from '../src/ai-governance/ai-treatment.service';
export async function testPhase3F1(db:PrismaClient,f:{riskId:string;riskOwnerId:string;officerId:string;auditorId:string}) {
 const prisma=db as PrismaService,audit=new AuditService(prisma),scope=new ScopeService(prisma),auth=new AiAuthorizationService(prisma,audit),routing=new AiWorkflowRoutingService(prisma),ids=new AiIdentifiersService();
 const risks=new AiRiskIntakeService(prisma,auth,scope,routing,ids,audit),service=new AiTreatmentService(prisma,auth,risks,routing,ids,scope,audit);
 const failed=new AiTreatmentService(prisma,auth,risks,routing,ids,scope,{logRequired:async()=>{throw new Error('Injected execution audit failure');}} as unknown as AuditService);
 const model=await db.user.findUniqueOrThrow({where:{email:'AI_MODEL_OWNER@phase3b.test'}}),role=await db.role.findUniqueOrThrow({where:{code:'AI_MODEL_OWNER'}}),evidence=await db.ndiEvidence.findFirstOrThrow({where:{deletedAt:null}});
 let context=await service.context(model.id,f.riskId),version=context.version;
 const [first,second]=context.actions,original=await db.workflowTask.findUniqueOrThrow({where:{id:first.workflowTaskId!}});
 const snapshot=await db.aiTreatmentPlan.findFirstOrThrow({where:{response:{is:{riskId:f.riskId}},decision:{is:{decision:'approve'}}}});
 const dto=(completionPct:number,evidenceIds:string[]=[])=>({expectedVersion:version,completionPct,justification:'Verified execution update from accountable executor',evidenceIds});
 assert.equal(first.canExecute,true);assert.equal(context.completionPct,0);
 await assert.rejects(service.execute(f.riskOwnerId,f.riskId,first.id,dto(35)),/assigned executor/);
 await assert.rejects(service.execute(model.id,f.riskId,first.id,{...dto(35),completionPct:101}),/integer/);
 await assert.rejects(service.execute(model.id,f.riskId,first.id,{...dto(35),justification:' '}),/required/);
 await assert.rejects(service.execute(model.id,f.riskId,first.id,{...dto(35),expectedVersion:version-1}),/changed/);
 const excluded=await db.roleDataScope.create({data:{roleId:role.id,scopeType:'org_unit',refId:'excluded-execution-org',includeDescendants:false}});
 await assert.rejects(service.execute(model.id,f.riskId,first.id,dto(35)),/not found/);await db.roleDataScope.delete({where:{id:excluded.id}});
 const person=await db.person.findUniqueOrThrow({where:{userId:model.id}});await db.person.update({where:{id:person.id},data:{isActive:false}});
 await assert.rejects(service.execute(model.id,f.riskId,first.id,dto(35)),/active assigned/);await db.person.update({where:{id:person.id},data:{isActive:true}});
 await db.user.update({where:{id:model.id},data:{isActive:false}});await assert.rejects(service.execute(model.id,f.riskId,first.id,dto(35)),/explicit eligible/);await db.user.update({where:{id:model.id},data:{isActive:true}});
 await db.userRole.create({data:{userId:f.auditorId,roleId:role.id}});await assert.rejects(service.execute(f.auditorId,f.riskId,first.id,dto(35)),/explicit eligible/);await db.userRole.delete({where:{userId_roleId:{userId:f.auditorId,roleId:role.id}}});
 // A posted/modified task approver hint cannot replace the immutable approver identity.
 await db.userRole.create({data:{userId:f.officerId,roleId:role.id}});
 await db.workflowTask.update({where:{id:original.id},data:{assigneeUserId:f.officerId,formDataJson:{...(original.formDataJson as object),planApproverId:model.id}}});
 await assert.rejects(service.execute(f.officerId,f.riskId,first.id,dto(35)),/GEN-28/);
 await db.workflowTask.update({where:{id:original.id},data:{assigneeUserId:model.id,formDataJson:original.formDataJson!}});await db.userRole.delete({where:{userId_roleId:{userId:f.officerId,roleId:role.id}}});
 await db.workflowTask.update({where:{id:original.id},data:{dueDate:new Date(Date.now()-86400000)}});
 assert.equal((await service.context(model.id,f.riskId)).actions[0].overdue,true);await assert.rejects(service.execute(model.id,f.riskId,first.id,dto(35)),/provenance changed/);
 await db.workflowTask.update({where:{id:original.id},data:{dueDate:original.dueDate}});
 await assert.rejects(failed.execute(model.id,f.riskId,first.id,dto(35)),/Injected execution audit failure/);
 assert.equal(await db.aiTreatmentProgress.count({where:{actionId:first.id}}),0);assert.equal((await db.workflowTask.findUniqueOrThrow({where:{id:original.id}})).status,'pending');
 const progressed=await Promise.allSettled([service.execute(model.id,f.riskId,first.id,dto(35)),service.execute(model.id,f.riskId,first.id,dto(35))]);assert.equal(progressed.filter(r=>r.status==='fulfilled').length,1);version++;
 context=await service.context(model.id,f.riskId);assert.equal(context.completionPct,17.5);assert.equal(context.actions[0].completionPct,35);
 await assert.rejects(service.execute(model.id,f.riskId,first.id,dto(100)),/requires execution evidence/);
 await assert.rejects(service.execute(model.id,f.riskId,first.id,dto(100,['00000000-0000-4000-8000-000000000001'])),/must exist/);
 await assert.rejects(failed.execute(model.id,f.riskId,first.id,dto(100,[evidence.id])),/Injected execution audit failure/);
 assert.equal((await db.workflowTask.findUniqueOrThrow({where:{id:original.id}})).status,'in_progress');
 const completed=await Promise.allSettled([service.execute(model.id,f.riskId,first.id,dto(100,[evidence.id])),service.execute(model.id,f.riskId,first.id,dto(100,[evidence.id]))]);assert.equal(completed.filter(r=>r.status==='fulfilled').length,1);version++;
 await assert.rejects(service.execute(model.id,f.riskId,first.id,dto(50)),/Completed action/);
 context=await service.context(model.id,f.riskId);assert.equal(context.completionPct,50);assert.equal(context.actions[0].canExecute,false);assert.ok(context.actions[0].closureDate);
 await service.execute(model.id,f.riskId,second.id,dto(100,[evidence.id]));version++;
 context=await service.context(f.officerId,f.riskId);assert.equal(context.completionPct,100);assert.ok(context.actions.every(action=>!action.canExecute&&!action.overdue));
 const ledger=await db.aiTreatmentProgress.findFirstOrThrow({where:{actionId:first.id},orderBy:{round:'asc'}});
 await assert.rejects(db.aiTreatmentProgress.update({where:{id:ledger.id},data:{completionPct:90}}));await assert.rejects(db.aiTreatmentProgress.delete({where:{id:ledger.id}}));
 assert.deepEqual((await db.aiTreatmentPlan.findUniqueOrThrow({where:{id:snapshot.id}})).snapshot,snapshot.snapshot);
 assert.equal((await db.workflowTask.findUniqueOrThrow({where:{id:original.id}})).dueDate!.getTime(),original.dueDate!.getTime());
 assert.equal((await db.aiRisk.findUniqueOrThrow({where:{id:f.riskId}})).version,version);assert.equal(await db.aiAssessmentRound.count({where:{riskId:f.riskId,kind:'residual'}}),0);
 console.log('Phase 3F1 passed: assigned executor/live scope/activity/Auditor controls, immutable approver GEN-28, provenance/deadline protection, required completion evidence, audit rollback, concurrent exactly-once progress/completion, immutable execution ledger, computed mean/overdue/closure and no residual fabrication.');
}
