import { testReportingLibrary } from './ai-reporting-library.integration';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { PrismaClient } from '@prisma/client';
import { AiDashboardService } from '../src/ai-governance/ai-dashboard.service';
import { CoverageTask, dimensionCoverage, ethicsCoverage } from '../src/ai-governance/ai-governance-coverage';
import { RISK_DIMENSIONS, RISK_DIMENSION_ROLES, jsonRecord } from '../src/ai-governance/ai-risk-scoring';

export async function testPhase3VW(db:PrismaClient,service:AiDashboardService,f:{riskId:string;officerId:string;riskOwnerId:string;auditorId:string}){
 const asOf=new Date(),due=new Date(asOf.getTime()-60000),actor=randomUUID(),caseId=randomUUID();
 const config={referenceVersions:{R_SCORE14:randomUUID(),R_IMPD:randomUUID(),R_LEVEL:randomUUID()},dimensions:RISK_DIMENSIONS.map(d=>({dimension:d,assessorRoleCode:RISK_DIMENSION_ROLES[d]}))};
 const coordinator:CoverageTask={id:randomUUID(),caseId,stageCode:'airs-inherent-assessment',status:'pending',assigneeRoleCode:null,assigneeUserId:null,formSubmittedBy:null,completedAt:null,dueDate:due,createdAt:due,formDataJson:{assessmentRound:1,configuration:config}};
 const contributions:CoverageTask[]=RISK_DIMENSIONS.map(d=>({...coordinator,id:randomUUID(),status:'completed',assigneeRoleCode:RISK_DIMENSION_ROLES[d],assigneeUserId:actor,formSubmittedBy:actor,completedAt:due,formDataJson:{coordinatorTaskId:coordinator.id,dimension:d,assessmentRound:1,assessedRoleCode:RISK_DIMENSION_ROLES[d],assessedBy:actor,score:{value:2,justification:'Documented dimension finding'}}}));
 assert.equal(dimensionCoverage(coordinator,contributions,asOf).complete,true);assert.equal(coordinator.status,'pending');
 for(const change of [{status:'pending'},{status:'cancelled'},{caseId:randomUUID()},{stageCode:'other'},{assigneeRoleCode:'system_admin'},{formSubmittedBy:randomUUID()},{completedAt:new Date(asOf.getTime()+60000)},{formDataJson:{...jsonRecord(contributions[0].formDataJson),assessmentRound:2}},{formDataJson:{...jsonRecord(contributions[0].formDataJson),coordinatorTaskId:randomUUID()}},{formDataJson:{...jsonRecord(contributions[0].formDataJson),score:{value:2,justification:'  '}}},{formDataJson:{...jsonRecord(contributions[0].formDataJson),score:{value:5,justification:'Out of scale'}}}])assert.equal(dimensionCoverage(coordinator,[{...contributions[0],...change},...contributions.slice(1)],asOf).complete,false);
 assert.equal(dimensionCoverage(coordinator,[...contributions,{...contributions[0],id:randomUUID()}],asOf).complete,false);
 assert.equal(dimensionCoverage({...coordinator,formDataJson:{assessmentRound:1}},contributions,asOf).complete,false);
 const decision=randomUUID(),evidence=randomUUID(),ethicsTask={...contributions[0],stageCode:'aiuc-ethics-review',assigneeRoleCode:'AI_ETHICS_COMMITTEE',formDataJson:{classificationDecisionId:decision,reviewDecision:'return',justification:'Independent evidenced finding',evidenceIds:[evidence]}};
 for(const reviewDecision of ['approve','return','reject'])assert.equal(ethicsCoverage(decision,{approvedTierCode:'HIGH'},[{...ethicsTask,formDataJson:{...ethicsTask.formDataJson,reviewDecision}}],asOf,randomUUID(),null).reviewed,true);
 assert.equal(ethicsCoverage(randomUUID(),{approvedTierCode:'HIGH'},[ethicsTask],asOf,randomUUID(),null).reviewed,false);
 assert.equal(ethicsCoverage(decision,{approvedTierCode:'HIGH'},[ethicsTask],asOf,actor,null).reviewed,false);
 assert.equal(ethicsCoverage(decision,{approvedTierCode:'HIGH'},[ethicsTask],asOf,randomUUID(),actor).reviewed,false);
 assert.equal(ethicsCoverage(decision,{approvedTierCode:'HIGH'},[{...ethicsTask,formDataJson:{...ethicsTask.formDataJson,evidenceIds:[]}}],asOf,randomUUID(),null).reviewed,false);
 assert.deepEqual(ethicsCoverage(decision,{proposedTierCode:'HIGH',approvedTierCode:'MINIMAL'},[],asOf,actor,null),{high:false,mandatory:true,reviewed:false});assert.equal(ethicsCoverage(decision,{approvedTierCode:'UNACCEPTABLE'},[],asOf,actor,null).mandatory,true);assert.equal(ethicsCoverage(decision,{proposedTierCode:'HIGH'},[],asOf,actor,null).mandatory,false);

 const before=await service.summary(f.officerId),g=before.governance!,risk=await db.aiRisk.findUniqueOrThrow({where:{id:f.riskId},include:{useCase:true}});
 const template=await db.workflowTemplate.findFirstOrThrow({where:{code:'AIRS_LIFECYCLE_V1',isActive:true}}),stage=await db.workflowTemplateStage.findFirstOrThrow({where:{templateId:template.id,code:'airs-inherent-assessment'}});
 const wc=await db.workflowCase.create({data:{code:'AIRS-2026-990100',title:'Coverage integration fixture',type:'AIRS',templateId:template.id,createdBy:f.officerId}}),r=await db.aiRisk.create({data:{useCaseId:risk.useCaseId,workflowCaseId:wc.id,riskRef:'AIR-990100',title:wc.title,cause:'Fixture cause',event:'Fixture event',effect:'Fixture effect',createdBy:f.officerId}});
 const sourceTasks=await db.workflowTask.findMany({where:{caseId:risk.workflowCaseId!,templateStage:{is:{code:'airs-inherent-assessment'}}},orderBy:{createdAt:'desc'},select:{formDataJson:true}}),nativeConfig=jsonRecord(sourceTasks.find(t=>jsonRecord(t.formDataJson)['configuration'])?.formDataJson)['configuration'];assert.ok(nativeConfig,'Native pinned configuration fixture is required');
 async function round(n:number,count:number,deadline:Date|null){const c=await db.workflowTask.create({data:{caseId:wc.id,templateStageId:stage.id,title:'Coordinator '+n,dueDate:deadline,createdAt:new Date(due.getTime()+n),formDataJson:{assessmentRound:n,configuration:nativeConfig as any}}});for(const d of RISK_DIMENSIONS.slice(0,count)){const user=await db.user.findFirstOrThrow({where:{isActive:true,userRoles:{some:{role:{code:RISK_DIMENSION_ROLES[d],isActive:true}}}}});await db.workflowTask.create({data:{caseId:wc.id,templateStageId:stage.id,title:d,status:'completed',assigneeRoleCode:RISK_DIMENSION_ROLES[d],assigneeUserId:user.id,formSubmittedBy:user.id,completedAt:due,formDataJson:{coordinatorTaskId:c.id,assessmentRound:n,dimension:d,assessedRoleCode:RISK_DIMENSION_ROLES[d],assessedBy:user.id,score:{value:2,justification:'Verified native fixture finding'}}}});}return c;}
 await round(1,7,due);let s=await service.summary(f.officerId);assert.equal(s.governance!.assessmentDue,g.assessmentDue+1);assert.equal(s.governance!.assessmentComplete,g.assessmentComplete);assert.ok((await service.drilldown(f.officerId,'assessment_gaps',1,100)).data.some(x=>x['reference']===r.riskRef&&x['validDimensions']===7));
 await round(2,8,due);s=await service.summary(f.officerId);assert.equal(s.governance!.assessmentDue,g.assessmentDue+1);assert.equal(s.governance!.assessmentComplete,g.assessmentComplete+1);assert.ok(!(await service.drilldown(f.officerId,'assessment_gaps',1,100)).data.some(x=>x['reference']===r.riskRef));
 await round(3,0,null);s=await service.summary(f.officerId);assert.equal(s.governance!.assessmentDue,g.assessmentDue);assert.equal(s.governance!.assessmentMissingDeadline,g.assessmentMissingDeadline+1);
 const aiucTemplate=await db.workflowTemplate.findFirstOrThrow({where:{code:'AIUC_APPROVAL_V1',isActive:true}}),ethicsStage=await db.workflowTemplateStage.findFirstOrThrow({where:{templateId:aiucTemplate.id,code:'aiuc-ethics-review'}}),ref=await db.governedReferenceVersion.findFirstOrThrow({where:{listCode:'R_SDAIA_TIER',state:'published'},orderBy:{version:'desc'}}),ev=await db.ndiEvidence.findFirstOrThrow(),ec=await db.user.findFirstOrThrow({where:{isActive:true,id:{not:risk.useCase.requesterUserId},userRoles:{some:{role:{code:'AI_ETHICS_COMMITTEE',isActive:true}}}}});
 const cases:Array<{u:{id:string};result:{approvedTierCode:string;proposedTierCode:string}}>=[];
 for(let n=0;n<4;n++){const c=await db.workflowCase.create({data:{code:'AIUC-2026-'+(990100+n),title:'Current Ethics coverage fixture '+n,type:'AIUC',templateId:aiucTemplate.id,createdBy:f.officerId}}),u=await db.aiUseCase.create({data:{workflowCaseId:c.id,requesterUserId:risk.useCase.requesterUserId,organizationUnitId:risk.useCase.organizationUnitId,name:c.title,createdBy:f.officerId,intakeRevisions:{create:{revision:1,payload:{},submittedAt:due,createdBy:f.officerId}}}}),result=n<2?{approvedTierCode:'HIGH',proposedTierCode:'HIGH'}:n===2?{approvedTierCode:'MINIMAL',proposedTierCode:'HIGH'}:{approvedTierCode:'UNACCEPTABLE',proposedTierCode:'UNACCEPTABLE'},d=await db.aiAssessmentRound.create({data:{useCaseId:u.id,kind:'classification',round:1,engineVersion:'coverage-test-v1',ruleReferenceVersionId:ref.id,inputs:{},result,createdBy:f.officerId}});if(n!==1)await db.workflowTask.create({data:{caseId:c.id,templateStageId:ethicsStage.id,title:'Ethics finding',status:'completed',assigneeRoleCode:'AI_ETHICS_COMMITTEE',assigneeUserId:ec.id,formSubmittedBy:ec.id,completedAt:due,formDataJson:{classificationDecisionId:n===2?randomUUID():d.id,reviewDecision:n===3?'reject':'return',justification:'Independent evidenced committee outcome',evidenceIds:[ev.id]}}});cases.push({u,result});}
 s=await service.summary(f.officerId);assert.equal(s.governance!.high,g.high+2);assert.equal(s.governance!.highReviewed,g.highReviewed+1);assert.equal(s.governance!.mandatory,g.mandatory+4);assert.equal(s.governance!.mandatoryReviewed,g.mandatoryReviewed+2);
 const gaps=await service.drilldown(f.officerId,'ethics_gaps',1,1);assert.equal(gaps.total,s.governance!.high-s.governance!.highReviewed);assert.equal((await service.drilldown(f.officerId,'mandatory_ethics_gaps',1,1)).total,s.governance!.mandatory-s.governance!.mandatoryReviewed);
 await db.aiAssessmentRound.create({data:{useCaseId:cases[0].u.id,kind:'classification',round:2,engineVersion:'coverage-test-v1',ruleReferenceVersionId:ref.id,inputs:{},result:cases[0].result,createdBy:f.officerId}});s=await service.summary(f.officerId);assert.equal(s.governance!.highReviewed,g.highReviewed);assert.equal(s.governance!.high,g.high+2);
 await assert.rejects(service.drilldown(f.riskOwnerId,'assessment_gaps'),/authority/);await assert.rejects(service.drilldown(f.riskOwnerId,'ethics_gaps'),/authority/);const exec=await db.user.findFirstOrThrow({where:{isActive:true,userRoles:{some:{role:{code:'AI_EXECUTIVE_TEAM',isActive:true}}}}});assert.equal((await service.summary(exec.id)).governance,null);await assert.rejects(service.drilldown(exec.id,'ethics_gaps'),/aggregate only/);assert.equal((await service.summary(f.riskOwnerId)).governance,null);assert.equal((await service.drilldown(f.auditorId,'mandatory_ethics_gaps')).readOnly,true);
 const role=await db.role.findUniqueOrThrow({where:{code:'AI_GOVERNANCE_OFFICER'}}),scope=await db.roleDataScope.create({data:{roleId:role.id,scopeType:'org_unit',refId:randomUUID()}});const empty=await service.summary(f.officerId);for(const id of ['GEN-100','GEN-101'])assert.equal(empty.cards.find(k=>k.id===id)!.value,null);assert.equal((await service.drilldown(f.officerId,'assessment_gaps')).total,0);assert.equal((await service.drilldown(f.officerId,'ethics_gaps')).total,0);await db.roleDataScope.delete({where:{id:scope.id}});
 await testReportingLibrary(db,f);
 console.log('Phases 3V/3W passed: due/current/non-cancelled eight-dimension provenance, superseded rounds/missing deadlines, exact approved HIGH versus mandatory Ethics cohorts, independent evidenced current decision outcomes, old review invalidation, full-denominator gap pagination, empty scoped ratios and executive/owner/Auditor privacy.');
}
