import assert from 'node:assert/strict';
import { ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import { PrismaClient } from '@prisma/client';
import { AppModule } from '../src/app.module';
import { PrismaService } from '../src/prisma/prisma.service';
import { AuditService } from '../src/audit/audit.service';
import { ScopeService } from '../src/access/scope.service';
import { AiAuthorizationService } from '../src/ai-governance/ai-authorization.service';
import { AiIdentifiersService } from '../src/ai-governance/ai-identifiers.service';
import { AiRiskIntakeService } from '../src/ai-governance/ai-risk-intake.service';
import { AiWorkflowRoutingService } from '../src/ai-governance/ai-workflow-routing.service';
import { AiTreatmentService } from '../src/ai-governance/ai-treatment.service';
import { ACTION_TYPES } from '../src/ai-governance/ai-treatment.dto';
import { jsonRecord } from '../src/ai-governance/ai-risk-scoring';
import { testPhase3F1 } from './ai-phase3f1.integration';
export async function testPhase3E(db: PrismaClient,f:{riskId:string;riskOwnerId:string;officerId:string;otherRiskOwnerId:string;auditorId:string}) {
 const prisma=db as PrismaService,audit=new AuditService(prisma),scope=new ScopeService(prisma),auth=new AiAuthorizationService(prisma,audit),routing=new AiWorkflowRoutingService(prisma),ids=new AiIdentifiersService();
 const risks=new AiRiskIntakeService(prisma,auth,scope,routing,ids,audit),service=new AiTreatmentService(prisma,auth,risks,routing,ids,scope,audit);
 const failed=new AiTreatmentService(prisma,auth,risks,routing,ids,scope,{logRequired:async()=>{throw new Error('Injected plan audit failure');}} as unknown as AuditService);
 const risk=await db.aiRisk.findUniqueOrThrow({where:{id:f.riskId}}),model=await db.user.findUniqueOrThrow({where:{email:'AI_MODEL_OWNER@phase3b.test'}}),evidence=await db.ndiEvidence.findFirstOrThrow({where:{deletedAt:null}});
 await db.person.upsert({where:{userId:model.id},create:{userId:model.id,fullNameEn:'Model executor',fullNameAr:'منفذ النموذج'},update:{}});
 const target=new Date(Date.now()+40*86400000).toISOString().slice(0,10);
 const action=(expectedVersion:number,assigneeUserId=model.id)=>({expectedVersion,title:'Evidence-backed preventive control',description:'Implement and validate a documented preventive control',actionType:'PREVENTIVE' as const,priorityCode:'HIGH',assigneeUserId,targetDate:target,evidenceRequired:'Test report and approved control evidence',evidenceIds:[evidence.id],taskType:'evidence_upload'});
 const decision=(expectedVersion:number,choice:'approve'|'return'='approve')=>({expectedVersion,decision:choice,justification:'Independent completeness, evidence and execution review',evidenceIds:[evidence.id]});
 async function publish(listCode:string) {
  await db.governedReferenceList.upsert({where:{code:listCode},create:{code:listCode,nameEn:listCode,nameAr:listCode,ownerRoleCode:'AI_GOVERNANCE_OFFICER'},update:{}});
  await db.governedReferenceVersion.updateMany({where:{listCode,state:'published'},data:{state:'retired',effectiveTo:new Date()}});
  const prior=await db.governedReferenceVersion.aggregate({where:{listCode},_max:{version:true}}),codes=listCode==='R_ACTTYPE'?[...ACTION_TYPES]:['LOW','NORMAL','HIGH','CRITICAL'];
  const row=await db.governedReferenceVersion.create({data:{listCode,version:(prior._max.version??0)+1,createdBy:'phase3e-synthetic-fixture',values:{create:codes.map((code,index)=>({code,labelEn:code,labelAr:code,sortOrder:index+1,...(listCode==='R_PRIORITY'?{metadata:{dgopPriorityCode:code}}:{})}))}}});
  await db.governedReferenceVersion.update({where:{id:row.id},data:{state:'published',effectiveFrom:new Date('2020-01-01'),approvedAt:new Date('2020-01-01'),approvedBy:'phase3e-synthetic-fixture'}});return row.id;
 }
 let version=(await service.context(f.riskOwnerId,f.riskId)).version;
 await assert.rejects(service.submit(f.riskOwnerId,f.riskId,version),/At least one/);
 await assert.rejects(service.save(f.riskOwnerId,f.riskId,action(version)),/Published/);
 await publish('R_ACTTYPE');const priorityRef=await publish('R_PRIORITY');
 await assert.rejects(service.save(f.otherRiskOwnerId,f.riskId,action(version)),/assigned Risk Owner/);
 await assert.rejects(service.save(f.riskOwnerId,f.riskId,{...action(version),evidenceRequired:''}),/required/);
 await assert.rejects(service.save(f.riskOwnerId,f.riskId,{...action(version),targetDate:'2026-02-30'}),/calendar date/);
 await assert.rejects(service.save(f.riskOwnerId,f.riskId,{...action(version),startDate:'2099-01-01'}),/not before/);
 await assert.rejects(service.save(f.riskOwnerId,f.riskId,action(version,f.riskOwnerId)),/eligible treatment executor/);
 await assert.rejects(failed.save(f.riskOwnerId,f.riskId,action(version)),/Injected plan audit failure/);
 assert.equal(await db.aiTreatmentAction.count({where:{riskId:f.riskId}}),0);
 const claims=await Promise.allSettled([service.save(f.riskOwnerId,f.riskId,action(version)),service.save(f.riskOwnerId,f.riskId,action(version))]);
 assert.equal(claims.filter(r=>r.status==='fulfilled').length,1);version++;
 let context=await service.context(f.riskOwnerId,f.riskId),first=context.actions[0];assert.match(first.actionRef,/^ACT-\d{3}$/);assert.equal(first.workflowTaskId,null);
 await assert.rejects(service.save(f.riskOwnerId,f.riskId,action(version-1),first.id),/changed/);
 const modelRole=await db.role.findUniqueOrThrow({where:{code:'AI_MODEL_OWNER'}}),excluded=await db.roleDataScope.create({data:{roleId:modelRole.id,scopeType:'org_unit',refId:'excluded-treatment-org',includeDescendants:false}});
 await assert.rejects(service.submit(f.riskOwnerId,f.riskId,version),/scope/);await db.roleDataScope.delete({where:{id:excluded.id}});
 await db.user.update({where:{id:model.id},data:{isActive:false}});await assert.rejects(service.submit(f.riskOwnerId,f.riskId,version),/explicit eligible/);await db.user.update({where:{id:model.id},data:{isActive:true}});
 await assert.rejects(failed.submit(f.riskOwnerId,f.riskId,version),/Injected plan audit failure/);
 await service.submit(f.riskOwnerId,f.riskId,version++);context=await service.context(f.officerId,f.riskId);
 assert.equal(context.canReview,true);assert.equal((await service.context(f.riskOwnerId,f.riskId)).canEdit,false);
 await assert.rejects(service.save(f.riskOwnerId,f.riskId,action(version),first.id),/frozen/);
 await assert.rejects(db.aiTreatmentAction.update({where:{id:first.id},data:{title:'Changed',version:{increment:1}}}));
 await assert.rejects(db.aiTreatmentAction.update({where:{id:first.id},data:{deletedAt:new Date(),version:{increment:1}}}));
 await db.governedReferenceVersion.update({where:{id:priorityRef},data:{state:'retired',effectiveTo:new Date()}});
 assert.equal((await service.context(f.officerId,f.riskId)).canApprove,false);
 await assert.rejects(service.review(f.officerId,f.riskId,context.taskId!,decision(version)),/references changed/);
 await assert.rejects(failed.review(f.officerId,f.riskId,context.taskId!,decision(version,'return')),/Injected plan audit failure/);
 await service.review(f.officerId,f.riskId,context.taskId!,decision(version++,'return'));await publish('R_PRIORITY');
 const officerModel=await db.userRole.create({data:{userId:f.officerId,roleId:modelRole.id}});
 await db.person.upsert({where:{userId:f.officerId},create:{userId:f.officerId,fullNameEn:'Combined officer/executor',fullNameAr:'مسؤول ومنفذ'},update:{}});
 await service.save(f.riskOwnerId,f.riskId,action(version++,f.officerId),first.id);await service.submit(f.riskOwnerId,f.riskId,version++);
 context=await service.context(f.officerId,f.riskId);assert.equal(context.canReview,false);
 await assert.rejects(service.review(f.officerId,f.riskId,context.taskId!,decision(version)),/GEN-28/);
 // Another independent officer can return a plan whose designated approver is also its executor.
 const officerRole=await db.role.findUniqueOrThrow({where:{code:'AI_GOVERNANCE_OFFICER'}}),independent=await db.user.create({data:{email:'independent-plan@phase3e.test',displayName:'Independent plan officer',passwordHash:'not-a-login',userRoles:{create:{roleId:officerRole.id}}}});
 await service.review(independent.id,f.riskId,context.taskId!,decision(version++,'return'));
 await db.userRole.delete({where:{userId_roleId:{userId:officerModel.userId,roleId:officerModel.roleId}}});
 await service.save(f.riskOwnerId,f.riskId,action(version++),first.id);
 const second=await service.save(f.riskOwnerId,f.riskId,{...action(version++),title:'Corrective follow-up',actionType:'CORRECTIVE',taskType:'investigation'});
 await service.submit(f.riskOwnerId,f.riskId,version++);context=await service.context(f.officerId,f.riskId);
 await db.userRole.create({data:{userId:f.riskOwnerId,roleId:officerRole.id}});await assert.rejects(service.review(f.riskOwnerId,f.riskId,context.taskId!,decision(version)),/WF-05/);
 await db.userRole.delete({where:{userId_roleId:{userId:f.riskOwnerId,roleId:officerRole.id}}});
 await db.userRole.create({data:{userId:f.auditorId,roleId:officerRole.id}});await assert.rejects(service.review(f.auditorId,f.riskId,context.taskId!,decision(version)),/explicit eligible/);
 await db.userRole.delete({where:{userId_roleId:{userId:f.auditorId,roleId:officerRole.id}}});
 await assert.rejects(service.review(f.officerId,f.riskId,context.taskId!,{...decision(version),evidenceIds:[]}),/evidence/);
 await assert.rejects(failed.review(f.officerId,f.riskId,context.taskId!,decision(version)),/Injected plan audit failure/);
 assert.equal(await db.aiTreatmentAction.count({where:{riskId:f.riskId,workflowTaskId:{not:null}}}),0);
 const approved=await Promise.allSettled([service.review(f.officerId,f.riskId,context.taskId!,decision(version)),service.review(f.officerId,f.riskId,context.taskId!,decision(version))]);
 assert.equal(approved.filter(r=>r.status==='fulfilled').length,1);version++;
 const actions=await db.aiTreatmentAction.findMany({where:{riskId:f.riskId},include:{workflowTask:true}});assert.equal(actions.length,2);
 for(const a of actions){assert.ok(a.workflowTaskId);assert.equal(a.workflowTask!.status,'pending');assert.equal(a.workflowTask!.assigneeUserId,model.id);assert.equal(a.workflowTask!.dueDate!.toISOString(),`${target}T20:59:59.999Z`);assert.equal(jsonRecord(a.workflowTask!.formDataJson)['completionPct'],0);assert.equal(jsonRecord(a.workflowTask!.formDataJson)['planApproverId'],f.officerId);}
 assert.equal(actions.find(a=>a.id===second.actionId)!.workflowTask!.type,'investigation');
 const plans=await db.aiTreatmentPlan.findMany({where:{response:{is:{riskId:f.riskId}}},include:{decision:true},orderBy:{round:'asc'}});assert.equal(plans.length,3);assert.equal(plans[0].decision!.decision,'return');
 assert.notDeepEqual(plans[0].snapshot,plans[2].snapshot);await assert.rejects(db.aiTreatmentPlan.update({where:{id:plans[0].id},data:{snapshot:{}}}));await assert.rejects(db.aiTreatmentPlanDecision.delete({where:{id:plans[2].decision!.id}}));
 await assert.rejects(db.aiTreatmentAction.update({where:{id:first.id},data:{title:'Post-approval edit',version:{increment:1}}}));
 assert.equal((await db.aiRisk.findUniqueOrThrow({where:{id:f.riskId}})).version,version);assert.equal(await db.aiAssessmentRound.count({where:{riskId:f.riskId,kind:'residual'}}),0);
 assert.equal((await db.workflowCase.findUniqueOrThrow({where:{id:risk.workflowCaseId!}})).status,'under_review');
 // MITIGATE also requires and approves a real plan, independently of the TRANSFER source above.
 const mitigate=await db.aiRisk.findUniqueOrThrow({where:{riskRef:'AIR-900'}});let v=(await service.context(f.riskOwnerId,mitigate.id)).version;
 await service.save(f.riskOwnerId,mitigate.id,action(v++));await service.submit(f.riskOwnerId,mitigate.id,v++);const gate=await service.context(f.officerId,mitigate.id);await service.review(f.officerId,mitigate.id,gate.taskId!,decision(v));
 const app=await NestFactory.create(AppModule,{logger:false});try{app.setGlobalPrefix('api');app.useGlobalPipes(new ValidationPipe({whitelist:true,forbidNonWhitelisted:true,transform:true}));await app.listen(0,'127.0.0.1');const base=await app.getUrl(),jwt=app.get(JwtService),headers={authorization:`Bearer ${jwt.sign({sub:f.riskOwnerId,tokenVersion:0,roles:['system_admin']})}`,'content-type':'application/json'};
  assert.equal((await fetch(`${base}/api/ai/risks/${f.riskId}/treatment`)).status,401);assert.equal((await fetch(`${base}/api/ai/risks/${f.riskId}/treatment`,{headers})).status,200);
  assert.equal((await fetch(`${base}/api/ai/risks/${f.riskId}/actions`,{method:'POST',headers,body:JSON.stringify({...action(version),actionRef:'ACT-999',completionPct:100,actorId:f.officerId})})).status,400);
  assert.equal((await fetch(`${base}/api/ai/risks/${f.riskId}/actions/${first.id}/progress`,{method:'POST',headers,body:JSON.stringify({expectedVersion:version,completionPct:100,justification:'Injected computed fields',evidenceIds:[evidence.id],closureDate:'2026-01-01',planApproverId:f.riskOwnerId})})).status,400);
 }finally{await app.close();}
 await testPhase3F1(db,f);
 console.log('Phase 3E passed: governed ACT records, date/evidence/executor/scope validation, immutable submitted plans, returns/reference retirement, GEN-28/WF-05/Auditor blocks, required-audit rollback, concurrent exactly-once action/approval, one-to-one assigned tasks with KSA target deadlines and HTTP protection.');
}
