import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import { PrismaClient } from '@prisma/client';
import { AppModule } from '../src/app.module';
import { AiDashboardService, percentage, average, projectRisk } from '../src/ai-governance/ai-dashboard.service';
import { AI_KPI_CATALOG } from '../src/ai-governance/ai-kpi.catalog';

export async function testPhase3RSTU(db:PrismaClient,f:{riskId:string;riskOwnerId:string;officerId:string;auditorId:string}){
 const app=await NestFactory.create(AppModule,{logger:false});
 try{
  app.setGlobalPrefix('api');app.useGlobalPipes(new ValidationPipe({whitelist:true,forbidNonWhitelisted:true,transform:true}));await app.listen(0,'127.0.0.1');
  const service=app.get(AiDashboardService),risk=await db.aiRisk.findUniqueOrThrow({where:{id:f.riskId},include:{useCase:true}}),before=await service.summary(f.officerId);
  const kpi=(s:Awaited<ReturnType<AiDashboardService['summary']>>,id:string)=>s.cards.find(k=>k.id===id)!;
  assert.equal(AI_KPI_CATALOG.length,21);assert.equal(new Set(AI_KPI_CATALOG.map(k=>k.id)).size,21);assert.equal(before.cards.length,19);assert.ok(before.catalog.filter(k=>k.coverage==='deferred').every(k=>!before.cards.some(c=>c.id===k.id)));
  assert.equal(percentage(0,0),null);assert.equal(percentage(1,3),33.33);assert.equal(average([]),null);assert.equal(average([-50,25]),-12.5);
  const fixture={id:randomUUID(),riskRef:'AIR-900000',title:'Projection contract',ownerPersonId:null,workflowCase:{status:'under_review'},reassessments:[],responses:[],actions:[],assessments:[{id:'i2',riskId:'x',kind:'inherent',round:2,inputs:{},result:{score:8,bandCode:'HIGH'}},{id:'r1',riskId:'x',kind:'residual',round:1,inputs:{inherentAssessmentId:'i1'},result:{score:2,bandCode:'LOW',likelihood:1,impactFinal:2}}]} as Parameters<typeof projectRisk>[0];
  let p=projectRisk(fixture,new Date());assert.equal(p.residualScore,null);assert.equal(p.reduction,null);assert.equal(p.completionPct,0);
  const paired={...fixture,assessments:[fixture.assessments[0],{...fixture.assessments[1],inputs:{inherentAssessmentId:'i2'},result:{score:12,bandCode:'HIGH',likelihood:3,impactFinal:4}}]};p=projectRisk(paired,new Date());assert.equal(p.residualScore,12);assert.equal(p.reduction,-50);
  p=projectRisk({...paired,reassessments:[{inherentRound:2,additionalTriggers:[{requiredInherentRound:3}]}]},new Date());assert.equal(p.inherentScore,null);assert.equal(p.residualScore,null);
  const due=new Date(Date.now()-1000),approved={...paired,responses:[{id:'response',assessmentId:'i2',plans:[{id:'plan',snapshot:{actionIds:['a','b']},decision:{decision:'approve'}}]}],actions:[{id:'a',actionRef:'ACT-900001',title:'Verified complete',responseId:'response',planData:{},workflowTask:{status:'completed',dueDate:due},progress:[{completionPct:100,completedAt:due}]},{id:'b',actionRef:'ACT-900002',title:'Overdue partial',responseId:'response',planData:{},workflowTask:{status:'pending',dueDate:due},progress:[{completionPct:50,completedAt:null}]}]} as Parameters<typeof projectRisk>[0];
  p=projectRisk(approved,new Date());assert.equal(p.hasPlan,true);assert.equal(p.treated,false);assert.equal(p.completionPct,75);assert.equal(p.actions.filter(a=>a.overdue).length,1);
  p=projectRisk({...approved,responses:approved.responses.map(r=>({...r,assessmentId:'old-inherent'}))},new Date());assert.equal(p.hasPlan,false);assert.equal(p.actions.length,0);
  p=projectRisk({...approved,actions:approved.actions.map(a=>({...a,workflowTask:{...a.workflowTask!,status:'cancelled'}}))},new Date());assert.equal(p.actions.length,0);assert.equal(p.treated,false);
  p=projectRisk({...approved,responses:approved.responses.map(r=>({...r,plans:r.plans.map(p=>({...p,snapshot:{actionIds:['a','b'],isSampleData:true}}))}))},new Date());assert.equal(p.hasPlan,false);assert.equal(p.actions.length,0);

  const refs=await db.governedReferenceVersion.findFirstOrThrow({where:{listCode:'R_SDAIA_TIER',state:'published'},orderBy:{version:'desc'}}),ids=Array.from({length:105},()=>randomUUID()),common={requesterUserId:risk.useCase.requesterUserId,createdBy:f.officerId,organizationUnitId:risk.useCase.organizationUnitId};
  const originalAsset=await db.dataAsset.findUniqueOrThrow({where:{id:risk.useCase.assetId!}}),assetIds=Array.from({length:107},()=>randomUUID()),assetRefs=assetIds.map((_,i)=>'AI-'+(i<105?990000+i:i===105?999900:999901));
  await db.dataAsset.createMany({data:assetIds.map((id,i)=>({id,code:'AST-'+assetRefs[i],nameEn:'Dashboard test asset '+i,nameAr:'أصل اختبار اللوحة '+i,assetType:'ai_data_product',assetSubtype:originalAsset.assetSubtype,orgUnitId:originalAsset.orgUnitId,domainId:originalAsset.domainId,classificationId:originalAsset.classificationId,typeMetadataJson:{aiUseCaseRef:assetRefs[i]}}))});
  await db.aiUseCase.createMany({data:ids.map((id,i)=>({...common,id,assetId:assetIds[i],useCaseRef:'AI-'+(990000+i),name:'Dashboard registered row '+i}))});
  const sample=await db.aiUseCase.create({data:{...common,assetId:assetIds[105],useCaseRef:'AI-999900',name:'Excluded sample High',isSampleData:true}});
  await db.aiUseCase.create({data:{...common,assetId:assetIds[106],useCaseRef:'AI-999901',name:'Excluded deleted record',deletedAt:new Date()}});
  for(const [id,result] of [[ids[0],{proposedTierCode:'HIGH',approvedTierCode:'HIGH'}],[ids[1],{proposedTierCode:'HIGH',approvedTierCode:'MINIMAL'}],[ids[2],{proposedTierCode:'HIGH'}],[sample.id,{approvedTierCode:'HIGH'}]] as const)await db.aiAssessmentRound.create({data:{useCaseId:id,kind:'classification',round:1,engineVersion:'dashboard-synthetic-v1',ruleReferenceVersionId:refs.id,inputs:{},result,createdBy:f.officerId}});
  let s=await service.summary(f.officerId);assert.equal(kpi(s,'GEN-85').value,kpi(before,'GEN-85').value!+105);assert.equal(kpi(s,'GEN-98').value,kpi(before,'GEN-98').value!+1);assert.equal(kpi(s,'GEN-99').value,kpi(before,'GEN-99').value!+103);assert.equal(s.reconciliation!.balanced,true);assert.equal(s.reconciliation!.sum,s.reconciliation!.total);assert.equal(s.distribution.reduce((n,u)=>n+u.count,0),s.reconciliation!.total);
  const baseline=s,template=await db.workflowTemplate.findFirstOrThrow({where:{code:'AIUC_APPROVAL_V1',isActive:true}}),triageStage=await db.workflowTemplateStage.findFirstOrThrow({where:{templateId:template.id,code:'aiuc-triage'}}),decisionStage=await db.workflowTemplateStage.findFirstOrThrow({where:{templateId:template.id,code:'aiuc-decision'}});
  for(let n=0;n<2;n++){
   const wc=await db.workflowCase.create({data:{code:'AIUC-2026-'+(990001+n),title:'Dashboard pipeline fixture '+n,type:'AIUC',status:n===0?'closed':'rejected',templateId:template.id,createdBy:f.officerId}});
   const uc=await db.aiUseCase.create({data:{requesterUserId:risk.useCase.requesterUserId,organizationUnitId:risk.useCase.organizationUnitId,workflowCaseId:wc.id,name:wc.title,createdBy:f.officerId,intakeRevisions:{create:{revision:1,payload:{},submittedAt:new Date(),createdBy:f.officerId}}}});
   const completedAt=new Date(due.getTime()+(n===0?0:1)),task=await db.workflowTask.create({data:{caseId:wc.id,title:'Synthetic completed triage',type:'review',status:'completed',templateStageId:triageStage.id,dueDate:due,completedAt}});
   await db.workflowEvent.create({data:{caseId:wc.id,taskId:task.id,actor:f.officerId,action:n===0?'aiuc.triage.accept':'aiuc.triage.return'}});
   if(n===0)await db.workflowTask.create({data:{caseId:wc.id,title:'Synthetic completed decision',type:'decision',status:'completed',templateStageId:decisionStage.id,completedAt:due,formDataJson:{adoptionDecision:{resolutionCode:'Approved'}}}});
  }
  s=await service.summary(f.officerId);assert.equal(kpi(s,'GEN-81').value,kpi(baseline,'GEN-81').value!+2);for(const [id,delta] of [['GEN-82',1],['GEN-83',1],['GEN-84',1]] as const){const old=kpi(baseline,id),next=kpi(s,id);assert.equal(next.numerator,old.numerator!+delta);assert.equal(next.denominator,old.denominator!+2);assert.equal(next.value,percentage(next.numerator!,next.denominator!));}
  const first=await service.drilldown(f.officerId,'registered',1,1),second=await service.drilldown(f.officerId,'registered',2,1);assert.ok(first.total>100);assert.equal(first.total,kpi(s,'GEN-85').value);assert.notEqual(first.rows[0]['id'],second.rows[0]['id']);assert.equal(first.readOnly,true);assert.ok((await service.drilldown(f.officerId,'sdaia_high',1,100)).rows.every(r=>r['approvedTier']==='HIGH'));assert.ok((await service.drilldown(f.officerId,'unclassified',1,100)).rows.every(r=>r['approvedTier']===null));
  const riskCount=await db.aiRisk.count({where:{deletedAt:null,isSampleData:false,riskRef:{not:null},workflowCase:{is:{type:'AIRS'}},useCase:{is:{deletedAt:null,isSampleData:false,asset:{is:{isActive:true,deletedAt:null}}}}}});assert.equal(kpi(s,'GEN-86').value,riskCount);assert.equal(s.matrix!.cells.flat().reduce((n,v)=>n+v,0),s.matrix!.assessed);assert.equal(s.matrix!.assessed+s.matrix!.unassessed,riskCount);assert.ok(s.topRisks.length<=10);for(let i=1;i<s.topRisks.length;i++)assert.ok(s.topRisks[i-1].residualScore!>=s.topRisks[i].residualScore!);
  const own=await service.summary(f.riskOwnerId);assert.equal(own.mode,'risk_owner');assert.deepEqual(own.cards.map(c=>c.id),['GEN-88','GEN-94','GEN-95','GEN-97']);assert.equal(own.reconciliation,null);assert.equal(own.matrix,null);for(const r of (await service.drilldown(f.riskOwnerId,'identified',1,100)).rows)assert.equal((await db.aiRisk.findUniqueOrThrow({where:{id:String(r['id'])},include:{owner:true}})).owner?.userId,f.riskOwnerId);await assert.rejects(service.drilldown(f.riskOwnerId,'registered'),/authority/);
  const exec=await db.user.findFirstOrThrow({where:{isActive:true,userRoles:{some:{role:{code:'AI_EXECUTIVE_TEAM',isActive:true}}}}}),executive=await service.summary(exec.id);assert.equal(executive.aggregateOnly,true);assert.equal(executive.topRisks.length,0);assert.equal(executive.distribution.length,0);assert.ok(!JSON.stringify(executive).includes(risk.riskRef!));assert.ok(!executive.cards.some(c=>c.group==='pipeline'));await assert.rejects(service.drilldown(exec.id,'identified'),/aggregate only/);assert.equal((await service.summary(f.auditorId)).mode,'audit');
  const officerRole=await db.role.findUniqueOrThrow({where:{code:'AI_GOVERNANCE_OFFICER'}}),excluded=await db.roleDataScope.create({data:{roleId:officerRole.id,scopeType:'org_unit',refId:randomUUID()}});s=await service.summary(f.officerId);assert.equal(kpi(s,'GEN-85').value,0);assert.equal(kpi(s,'GEN-86').value,0);assert.equal(kpi(s,'GEN-82').value,null);assert.equal((await service.drilldown(f.officerId,'registered')).total,0);await db.roleDataScope.delete({where:{id:excluded.id}});
  await db.dataAsset.update({where:{id:assetIds[0]},data:{isActive:false}});s=await service.summary(f.officerId);assert.equal(kpi(s,'GEN-85').value,kpi(baseline,'GEN-85').value!-1);await db.dataAsset.update({where:{id:assetIds[0]},data:{isActive:true}});await db.user.update({where:{id:f.officerId},data:{isActive:false}});await assert.rejects(service.summary(f.officerId),/active|eligible/);await db.user.update({where:{id:f.officerId},data:{isActive:true}});
  const base=await app.getUrl(),jwt=app.get(JwtService),headers={authorization:'Bearer '+jwt.sign({sub:f.officerId,tokenVersion:0,roles:['system_admin']})};assert.equal((await fetch(base+'/api/ai/dashboard',{headers})).status,200);assert.equal((await fetch(base+'/api/ai/dashboard/drilldown?filter=registered&page=0',{headers})).status,400);assert.equal((await fetch(base+'/api/ai/dashboard/drilldown?filter=raw_sql',{headers})).status,400);assert.equal((await fetch(base+'/api/ai/dashboard',{method:'POST',headers})).status,404);assert.equal((await fetch(base+'/api/ai/dashboard')).status,401);
  console.log('Phases 3R/3S/3T/3U passed: exact approved-SDAIA counts/reconciliation beyond 100 rows, sample/scope/live-identity exclusion, current residual pairing and 4x4 matrix, approved-plan completion/overdue contracts, 19 live KPIs/21 explicit definitions, stable scoped drilldown and executive/Auditor/owner HTTP privacy.');
 }finally{await app.close();}
}
