import 'reflect-metadata';
import assert from 'node:assert/strict';
import { randomUUID,createHash } from 'node:crypto';
import { readFileSync,writeFileSync } from 'node:fs';
import { NestFactory } from '@nestjs/core';
import { AppModule } from '../src/app.module';
import { PrismaService } from '../src/prisma/prisma.service';
import { AuditService } from '../src/audit/audit.service';
import { AiDashboardService } from '../src/ai-governance/ai-dashboard.service';
import { AiDashboardReportsService } from '../src/ai-governance/ai-dashboard-reports.service';
import { AiReviewReportService,aggregateReviewMeasures } from '../src/ai-governance/ai-review-report.service';
import { AiMigrationPreviewService } from '../src/ai-governance/ai-migration-preview.service';
import { AiSourceNativeService } from '../src/ai-governance/ai-source-native.service';
import { reportProofs } from '../src/ai-governance/ai-reporting-proof';
import { isManagedDemoProfile } from '../src/common/demo-profile';
const startedAt=new Date().toISOString(),checks:string[]=[],url=new URL(process.env.DATABASE_URL!),manifestBytes=readFileSync(process.env.DGOP_DEMO_MANIFEST!),manifest=JSON.parse(manifestBytes.toString());
async function main(){assert.equal(url.hostname,'127.0.0.1');assert.equal(url.port,'55438');assert.match(url.pathname,/^\/dgop_ai_test_repair_batch1_\d+$/);assert.equal(isManagedDemoProfile(),true);
 const app=await NestFactory.createApplicationContext(AppModule,{logger:false}),db=app.get(PrismaService),dashboard=app.get(AiDashboardService),reports=app.get(AiDashboardReportsService),reviews=app.get(AiReviewReportService),sources=app.get(AiMigrationPreviewService),audit=app.get(AuditService),officer=manifest.actors.officer,executive=manifest.actors.executiveViewer;
 let error:string|null=null;const tag='diagnostic:batch6:'+randomUUID(),durations:number[]=[];
 try{
  const summary=await dashboard.summary(officer),independent=await db.aiUseCase.findMany({where:{deletedAt:null,isSampleData:false,useCaseRef:{not:null},lifecycleState:{not:'retired'},asset:{is:{isActive:true,deletedAt:null}}},select:{id:true,lifecycleState:true,effectiveConfiguration:{select:{tierCode:true}},assessments:{where:{kind:'classification',riskId:null},orderBy:{round:'desc'},take:1,select:{result:true}}}});
  assert.equal(summary.reconciliation!.total,independent.length);assert.equal(summary.lifecycle.active+summary.lifecycle.suspended,independent.length);assert.equal(summary.lifecycle.retired,await db.aiUseCase.count({where:{deletedAt:null,isSampleData:false,useCaseRef:{not:null},lifecycleState:'retired',asset:{is:{isActive:true,deletedAt:null}}}}));checks.push('complete live register totals reconcile independently; retired history counted separately');
  const executiveSummary=await dashboard.summary(executive);assert.equal(executiveSummary.cards.find(c=>c.id==='GEN-86')!.value,summary.cards.find(c=>c.id==='GEN-86')!.value);assert.equal(executiveSummary.topRisks.length,0);await assert.rejects(dashboard.drilldown(executive,'registered'),/aggregate/);checks.push('governance and executive risk denominators agree; aggregate persona has no row drilldown');
  const page=await dashboard.drilldown(officer,'registered'),oversize=await dashboard.drilldown(officer,'registered',1,200);assert.equal(page.pageSize,25);assert.equal(page.totalPages,Math.max(1,Math.ceil(page.total/25)));assert.equal(oversize.total,page.total);await assert.rejects(dashboard.drilldown(officer,'registered',1,201));await assert.rejects(dashboard.drilldown(officer,'registered',1,25,'x'.repeat(201)));assert.equal((await dashboard.drilldown(officer,'registered',100)).data.length,0);checks.push('drilldowns use complete standard paging, maximum 200 and bounded search');
  const record=page.data[0];assert.ok(record);const search=await dashboard.drilldown(officer,'registered',1,25,String(record['reference']));assert.ok(search.data.some(r=>r['id']===record['id']));checks.push('server search reconciles matching register records');
  const retired=await db.aiUseCase.findFirstOrThrow({where:{lifecycleState:'retired',effectiveConfiguration:{is:{sourceRequestId:{not:null}}}},include:{effectiveConfiguration:true,risks:true}});
  const rollback=Error('rollback reporting diagnostic');let checked=false;
  try{await db.$transaction(async tx=>{await tx.aiUseCase.update({where:{id:retired.id},data:{lifecycleState:'suspended',version:{increment:1}}});const live=await dashboard.projection(tx,officer),rows=await (dashboard as any).population(tx,officer);assert.ok(rows.useCases.some((r:any)=>r.id===retired.id&&r.approvedTier===retired.effectiveConfiguration!.tierCode));assert.equal(live.lifecycle.suspended,summary.lifecycle.suspended+1);for(const r of rows.risks.filter((r:any)=>retired.risks.some(x=>x.id===r.id))){assert.equal(r.residualScore,null);assert.equal(r.hasPlan,false)}checked=true;throw rollback},{timeout:30000})}catch(e){assert.equal(e,rollback)}assert.ok(checked);assert.equal((await db.aiUseCase.findUniqueOrThrow({where:{id:retired.id}})).lifecycleState,'retired');checks.push('database-backed effective tier and reassessment projection include suspension; no old residual/plan credit; fixture rolled back');
  const retiredRiskIds=retired.risks.map(r=>r.id),measures=await db.$transaction(tx=>aggregateReviewMeasures(tx,retiredRiskIds,new Date()));assert.equal(measures.overdue,0);assert.equal(measures.due,await db.aiRiskReview.count({where:{riskId:{in:retiredRiskIds},retirement:{is:null},cancellation:{is:null},dueAt:{lte:new Date()}}}));checks.push('retirement ledgers remove pending retired reviews from due and overdue measures');
  const retiredReview=await db.aiRiskReview.findFirst({where:{riskId:{in:retiredRiskIds},retirement:{isNot:null}}});if(retiredReview)assert.equal((await reviews.detail(officer,retiredReview.id)).status,'retired');checks.push('authorized retired review details remain discoverable with a retired label');
  const unit=independent.length?(await db.aiUseCase.findUniqueOrThrow({where:{id:independent[0].id}})).organizationUnitId!:null;assert.ok(unit);
  const old=await db.aiDashboardSnapshot.findFirst({where:{organizationUnitId:unit},orderBy:{asOf:'desc'}});if(old){const saved=await reports.get(officer,old.id);assert.equal(saved.digest,old.digest);assert.deepEqual(saved.projection,old.projection);checks.push('immutable older reporting observations survive lifecycle retirement and keep their original definition')}
  const administrator=manifest.actors.administrator,adminSummary=await dashboard.summary(administrator);assert.equal(adminSummary.reconciliation!.total,summary.reconciliation!.total);assert.ok((await reports.units(administrator)).units.some(u=>u.id===unit));await assert.rejects(reports.capture(administrator,unit));assert.equal((await reports.schedule(administrator,unit)).canManage,false);assert.equal((await reports.trend(administrator,unit)).total,(await reports.list(administrator,unit)).total);await reports.currentBasis(administrator,unit,'manual');
  const executiveUnits=await reports.units(executive);assert.ok(executiveUnits.units.some(u=>u.id===unit));await assert.rejects(reports.capture(executive,unit));
  const capture=await reports.capture(officer,unit),view=await reports.get(officer,capture.id);assert.equal(view.projection['projectionVersion'],'ai-dashboard-v3');const archive=await reports.list(officer,unit,1,200),trend=await reports.trend(officer,unit,'GEN-85','manual',1,200);assert.equal(archive.data.length,archive.total);assert.equal((await reports.get(executive,capture.id)).aggregateOnly,true);assert.equal((await reports.list(executive,unit)).total,archive.total);assert.equal(trend.data.length,trend.total);const incompatible=trend.data.find(r=>r.previousAsOf&&!r.comparisonAvailable);if(incompatible)assert.equal(incompatible.delta,null);checks.push('new captures use v3; complete archive and trend pages preserve version-sensitive comparisons');
  const savedPreview=await db.aiMigrationPreview.findFirstOrThrow(),sourceAny=sources as any,originalSources=sourceAny.sources;let calls=0;sourceAny.sources=async()=>{calls++;throw Error('diagnostic source unavailable')};
  try{const replay=await sources.create(savedPreview.createdBy,{requestKey:savedPreview.requestKey,justification:savedPreview.justification,evidenceIds:savedPreview.evidenceIds as string[]});assert.equal(replay.id,savedPreview.id);assert.equal(replay.created,false);assert.equal(calls,0);await assert.rejects(sources.create(savedPreview.createdBy,{requestKey:savedPreview.requestKey,justification:'conflicting intent',evidenceIds:savedPreview.evidenceIds as string[]}),/another proposal/);assert.equal(calls,0);const count=await db.aiMigrationPreview.count(),auditCount=await db.auditLog.count();await assert.rejects(sources.create(officer,{requestKey:randomUUID(),justification:tag,evidenceIds:savedPreview.evidenceIds as string[]}),/source unavailable/);assert.equal(await db.aiMigrationPreview.count(),count);assert.equal(await db.auditLog.count(),auditCount)}finally{sourceAny.sources=originalSources}checks.push('exact replay survives unavailable sources; conflicting replay is rejected; fresh parse failure leaves no proposal or audit');
  const countBefore=await db.aiMigrationPreview.count(),auditOriginal=audit.logRequired.bind(audit);audit.logRequired=async(entry,...args)=>{if(entry.action==='ai.migration.preview.propose')throw Error('diagnostic audit rollback');return auditOriginal(entry,...args)};
  try{await assert.rejects(sources.create(officer,{requestKey:randomUUID(),justification:tag,evidenceIds:savedPreview.evidenceIds as string[]}),/audit rollback/);assert.equal(await db.aiMigrationPreview.count(),countBefore)}finally{audit.logRequired=auditOriginal}checks.push('source creation and required audit roll back atomically');
  const request={requestKey:randomUUID(),justification:tag,evidenceIds:savedPreview.evidenceIds as string[]},pair=await Promise.all([sources.create(officer,request),sources.create(officer,request)]);assert.equal(pair[0].id,pair[1].id);assert.equal(pair.filter(r=>r.created).length,1);assert.equal(await db.auditLog.count({where:{entityId:pair[0].id,action:'ai.migration.preview.propose'}}),1);assert.equal(pair[0].report['sourceMode'],'synthetic_demo');assert.equal(pair[0].productionReady,false);checks.push('concurrent source requests persist exactly one preview and audit; synthetic sources remain demo-only');
  const sourceArchive=await sources.list(officer,1,200,tag);assert.equal(sourceArchive.total,1);assert.equal(sourceArchive.data[0].id,pair[0].id);await assert.rejects(sources.list(officer,1,25,'x'.repeat(201)));checks.push('source archive has complete server search and bounded paged envelope');
  const proofStates=await db.$transaction(tx=>reportProofs(tx,[{entityType:'ai_lifecycle_request',entityId:retired.effectiveConfiguration!.sourceRequestId!}],new Date()));assert.ok([...proofStates.values()].every(s=>s!=='verified'));assert.equal(summary.governance!.evidenceBasis,'operational_verified');checks.push('synthetic or revoked lifecycle proof earns no operational ethics coverage');
  const draft=await db.aiSourceNativeDraft.findFirst();if(draft){const native=app.get(AiSourceNativeService),replayed=await native.create(draft.createdBy,draft.snapshotId,{expectedDigest:(await db.aiCorrectedSourceSnapshot.findUniqueOrThrow({where:{id:draft.snapshotId}})).digest,rowKey:draft.rowKey,requestKey:draft.requestKey,justification:draft.justification,evidenceIds:draft.evidenceIds as string[],...(draft.targetRiskId?{useCaseId:(await db.aiRisk.findUniqueOrThrow({where:{id:draft.targetRiskId}})).useCaseId}:{})});assert.equal(replayed.id,draft.id);assert.equal(replayed.created,false);checks.push('native source draft replay preserves provenance and does not duplicate native workflow')}
  for(let i=0;i<5;i++){const begin=performance.now();await dashboard.summary(officer);durations.push(Math.round(performance.now()-begin))}assert.ok(durations.every(d=>d<2000));checks.push('five warm small-profile reporting reads finish within two seconds; final capacity gate remains separate');
 }catch(e){error=e instanceof Error?e.stack??e.message:String(e);throw e}
 finally{const receipt={startedAt,finishedAt:new Date().toISOString(),database:url.pathname.slice(1),fixtureManifestSha256:createHash('sha256').update(manifestBytes).digest('hex'),installationId:process.env.DGOP_DEMO_INSTALLATION_ID,personas:{officer,executive},checks:checks.length,scenarios:checks,warmReadMs:durations,diagnosticFixtureTag:tag,diagnosticProjectionRolledBack:true,productionSourceAcceptance:false,passed:error===null,error};if(process.env.DGOP_REPORTING_RECEIPT)writeFileSync(process.env.DGOP_REPORTING_RECEIPT,JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({passed:receipt.passed,checks:receipt.checks,warmReadMs:durations,error}));await app.close()}
}
void main().catch(()=>{process.exitCode=1});
